/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { UsersResponse } from '../model';
/**
 * PublicUsersApi - axios parameter creator
 * @export
 */
export const PublicUsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Organization Admin user can list all users within the same organization. Also provide filtering on a list of user IDs or/and a list of user emails.
         * @summary List all users within an organization
         * @param {string} organizationId 
         * @param {Array<string>} [ids] List of user IDs to filter by
         * @param {Array<string>} [emails] List of user emails to filter by
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUsersWithinAnOrganization: async (organizationId: string, ids?: Array<string>, emails?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('listUsersWithinAnOrganization', 'organizationId', organizationId)
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication clientCredentials required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "clientCredentials", [], configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (organizationId !== undefined) {
                localVarQueryParameter['organizationId'] = organizationId;
            }

            if (ids) {
                localVarQueryParameter['ids'] = ids;
            }

            if (emails) {
                localVarQueryParameter['emails'] = emails;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PublicUsersApi - functional programming interface
 * @export
 */
export const PublicUsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PublicUsersApiAxiosParamCreator(configuration)
    return {
        /**
         * Organization Admin user can list all users within the same organization. Also provide filtering on a list of user IDs or/and a list of user emails.
         * @summary List all users within an organization
         * @param {string} organizationId 
         * @param {Array<string>} [ids] List of user IDs to filter by
         * @param {Array<string>} [emails] List of user emails to filter by
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listUsersWithinAnOrganization(organizationId: string, ids?: Array<string>, emails?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listUsersWithinAnOrganization(organizationId, ids, emails, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PublicUsersApi.listUsersWithinAnOrganization']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PublicUsersApi - factory interface
 * @export
 */
export const PublicUsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PublicUsersApiFp(configuration)
    return {
        /**
         * Organization Admin user can list all users within the same organization. Also provide filtering on a list of user IDs or/and a list of user emails.
         * @summary List all users within an organization
         * @param {PublicUsersApiListUsersWithinAnOrganizationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUsersWithinAnOrganization(requestParameters: PublicUsersApiListUsersWithinAnOrganizationRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersResponse> {
            return localVarFp.listUsersWithinAnOrganization(requestParameters.organizationId, requestParameters.ids, requestParameters.emails, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for listUsersWithinAnOrganization operation in PublicUsersApi.
 * @export
 * @interface PublicUsersApiListUsersWithinAnOrganizationRequest
 */
export interface PublicUsersApiListUsersWithinAnOrganizationRequest {
    /**
     * 
     * @type {string}
     * @memberof PublicUsersApiListUsersWithinAnOrganization
     */
    readonly organizationId: string

    /**
     * List of user IDs to filter by
     * @type {Array<string>}
     * @memberof PublicUsersApiListUsersWithinAnOrganization
     */
    readonly ids?: Array<string>

    /**
     * List of user emails to filter by
     * @type {Array<string>}
     * @memberof PublicUsersApiListUsersWithinAnOrganization
     */
    readonly emails?: Array<string>
}

/**
 * PublicUsersApi - object-oriented interface
 * @export
 * @class PublicUsersApi
 * @extends {BaseAPI}
 */
export class PublicUsersApi extends BaseAPI {
    /**
     * Organization Admin user can list all users within the same organization. Also provide filtering on a list of user IDs or/and a list of user emails.
     * @summary List all users within an organization
     * @param {PublicUsersApiListUsersWithinAnOrganizationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PublicUsersApi
     */
    public listUsersWithinAnOrganization(requestParameters: PublicUsersApiListUsersWithinAnOrganizationRequest, options?: RawAxiosRequestConfig) {
        return PublicUsersApiFp(this.configuration).listUsersWithinAnOrganization(requestParameters.organizationId, requestParameters.ids, requestParameters.emails, options).then((request) => request(this.axios, this.basePath));
    }
}

