/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AccessToken1
 */
export interface AccessToken1 {
    /**
     * 
     * @type {string}
     * @memberof AccessToken1
     */
    'type': AccessToken1TypeEnum;
    /**
     * Access Token for making authenticated requests.
     * @type {string}
     * @memberof AccessToken1
     */
    'access_token': string;
}

export const AccessToken1TypeEnum = {
    ACCESS_TOKEN: 'access_token'
} as const;

export type AccessToken1TypeEnum = typeof AccessToken1TypeEnum[keyof typeof AccessToken1TypeEnum];


