/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Config for custom ad Analytics Report
 * @export
 * @interface AdAnalyticsReportConfiguration
 */
export interface AdAnalyticsReportConfiguration {
    /**
     * The name for the custom report.
     * @type {string}
     * @memberof AdAnalyticsReportConfiguration
     */
    'name': string;
    /**
     * Choose a category to pivot your analytics report around. This selection will organize your data based on the chosen attribute, allowing you to analyze trends and performance from different perspectives.
     * @type {string}
     * @memberof AdAnalyticsReportConfiguration
     */
    'pivot_by': AdAnalyticsReportConfigurationPivotByEnum;
    /**
     * Choose how to group the data in your report by time. The options are:<br>- \'ALL\': A single result summarizing the entire time range.<br>- \'DAILY\': Group results by each day.<br>- \'MONTHLY\': Group results by each month.<br>- \'YEARLY\': Group results by each year.<br>Selecting a time grouping helps you analyze trends and patterns over different time periods.
     * @type {string}
     * @memberof AdAnalyticsReportConfiguration
     */
    'time_granularity': AdAnalyticsReportConfigurationTimeGranularityEnum;
}

export const AdAnalyticsReportConfigurationPivotByEnum = {
    COMPANY: 'COMPANY',
    ACCOUNT: 'ACCOUNT',
    SHARE: 'SHARE',
    CAMPAIGN: 'CAMPAIGN',
    CREATIVE: 'CREATIVE',
    CAMPAIGN_GROUP: 'CAMPAIGN_GROUP',
    CONVERSION: 'CONVERSION',
    CONVERSATION_NODE: 'CONVERSATION_NODE',
    CONVERSATION_NODE_OPTION_INDEX: 'CONVERSATION_NODE_OPTION_INDEX',
    SERVING_LOCATION: 'SERVING_LOCATION',
    CARD_INDEX: 'CARD_INDEX',
    MEMBER_COMPANY_SIZE: 'MEMBER_COMPANY_SIZE',
    MEMBER_INDUSTRY: 'MEMBER_INDUSTRY',
    MEMBER_SENIORITY: 'MEMBER_SENIORITY',
    MEMBER_JOB_TITLE: 'MEMBER_JOB_TITLE',
    MEMBER_JOB_FUNCTION: 'MEMBER_JOB_FUNCTION',
    MEMBER_COUNTRY_V2: 'MEMBER_COUNTRY_V2',
    MEMBER_REGION_V2: 'MEMBER_REGION_V2',
    MEMBER_COMPANY: 'MEMBER_COMPANY',
    PLACEMENT_NAME: 'PLACEMENT_NAME',
    IMPRESSION_DEVICE_TYPE: 'IMPRESSION_DEVICE_TYPE'
} as const;

export type AdAnalyticsReportConfigurationPivotByEnum = typeof AdAnalyticsReportConfigurationPivotByEnum[keyof typeof AdAnalyticsReportConfigurationPivotByEnum];
export const AdAnalyticsReportConfigurationTimeGranularityEnum = {
    ALL: 'ALL',
    DAILY: 'DAILY',
    MONTHLY: 'MONTHLY',
    YEARLY: 'YEARLY'
} as const;

export type AdAnalyticsReportConfigurationTimeGranularityEnum = typeof AdAnalyticsReportConfigurationTimeGranularityEnum[keyof typeof AdAnalyticsReportConfigurationTimeGranularityEnum];


