/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Allow SSL mode.
 * @export
 * @interface Allow3
 */
export interface Allow3 {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof Allow3
     */
    'mode': Allow3ModeEnum;
}

export const Allow3ModeEnum = {
    ALLOW: 'allow'
} as const;

export type Allow3ModeEnum = typeof Allow3ModeEnum[keyof typeof Allow3ModeEnum];


