/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AmazonSellerPartner
 */
export interface AmazonSellerPartner {
    /**
     * Your Login with Amazon Client ID.
     * @type {string}
     * @memberof AmazonSellerPartner
     */
    'lwa_app_id'?: string;
    /**
     * Your Login with Amazon Client Secret.
     * @type {string}
     * @memberof AmazonSellerPartner
     */
    'lwa_client_secret'?: string;
}

