/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface APIAccessToken1
 */
export interface APIAccessToken1 {
    /**
     * 
     * @type {string}
     * @memberof APIAccessToken1
     */
    'auth_type'?: APIAccessToken1AuthTypeEnum;
    /**
     * The access token to use for accessing your data from Smartsheets. This access token must be generated by a user with at least read access to the data you\'d like to replicate. Generate an access token in the Smartsheets main menu by clicking Account > Apps & Integrations > API Access. See the <a href=\"https://docs.airbyte.com/integrations/sources/smartsheets/#setup-guide\">setup guide</a> for information on how to obtain this token.
     * @type {string}
     * @memberof APIAccessToken1
     */
    'access_token': string;
}

export const APIAccessToken1AuthTypeEnum = {
    ACCESS_TOKEN: 'access_token'
} as const;

export type APIAccessToken1AuthTypeEnum = typeof APIAccessToken1AuthTypeEnum[keyof typeof APIAccessToken1AuthTypeEnum];


