/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface APIKey3
 */
export interface APIKey3 {
    /**
     * 
     * @type {string}
     * @memberof APIKey3
     */
    'auth_type': APIKey3AuthTypeEnum;
    /**
     * Mailchimp API Key. See the <a href=\"https://docs.airbyte.com/integrations/sources/mailchimp\">docs</a> for information on how to generate this key.
     * @type {string}
     * @memberof APIKey3
     */
    'apikey': string;
}

export const APIKey3AuthTypeEnum = {
    APIKEY: 'apikey'
} as const;

export type APIKey3AuthTypeEnum = typeof APIKey3AuthTypeEnum[keyof typeof APIKey3AuthTypeEnum];


