/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface APIKey1
 */
export interface APIKey1 {
    /**
     * 
     * @type {string}
     * @memberof APIKey1
     */
    'auth_type': APIKey1AuthTypeEnum;
    /**
     * The API key for a Square application
     * @type {string}
     * @memberof APIKey1
     */
    'api_key': string;
}

export const APIKey1AuthTypeEnum = {
    API_KEY: 'API Key'
} as const;

export type APIKey1AuthTypeEnum = typeof APIKey1AuthTypeEnum[keyof typeof APIKey1AuthTypeEnum];


