/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OAuth3 } from './oauth3';
// May contain unused imports in some cases
// @ts-ignore
import type { PrivateApp1 } from './private-app1';

/**
 * @type Authentication19
 * Choose how to authenticate to HubSpot.
 * @export
 */
export type Authentication19 = OAuth3 | PrivateApp1;


