/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthenticateViaHarvestOAuth1
 */
export interface AuthenticateViaHarvestOAuth1 {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof AuthenticateViaHarvestOAuth1
     */
    'auth_type'?: AuthenticateViaHarvestOAuth1AuthTypeEnum;
    /**
     * The Client ID of your Harvest developer application.
     * @type {string}
     * @memberof AuthenticateViaHarvestOAuth1
     */
    'client_id': string;
    /**
     * The Client Secret of your Harvest developer application.
     * @type {string}
     * @memberof AuthenticateViaHarvestOAuth1
     */
    'client_secret': string;
    /**
     * Refresh Token to renew the expired Access Token.
     * @type {string}
     * @memberof AuthenticateViaHarvestOAuth1
     */
    'refresh_token': string;
}

export const AuthenticateViaHarvestOAuth1AuthTypeEnum = {
    CLIENT: 'Client'
} as const;

export type AuthenticateViaHarvestOAuth1AuthTypeEnum = typeof AuthenticateViaHarvestOAuth1AuthTypeEnum[keyof typeof AuthenticateViaHarvestOAuth1AuthTypeEnum];


