/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthenticateViaGoogleOAuth
 */
export interface AuthenticateViaGoogleOAuth {
    /**
     * 
     * @type {string}
     * @memberof AuthenticateViaGoogleOAuth
     */
    'auth_type': AuthenticateViaGoogleOAuthAuthTypeEnum;
    /**
     * Enter your Google application\'s Client ID. See <a href=\'https://developers.google.com/identity/protocols/oauth2\'>Google\'s documentation</a> for more information.
     * @type {string}
     * @memberof AuthenticateViaGoogleOAuth
     */
    'client_id': string;
    /**
     * Enter your Google application\'s Client Secret. See <a href=\'https://developers.google.com/identity/protocols/oauth2\'>Google\'s documentation</a> for more information.
     * @type {string}
     * @memberof AuthenticateViaGoogleOAuth
     */
    'client_secret': string;
    /**
     * Enter your Google application\'s refresh token. See <a href=\'https://developers.google.com/identity/protocols/oauth2\'>Google\'s documentation</a> for more information.
     * @type {string}
     * @memberof AuthenticateViaGoogleOAuth
     */
    'refresh_token': string;
}

export const AuthenticateViaGoogleOAuthAuthTypeEnum = {
    CLIENT: 'Client'
} as const;

export type AuthenticateViaGoogleOAuthAuthTypeEnum = typeof AuthenticateViaGoogleOAuthAuthTypeEnum[keyof typeof AuthenticateViaGoogleOAuthAuthTypeEnum];


