/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthenticateViaMicrosoftOAuth } from './authenticate-via-microsoft-oauth';
// May contain unused imports in some cases
// @ts-ignore
import type { ServiceKeyAuthentication } from './service-key-authentication';

/**
 * @type Authentication4
 * Credentials for connecting to the One Drive API
 * @export
 */
export type Authentication4 = AuthenticateViaMicrosoftOAuth | ServiceKeyAuthentication;


