/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthenticateViaRetentlyOAuth
 */
export interface AuthenticateViaRetentlyOAuth {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof AuthenticateViaRetentlyOAuth
     */
    'auth_type'?: AuthenticateViaRetentlyOAuthAuthTypeEnum;
    /**
     * The Client ID of your Retently developer application.
     * @type {string}
     * @memberof AuthenticateViaRetentlyOAuth
     */
    'client_id': string;
    /**
     * The Client Secret of your Retently developer application.
     * @type {string}
     * @memberof AuthenticateViaRetentlyOAuth
     */
    'client_secret': string;
    /**
     * Retently Refresh Token which can be used to fetch new Bearer Tokens when the current one expires.
     * @type {string}
     * @memberof AuthenticateViaRetentlyOAuth
     */
    'refresh_token': string;
}

export const AuthenticateViaRetentlyOAuthAuthTypeEnum = {
    CLIENT: 'Client'
} as const;

export type AuthenticateViaRetentlyOAuthAuthTypeEnum = typeof AuthenticateViaRetentlyOAuthAuthTypeEnum[keyof typeof AuthenticateViaRetentlyOAuthAuthTypeEnum];


