/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiKeyAuth } from './api-key-auth';
// May contain unused imports in some cases
// @ts-ignore
import type { NoAuth } from './no-auth';

/**
 * @type AuthenticationMethod8
 * Method to authenticate with the Qdrant Instance
 * @export
 */
export type AuthenticationMethod8 = ApiKeyAuth | NoAuth;


