/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthenticateViaPassword1 } from './authenticate-via-password1';
// May contain unused imports in some cases
// @ts-ignore
import type { AuthenticateViaPrivateKey } from './authenticate-via-private-key';

/**
 * @type Authentication13
 * Credentials for connecting to the SFTP Server
 * @export
 */
export type Authentication13 = AuthenticateViaPassword1 | AuthenticateViaPrivateKey;


