/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * OAuthCredentials class to hold authentication details for Microsoft OAuth authentication. This class uses pydantic for data validation and settings management.
 * @export
 * @interface AuthenticateViaMicrosoftOAuth2
 */
export interface AuthenticateViaMicrosoftOAuth2 {
    /**
     * 
     * @type {string}
     * @memberof AuthenticateViaMicrosoftOAuth2
     */
    'auth_type'?: AuthenticateViaMicrosoftOAuth2AuthTypeEnum;
    /**
     * Tenant ID of the Microsoft OneDrive user
     * @type {string}
     * @memberof AuthenticateViaMicrosoftOAuth2
     */
    'tenant_id': string;
    /**
     * Client ID of your Microsoft developer application
     * @type {string}
     * @memberof AuthenticateViaMicrosoftOAuth2
     */
    'client_id': string;
    /**
     * Client Secret of your Microsoft developer application
     * @type {string}
     * @memberof AuthenticateViaMicrosoftOAuth2
     */
    'client_secret': string;
    /**
     * Refresh Token of your Microsoft developer application
     * @type {string}
     * @memberof AuthenticateViaMicrosoftOAuth2
     */
    'refresh_token': string;
}

export const AuthenticateViaMicrosoftOAuth2AuthTypeEnum = {
    CLIENT: 'Client'
} as const;

export type AuthenticateViaMicrosoftOAuth2AuthTypeEnum = typeof AuthenticateViaMicrosoftOAuth2AuthTypeEnum[keyof typeof AuthenticateViaMicrosoftOAuth2AuthTypeEnum];


