/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProjectSecret1 } from './project-secret1';
// May contain unused imports in some cases
// @ts-ignore
import type { ServiceAccount1 } from './service-account1';

/**
 * @type Authentication1
 * Choose how to authenticate to Mixpanel
 * @export
 */
export type Authentication1 = ProjectSecret1 | ServiceAccount1;


