/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthenticateViaMicrosoft } from './authenticate-via-microsoft';
// May contain unused imports in some cases
// @ts-ignore
import type { AuthenticateViaMicrosoftOAuth20 } from './authenticate-via-microsoft-oauth20';

/**
 * @type AuthenticationMechanism6
 * Choose how to authenticate to Microsoft
 * @export
 */
export type AuthenticationMechanism6 = AuthenticateViaMicrosoft | AuthenticateViaMicrosoftOAuth20;


