/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OAuth } from './oauth';
// May contain unused imports in some cases
// @ts-ignore
import type { ServiceAccountKeyAuthentication } from './service-account-key-authentication';

/**
 * @type AuthenticationType
 * 
 * @export
 */
export type AuthenticationType = OAuth | ServiceAccountKeyAuthentication;


