/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CentralAPIRouter1 } from './central-apirouter1';
// May contain unused imports in some cases
// @ts-ignore
import type { SingleStoreAccessToken1 } from './single-store-access-token1';

/**
 * @type AuthorizationMethod17
 * 
 * @export
 */
export type AuthorizationMethod17 = CentralAPIRouter1 | SingleStoreAccessToken1;


