/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PasswordAuthentication2 } from './password-authentication2';
// May contain unused imports in some cases
// @ts-ignore
import type { SSHKeyAuthentication2 } from './sshkey-authentication2';

/**
 * @type Authentication30
 * The server authentication method
 * @export
 */
export type Authentication30 = PasswordAuthentication2 | SSHKeyAuthentication2;


