/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthenticateViaOauth2
 */
export interface AuthenticateViaOauth2 {
    /**
     * 
     * @type {string}
     * @memberof AuthenticateViaOauth2
     */
    'auth_type': AuthenticateViaOauth2AuthTypeEnum;
    /**
     * Tenant ID of the Microsoft Azure Application user
     * @type {string}
     * @memberof AuthenticateViaOauth2
     */
    'tenant_id': string;
    /**
     * Client ID of your Microsoft developer application
     * @type {string}
     * @memberof AuthenticateViaOauth2
     */
    'client_id': string;
    /**
     * Client Secret of your Microsoft developer application
     * @type {string}
     * @memberof AuthenticateViaOauth2
     */
    'client_secret': string;
    /**
     * Refresh Token of your Microsoft developer application
     * @type {string}
     * @memberof AuthenticateViaOauth2
     */
    'refresh_token': string;
}

export const AuthenticateViaOauth2AuthTypeEnum = {
    OAUTH2: 'oauth2'
} as const;

export type AuthenticateViaOauth2AuthTypeEnum = typeof AuthenticateViaOauth2AuthTypeEnum[keyof typeof AuthenticateViaOauth2AuthTypeEnum];


