/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthenticateViaAPIKey1
 */
export interface AuthenticateViaAPIKey1 {
    /**
     * API Key for making authenticated requests. More instruction on how to find this value in our <a href=\"https://docs.airbyte.com/integrations/sources/salesloft#setup-guide\">docs</a>
     * @type {string}
     * @memberof AuthenticateViaAPIKey1
     */
    'api_key': string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticateViaAPIKey1
     */
    'auth_type': AuthenticateViaAPIKey1AuthTypeEnum;
}

export const AuthenticateViaAPIKey1AuthTypeEnum = {
    API_KEY: 'api_key'
} as const;

export type AuthenticateViaAPIKey1AuthTypeEnum = typeof AuthenticateViaAPIKey1AuthTypeEnum[keyof typeof AuthenticateViaAPIKey1AuthTypeEnum];


