/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthenticateViaAsanaOauth
 */
export interface AuthenticateViaAsanaOauth {
    /**
     * OAuth Credentials
     * @type {string}
     * @memberof AuthenticateViaAsanaOauth
     */
    'option_title'?: AuthenticateViaAsanaOauthOptionTitleEnum;
    /**
     * 
     * @type {string}
     * @memberof AuthenticateViaAsanaOauth
     */
    'client_id': string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticateViaAsanaOauth
     */
    'client_secret': string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticateViaAsanaOauth
     */
    'refresh_token': string;
}

export const AuthenticateViaAsanaOauthOptionTitleEnum = {
    O_AUTH_CREDENTIALS: 'OAuth Credentials'
} as const;

export type AuthenticateViaAsanaOauthOptionTitleEnum = typeof AuthenticateViaAsanaOauthOptionTitleEnum[keyof typeof AuthenticateViaAsanaOauthOptionTitleEnum];


