/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { APIAccessToken1 } from './apiaccess-token1';
// May contain unused imports in some cases
// @ts-ignore
import type { OAuth2013 } from './oauth2013';

/**
 * @type AuthorizationMethod9
 * @export
 */
export type AuthorizationMethod9 = APIAccessToken1 | OAuth2013;


