/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AvroFormat
 */
export interface AvroFormat {
    /**
     * 
     * @type {string}
     * @memberof AvroFormat
     */
    'filetype': AvroFormatFiletypeEnum;
    /**
     * Whether to convert double fields to strings. This is recommended if you have decimal numbers with a high degree of precision because there can be a loss precision when handling floating point numbers.
     * @type {boolean}
     * @memberof AvroFormat
     */
    'double_as_string'?: boolean;
}

export const AvroFormatFiletypeEnum = {
    AVRO: 'avro'
} as const;

export type AvroFormatFiletypeEnum = typeof AvroFormatFiletypeEnum[keyof typeof AvroFormatFiletypeEnum];


