/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompressionCodec1 } from './compression-codec1';

/**
 * 
 * @export
 * @interface AvroApacheAvro1
 */
export interface AvroApacheAvro1 {
    /**
     * 
     * @type {string}
     * @memberof AvroApacheAvro1
     */
    'format_type': AvroApacheAvro1FormatTypeEnum;
    /**
     * 
     * @type {CompressionCodec1}
     * @memberof AvroApacheAvro1
     */
    'compression_codec': CompressionCodec1;
}

export const AvroApacheAvro1FormatTypeEnum = {
    AVRO: 'Avro'
} as const;

export type AvroApacheAvro1FormatTypeEnum = typeof AvroApacheAvro1FormatTypeEnum[keyof typeof AvroApacheAvro1FormatTypeEnum];


