/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * <i>(recommended)</i> Uploads data to S3 and then uses a COPY to insert the data into Redshift. COPY is recommended for production workloads for better speed and scalability. See <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/creating-bucket.html\">AWS docs</a> for more details.
 * @export
 * @interface AWSS3Staging1
 */
export interface AWSS3Staging1 {
    /**
     * 
     * @type {string}
     * @memberof AWSS3Staging1
     */
    'method': AWSS3Staging1MethodEnum;
    /**
     * The name of the staging S3 bucket.
     * @type {string}
     * @memberof AWSS3Staging1
     */
    's3_bucket_name': string;
    /**
     * The directory under the S3 bucket where data will be written. If not provided, then defaults to the root directory. See <a href=\"https://docs.aws.amazon.com/prescriptive-guidance/latest/defining-bucket-names-data-lakes/faq.html#:~:text=be%20globally%20unique.-,For%20S3%20bucket%20paths,-%2C%20you%20can%20use\">path\'s name recommendations</a> for more details.
     * @type {string}
     * @memberof AWSS3Staging1
     */
    's3_bucket_path'?: string;
    /**
     * The region of the S3 staging bucket.
     * @type {string}
     * @memberof AWSS3Staging1
     */
    's3_bucket_region': AWSS3Staging1S3BucketRegionEnum;
    /**
     * This ID grants access to the above S3 staging bucket. Airbyte requires Read and Write permissions to the given bucket. See <a href=\"https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys\">AWS docs</a> on how to generate an access key ID and secret access key.
     * @type {string}
     * @memberof AWSS3Staging1
     */
    'access_key_id': string;
    /**
     * The corresponding secret to the above access key id. See <a href=\"https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys\">AWS docs</a> on how to generate an access key ID and secret access key.
     * @type {string}
     * @memberof AWSS3Staging1
     */
    'secret_access_key': string;
    /**
     * The pattern allows you to set the file-name format for the S3 staging file(s)
     * @type {string}
     * @memberof AWSS3Staging1
     */
    'file_name_pattern'?: string;
    /**
     * Whether to delete the staging files from S3 after completing the sync. See <a href=\"https://docs.airbyte.com/integrations/destinations/redshift/#:~:text=the%20root%20directory.-,Purge%20Staging%20Data,-Whether%20to%20delete\"> docs</a> for details.
     * @type {boolean}
     * @memberof AWSS3Staging1
     */
    'purge_staging_data'?: boolean;
}

export const AWSS3Staging1MethodEnum = {
    S3_STAGING: 'S3 Staging'
} as const;

export type AWSS3Staging1MethodEnum = typeof AWSS3Staging1MethodEnum[keyof typeof AWSS3Staging1MethodEnum];
export const AWSS3Staging1S3BucketRegionEnum = {
    EMPTY: '',
    AF_SOUTH_1: 'af-south-1',
    AP_EAST_1: 'ap-east-1',
    AP_NORTHEAST_1: 'ap-northeast-1',
    AP_NORTHEAST_2: 'ap-northeast-2',
    AP_NORTHEAST_3: 'ap-northeast-3',
    AP_SOUTH_1: 'ap-south-1',
    AP_SOUTH_2: 'ap-south-2',
    AP_SOUTHEAST_1: 'ap-southeast-1',
    AP_SOUTHEAST_2: 'ap-southeast-2',
    AP_SOUTHEAST_3: 'ap-southeast-3',
    AP_SOUTHEAST_4: 'ap-southeast-4',
    CA_CENTRAL_1: 'ca-central-1',
    CA_WEST_1: 'ca-west-1',
    CN_NORTH_1: 'cn-north-1',
    CN_NORTHWEST_1: 'cn-northwest-1',
    EU_CENTRAL_1: 'eu-central-1',
    EU_CENTRAL_2: 'eu-central-2',
    EU_NORTH_1: 'eu-north-1',
    EU_SOUTH_1: 'eu-south-1',
    EU_SOUTH_2: 'eu-south-2',
    EU_WEST_1: 'eu-west-1',
    EU_WEST_2: 'eu-west-2',
    EU_WEST_3: 'eu-west-3',
    IL_CENTRAL_1: 'il-central-1',
    ME_CENTRAL_1: 'me-central-1',
    ME_SOUTH_1: 'me-south-1',
    SA_EAST_1: 'sa-east-1',
    US_EAST_1: 'us-east-1',
    US_EAST_2: 'us-east-2',
    US_GOV_EAST_1: 'us-gov-east-1',
    US_GOV_WEST_1: 'us-gov-west-1',
    US_WEST_1: 'us-west-1',
    US_WEST_2: 'us-west-2'
} as const;

export type AWSS3Staging1S3BucketRegionEnum = typeof AWSS3Staging1S3BucketRegionEnum[keyof typeof AWSS3Staging1S3BucketRegionEnum];


