/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AzBlobAzureBlobStorage1
 */
export interface AzBlobAzureBlobStorage1 {
    /**
     * 
     * @type {string}
     * @memberof AzBlobAzureBlobStorage1
     */
    'storage': AzBlobAzureBlobStorage1StorageEnum;
    /**
     * The globally unique name of the storage account that the desired blob sits within. See <a href=\"https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview\" target=\"_blank\">here</a> for more details.
     * @type {string}
     * @memberof AzBlobAzureBlobStorage1
     */
    'storage_account': string;
    /**
     * To access Azure Blob Storage, this connector would need credentials with the proper permissions. One option is a SAS (Shared Access Signature) token. If accessing publicly available data, this field is not necessary.
     * @type {string}
     * @memberof AzBlobAzureBlobStorage1
     */
    'sas_token'?: string;
    /**
     * To access Azure Blob Storage, this connector would need credentials with the proper permissions. One option is a storage account shared key (aka account key or access key). If accessing publicly available data, this field is not necessary.
     * @type {string}
     * @memberof AzBlobAzureBlobStorage1
     */
    'shared_key'?: string;
}

export const AzBlobAzureBlobStorage1StorageEnum = {
    AZ_BLOB: 'AzBlob'
} as const;

export type AzBlobAzureBlobStorage1StorageEnum = typeof AzBlobAzureBlobStorage1StorageEnum[keyof typeof AzBlobAzureBlobStorage1StorageEnum];


