/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AzureBlobStorageCredentials
 */
export interface AzureBlobStorageCredentials {
    /**
     * Client ID of your Microsoft developer application
     * @type {string}
     * @memberof AzureBlobStorageCredentials
     */
    'client_id'?: string;
    /**
     * Client Secret of your Microsoft developer application
     * @type {string}
     * @memberof AzureBlobStorageCredentials
     */
    'client_secret'?: string;
}

