/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EUBasedAccount } from './eubased-account';
// May contain unused imports in some cases
// @ts-ignore
import type { GlobalAccount } from './global-account';

/**
 * @type BaseURL
 * Is your account location is EU based? If yes, the base url to retrieve data will be different.
 * @export
 */
export type BaseURL = EUBasedAccount | GlobalAccount;


