/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Split the text by suitable delimiters based on the programming language. This is useful for splitting code into chunks.
 * @export
 * @interface ByProgrammingLanguage
 */
export interface ByProgrammingLanguage {
    /**
     * 
     * @type {string}
     * @memberof ByProgrammingLanguage
     */
    'mode': ByProgrammingLanguageModeEnum;
    /**
     * Split code in suitable places based on the programming language
     * @type {string}
     * @memberof ByProgrammingLanguage
     */
    'language': ByProgrammingLanguageLanguageEnum;
}

export const ByProgrammingLanguageModeEnum = {
    CODE: 'code'
} as const;

export type ByProgrammingLanguageModeEnum = typeof ByProgrammingLanguageModeEnum[keyof typeof ByProgrammingLanguageModeEnum];
export const ByProgrammingLanguageLanguageEnum = {
    CPP: 'cpp',
    GO: 'go',
    JAVA: 'java',
    JS: 'js',
    PHP: 'php',
    PROTO: 'proto',
    PYTHON: 'python',
    RST: 'rst',
    RUBY: 'ruby',
    RUST: 'rust',
    SCALA: 'scala',
    SWIFT: 'swift',
    MARKDOWN: 'markdown',
    LATEX: 'latex',
    HTML: 'html',
    SOL: 'sol'
} as const;

export type ByProgrammingLanguageLanguageEnum = typeof ByProgrammingLanguageLanguageEnum[keyof typeof ByProgrammingLanguageLanguageEnum];


