/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Bzip2 } from './bzip2';
// May contain unused imports in some cases
// @ts-ignore
import type { Deflate } from './deflate';
// May contain unused imports in some cases
// @ts-ignore
import type { NoCompression } from './no-compression';
// May contain unused imports in some cases
// @ts-ignore
import type { Snappy } from './snappy';
// May contain unused imports in some cases
// @ts-ignore
import type { Xz } from './xz';
// May contain unused imports in some cases
// @ts-ignore
import type { Zstandard } from './zstandard';

/**
 * @type CompressionCodec
 * The compression algorithm used to compress data. Default to no compression.
 * @export
 */
export type CompressionCodec = Bzip2 | Deflate | NoCompression | Snappy | Xz | Zstandard;


