/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Bzip2 } from './bzip2';
// May contain unused imports in some cases
// @ts-ignore
import type { Deflate1 } from './deflate1';
// May contain unused imports in some cases
// @ts-ignore
import type { NoCompression } from './no-compression';
// May contain unused imports in some cases
// @ts-ignore
import type { Snappy } from './snappy';
// May contain unused imports in some cases
// @ts-ignore
import type { Xz1 } from './xz1';
// May contain unused imports in some cases
// @ts-ignore
import type { Zstandard1 } from './zstandard1';

/**
 * @type CompressionCodec1
 * The compression algorithm used to compress data. Default to no compression.
 * @export
 */
export type CompressionCodec1 = Bzip2 | Deflate1 | NoCompression | Snappy | Xz1 | Zstandard1;


