/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const ConnectionSyncModeEnum = {
    FULL_REFRESH_OVERWRITE: 'full_refresh_overwrite',
    FULL_REFRESH_APPEND: 'full_refresh_append',
    INCREMENTAL_APPEND: 'incremental_append',
    INCREMENTAL_DEDUPED_HISTORY: 'incremental_deduped_history'
} as const;

export type ConnectionSyncModeEnum = typeof ConnectionSyncModeEnum[keyof typeof ConnectionSyncModeEnum];



