/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthenticateViaGoogleOauth } from './authenticate-via-google-oauth';
// May contain unused imports in some cases
// @ts-ignore
import type { ServiceAccountKeyAuthentication4 } from './service-account-key-authentication4';

/**
 * @type Credentials2
 * Credentials for the service
 * @export
 */
export type Credentials2 = AuthenticateViaGoogleOauth | ServiceAccountKeyAuthentication4;


