/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Compression } from './compression';

/**
 * 
 * @export
 * @interface CSVCommaSeparatedValues
 */
export interface CSVCommaSeparatedValues {
    /**
     * 
     * @type {string}
     * @memberof CSVCommaSeparatedValues
     */
    'format_type': CSVCommaSeparatedValuesFormatTypeEnum;
    /**
     * Whether the input JSON data should be normalized (flattened) in the output CSV. Please refer to docs for details.
     * @type {string}
     * @memberof CSVCommaSeparatedValues
     */
    'flattening'?: CSVCommaSeparatedValuesFlatteningEnum;
    /**
     * 
     * @type {Compression}
     * @memberof CSVCommaSeparatedValues
     */
    'compression'?: Compression;
}

export const CSVCommaSeparatedValuesFormatTypeEnum = {
    CSV: 'CSV'
} as const;

export type CSVCommaSeparatedValuesFormatTypeEnum = typeof CSVCommaSeparatedValuesFormatTypeEnum[keyof typeof CSVCommaSeparatedValuesFormatTypeEnum];
export const CSVCommaSeparatedValuesFlatteningEnum = {
    NO_FLATTENING: 'No flattening',
    ROOT_LEVEL_FLATTENING: 'Root level flattening'
} as const;

export type CSVCommaSeparatedValuesFlatteningEnum = typeof CSVCommaSeparatedValuesFlatteningEnum[keyof typeof CSVCommaSeparatedValuesFlatteningEnum];


