/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Autogenerated } from './autogenerated';
// May contain unused imports in some cases
// @ts-ignore
import type { FromCSV } from './from-csv';
// May contain unused imports in some cases
// @ts-ignore
import type { UserProvided } from './user-provided';

/**
 * @type CSVHeaderDefinition
 * How headers will be defined. `User Provided` assumes the CSV does not have a header row and uses the headers provided and `Autogenerated` assumes the CSV does not have a header row and the CDK will generate headers using for `f{i}` where `i` is the index starting from 0. Else, the default behavior is to use the header from the CSV file. If a user wants to autogenerate or provide column names for a CSV having headers, they can skip rows.
 * @export
 */
export type CSVHeaderDefinition = Autogenerated | FromCSV | UserProvided;


