/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Deflate1
 */
export interface Deflate1 {
    /**
     * 
     * @type {string}
     * @memberof Deflate1
     */
    'codec': Deflate1CodecEnum;
    /**
     * 0: no compression & fastest, 9: best compression & slowest.
     * @type {number}
     * @memberof Deflate1
     */
    'compression_level': number;
}

export const Deflate1CodecEnum = {
    DEFLATE: 'Deflate'
} as const;

export type Deflate1CodecEnum = typeof Deflate1CodecEnum[keyof typeof Deflate1CodecEnum];


