/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Disabled } from './disabled';
// May contain unused imports in some cases
// @ts-ignore
import type { Enabled } from './enabled';

/**
 * @type DeletionMode
 * <b>This only applies to incremental syncs.</b> <br> Enabling deletion mode informs your destination of deleted documents.<br> Disabled - Leave this feature disabled, and ignore deleted documents.<br> Enabled - Enables this feature. When a document is deleted, the connector exports a record with a \"deleted at\" column containing the time that the document was deleted.
 * @export
 */
export type DeletionMode = Disabled | Enabled;


