/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OutputFormat2 } from './output-format2';

/**
 * 
 * @export
 * @interface DestinationS3Update
 */
export interface DestinationS3Update {
    /**
     * The access key ID to access the S3 bucket. Airbyte requires Read and Write permissions to the given bucket. Read more <a href=\"https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys\">here</a>.
     * @type {string}
     * @memberof DestinationS3Update
     */
    'access_key_id'?: string;
    /**
     * The corresponding secret to the access key ID. Read more <a href=\"https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys\">here</a>
     * @type {string}
     * @memberof DestinationS3Update
     */
    'secret_access_key'?: string;
    /**
     * The Role ARN
     * @type {string}
     * @memberof DestinationS3Update
     */
    'role_arn'?: string;
    /**
     * The name of the S3 bucket. Read more <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/create-bucket-overview.html\">here</a>.
     * @type {string}
     * @memberof DestinationS3Update
     */
    's3_bucket_name': string;
    /**
     * Directory under the S3 bucket where data will be written. Read more <a href=\"https://docs.airbyte.com/integrations/destinations/s3#:~:text=to%20format%20the-,bucket%20path,-%3A\">here</a>
     * @type {string}
     * @memberof DestinationS3Update
     */
    's3_bucket_path': string;
    /**
     * The region of the S3 bucket. See <a href=\"https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regions\">here</a> for all region codes.
     * @type {string}
     * @memberof DestinationS3Update
     */
    's3_bucket_region': DestinationS3UpdateS3BucketRegionEnum;
    /**
     * 
     * @type {OutputFormat2}
     * @memberof DestinationS3Update
     */
    'format': OutputFormat2;
    /**
     * Your S3 endpoint url. Read more <a href=\"https://docs.aws.amazon.com/general/latest/gr/s3.html#:~:text=Service%20endpoints-,Amazon%20S3%20endpoints,-When%20you%20use\">here</a>
     * @type {string}
     * @memberof DestinationS3Update
     */
    's3_endpoint'?: string;
    /**
     * Format string on how data will be organized inside the S3 bucket directory. Read more <a href=\"https://docs.airbyte.com/integrations/destinations/s3#:~:text=The%20full%20path%20of%20the%20output%20data%20with%20the%20default%20S3%20path%20format\">here</a>
     * @type {string}
     * @memberof DestinationS3Update
     */
    's3_path_format'?: string;
    /**
     * The pattern allows you to set the file-name format for the S3 staging file(s)
     * @type {string}
     * @memberof DestinationS3Update
     */
    'file_name_pattern'?: string;
}

export const DestinationS3UpdateS3BucketRegionEnum = {
    EMPTY: '',
    AF_SOUTH_1: 'af-south-1',
    AP_EAST_1: 'ap-east-1',
    AP_NORTHEAST_1: 'ap-northeast-1',
    AP_NORTHEAST_2: 'ap-northeast-2',
    AP_NORTHEAST_3: 'ap-northeast-3',
    AP_SOUTH_1: 'ap-south-1',
    AP_SOUTH_2: 'ap-south-2',
    AP_SOUTHEAST_1: 'ap-southeast-1',
    AP_SOUTHEAST_2: 'ap-southeast-2',
    AP_SOUTHEAST_3: 'ap-southeast-3',
    AP_SOUTHEAST_4: 'ap-southeast-4',
    CA_CENTRAL_1: 'ca-central-1',
    CA_WEST_1: 'ca-west-1',
    CN_NORTH_1: 'cn-north-1',
    CN_NORTHWEST_1: 'cn-northwest-1',
    EU_CENTRAL_1: 'eu-central-1',
    EU_CENTRAL_2: 'eu-central-2',
    EU_NORTH_1: 'eu-north-1',
    EU_SOUTH_1: 'eu-south-1',
    EU_SOUTH_2: 'eu-south-2',
    EU_WEST_1: 'eu-west-1',
    EU_WEST_2: 'eu-west-2',
    EU_WEST_3: 'eu-west-3',
    IL_CENTRAL_1: 'il-central-1',
    ME_CENTRAL_1: 'me-central-1',
    ME_SOUTH_1: 'me-south-1',
    SA_EAST_1: 'sa-east-1',
    US_EAST_1: 'us-east-1',
    US_EAST_2: 'us-east-2',
    US_GOV_EAST_1: 'us-gov-east-1',
    US_GOV_WEST_1: 'us-gov-west-1',
    US_WEST_1: 'us-west-1',
    US_WEST_2: 'us-west-2'
} as const;

export type DestinationS3UpdateS3BucketRegionEnum = typeof DestinationS3UpdateS3BucketRegionEnum[keyof typeof DestinationS3UpdateS3BucketRegionEnum];


