/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LoadingMethod } from './loading-method';

/**
 * 
 * @export
 * @interface DestinationFirebolt
 */
export interface DestinationFirebolt {
    /**
     * Firebolt service account ID.
     * @type {string}
     * @memberof DestinationFirebolt
     */
    'client_id': string;
    /**
     * Firebolt secret, corresponding to the service account ID.
     * @type {string}
     * @memberof DestinationFirebolt
     */
    'client_secret': string;
    /**
     * Firebolt account to login.
     * @type {string}
     * @memberof DestinationFirebolt
     */
    'account': string;
    /**
     * The host name of your Firebolt database.
     * @type {string}
     * @memberof DestinationFirebolt
     */
    'host'?: string;
    /**
     * The database to connect to.
     * @type {string}
     * @memberof DestinationFirebolt
     */
    'database': string;
    /**
     * Engine name to connect to.
     * @type {string}
     * @memberof DestinationFirebolt
     */
    'engine': string;
    /**
     * 
     * @type {LoadingMethod}
     * @memberof DestinationFirebolt
     */
    'loading_method'?: LoadingMethod;
    /**
     * 
     * @type {string}
     * @memberof DestinationFirebolt
     */
    'destinationType': DestinationFireboltDestinationTypeEnum;
}

export const DestinationFireboltDestinationTypeEnum = {
    FIREBOLT: 'firebolt'
} as const;

export type DestinationFireboltDestinationTypeEnum = typeof DestinationFireboltDestinationTypeEnum[keyof typeof DestinationFireboltDestinationTypeEnum];


