/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DestinationSftpJsonUpdate
 */
export interface DestinationSftpJsonUpdate {
    /**
     * Hostname of the SFTP server.
     * @type {string}
     * @memberof DestinationSftpJsonUpdate
     */
    'host': string;
    /**
     * Port of the SFTP server.
     * @type {number}
     * @memberof DestinationSftpJsonUpdate
     */
    'port'?: number;
    /**
     * Username to use to access the SFTP server.
     * @type {string}
     * @memberof DestinationSftpJsonUpdate
     */
    'username': string;
    /**
     * Password associated with the username.
     * @type {string}
     * @memberof DestinationSftpJsonUpdate
     */
    'password': string;
    /**
     * Path to the directory where json files will be written.
     * @type {string}
     * @memberof DestinationSftpJsonUpdate
     */
    'destination_path': string;
}

