/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SSLModes2 } from './sslmodes2';

/**
 * 
 * @export
 * @interface DestinationTeradata
 */
export interface DestinationTeradata {
    /**
     * Hostname of the database.
     * @type {string}
     * @memberof DestinationTeradata
     */
    'host': string;
    /**
     * Username to use to access the database.
     * @type {string}
     * @memberof DestinationTeradata
     */
    'username': string;
    /**
     * Password associated with the username.
     * @type {string}
     * @memberof DestinationTeradata
     */
    'password'?: string;
    /**
     * The default schema tables are written to if the source does not specify a namespace. The usual value for this field is \"public\".
     * @type {string}
     * @memberof DestinationTeradata
     */
    'schema'?: string;
    /**
     * Encrypt data using SSL. When activating SSL, please select one of the connection modes.
     * @type {boolean}
     * @memberof DestinationTeradata
     */
    'ssl'?: boolean;
    /**
     * 
     * @type {SSLModes2}
     * @memberof DestinationTeradata
     */
    'ssl_mode'?: SSLModes2;
    /**
     * Additional properties to pass to the JDBC URL string when connecting to the database formatted as \'key=value\' pairs separated by the symbol \'&\'. (example: key1=value1&key2=value2&key3=value3).
     * @type {string}
     * @memberof DestinationTeradata
     */
    'jdbc_url_params'?: string;
    /**
     * 
     * @type {string}
     * @memberof DestinationTeradata
     */
    'destinationType': DestinationTeradataDestinationTypeEnum;
}

export const DestinationTeradataDestinationTypeEnum = {
    TERADATA: 'teradata'
} as const;

export type DestinationTeradataDestinationTypeEnum = typeof DestinationTeradataDestinationTypeEnum[keyof typeof DestinationTeradataDestinationTypeEnum];


