/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DestinationDuckdbUpdate
 */
export interface DestinationDuckdbUpdate {
    /**
     * API key to use for authentication to a MotherDuck database.
     * @type {string}
     * @memberof DestinationDuckdbUpdate
     */
    'motherduck_api_key'?: string;
    /**
     * Path to the .duckdb file, or the text \'md:\' to connect to MotherDuck. The file will be placed inside that local mount. For more information check out our <a href=\"https://docs.airbyte.io/integrations/destinations/duckdb\">docs</a>
     * @type {string}
     * @memberof DestinationDuckdbUpdate
     */
    'destination_path': string;
    /**
     * Database schema name, default for duckdb is \'main\'.
     * @type {string}
     * @memberof DestinationDuckdbUpdate
     */
    'schema'?: string;
}

