/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthorizationMethod20 } from './authorization-method20';

/**
 * 
 * @export
 * @interface DestinationSnowflake
 */
export interface DestinationSnowflake {
    /**
     * Enter your Snowflake account\'s <a href=\"https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#using-an-account-locator-as-an-identifier\">locator</a> (in the format <account_locator>.<region>.<cloud>.snowflakecomputing.com)
     * @type {string}
     * @memberof DestinationSnowflake
     */
    'host': string;
    /**
     * Enter the <a href=\"https://docs.snowflake.com/en/user-guide/security-access-control-overview.html#roles\">role</a> that you want to use to access Snowflake
     * @type {string}
     * @memberof DestinationSnowflake
     */
    'role': string;
    /**
     * Enter the name of the <a href=\"https://docs.snowflake.com/en/user-guide/warehouses-overview.html#overview-of-warehouses\">warehouse</a> that you want to use as a compute cluster
     * @type {string}
     * @memberof DestinationSnowflake
     */
    'warehouse': string;
    /**
     * Enter the name of the <a href=\"https://docs.snowflake.com/en/sql-reference/ddl-database.html#database-schema-share-ddl\">database</a> you want to sync data into
     * @type {string}
     * @memberof DestinationSnowflake
     */
    'database': string;
    /**
     * Enter the name of the default <a href=\"https://docs.snowflake.com/en/sql-reference/ddl-database.html#database-schema-share-ddl\">schema</a>
     * @type {string}
     * @memberof DestinationSnowflake
     */
    'schema': string;
    /**
     * Enter the name of the user you want to use to access the database
     * @type {string}
     * @memberof DestinationSnowflake
     */
    'username': string;
    /**
     * 
     * @type {AuthorizationMethod20}
     * @memberof DestinationSnowflake
     */
    'credentials'?: AuthorizationMethod20;
    /**
     * Enter the additional properties to pass to the JDBC URL string when connecting to the database (formatted as key=value pairs separated by the symbol &). Example: key1=value1&key2=value2&key3=value3
     * @type {string}
     * @memberof DestinationSnowflake
     */
    'jdbc_url_params'?: string;
    /**
     * The schema to write raw tables into (default: airbyte_internal)
     * @type {string}
     * @memberof DestinationSnowflake
     */
    'raw_data_schema'?: string;
    /**
     * Disable Writing Final Tables. WARNING! The data format in _airbyte_data is likely stable but there are no guarantees that other metadata columns will remain the same in future versions
     * @type {boolean}
     * @memberof DestinationSnowflake
     */
    'disable_type_dedupe'?: boolean;
    /**
     * The number of days of Snowflake Time Travel to enable on the tables. See <a href=\"https://docs.snowflake.com/en/user-guide/data-time-travel#data-retention-period\">Snowflake\'s documentation</a> for more information. Setting a nonzero value will incur increased storage costs in your Snowflake instance.
     * @type {number}
     * @memberof DestinationSnowflake
     */
    'retention_period_days'?: number;
    /**
     * Use MERGE for de-duplication of final tables. This option no effect if Final tables are disabled or Sync mode is not DEDUPE
     * @type {boolean}
     * @memberof DestinationSnowflake
     */
    'use_merge_for_upsert'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DestinationSnowflake
     */
    'destinationType': DestinationSnowflakeDestinationTypeEnum;
}

export const DestinationSnowflakeDestinationTypeEnum = {
    SNOWFLAKE: 'snowflake'
} as const;

export type DestinationSnowflakeDestinationTypeEnum = typeof DestinationSnowflakeDestinationTypeEnum[keyof typeof DestinationSnowflakeDestinationTypeEnum];


