/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DestinationConvex
 */
export interface DestinationConvex {
    /**
     * URL of the Convex deployment that is the destination
     * @type {string}
     * @memberof DestinationConvex
     */
    'deployment_url': string;
    /**
     * API access key used to send data to a Convex deployment.
     * @type {string}
     * @memberof DestinationConvex
     */
    'access_key': string;
    /**
     * 
     * @type {string}
     * @memberof DestinationConvex
     */
    'destinationType': DestinationConvexDestinationTypeEnum;
}

export const DestinationConvexDestinationTypeEnum = {
    CONVEX: 'convex'
} as const;

export type DestinationConvexDestinationTypeEnum = typeof DestinationConvexDestinationTypeEnum[keyof typeof DestinationConvexDestinationTypeEnum];


