/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AzureOpenAI } from './azure-open-ai';
// May contain unused imports in some cases
// @ts-ignore
import type { Cohere } from './cohere';
// May contain unused imports in some cases
// @ts-ignore
import type { Fake } from './fake';
// May contain unused imports in some cases
// @ts-ignore
import type { FromField } from './from-field';
// May contain unused imports in some cases
// @ts-ignore
import type { NoExternalEmbedding } from './no-external-embedding';
// May contain unused imports in some cases
// @ts-ignore
import type { OpenAI } from './open-ai';
// May contain unused imports in some cases
// @ts-ignore
import type { OpenAICompatible } from './open-aicompatible';

/**
 * @type Embedding
 * Embedding configuration
 * @export
 */
export type Embedding = AzureOpenAI | Cohere | Fake | FromField | NoExternalEmbedding | OpenAI | OpenAICompatible;


