/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Enabled
 */
export interface Enabled {
    /**
     * 
     * @type {string}
     * @memberof Enabled
     */
    'deletion_mode': EnabledDeletionModeEnum;
    /**
     * Name of the \"deleted at\" column.
     * @type {string}
     * @memberof Enabled
     */
    'column': string;
}

export const EnabledDeletionModeEnum = {
    DELETED_FIELD: 'deleted_field'
} as const;

export type EnabledDeletionModeEnum = typeof EnabledDeletionModeEnum[keyof typeof EnabledDeletionModeEnum];


