/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CohortReportSettings } from './cohort-report-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { Cohorts } from './cohorts';
// May contain unused imports in some cases
// @ts-ignore
import type { Enabled1CohortsRange } from './enabled1-cohorts-range';

/**
 * 
 * @export
 * @interface Enabled1
 */
export interface Enabled1 {
    /**
     * 
     * @type {string}
     * @memberof Enabled1
     */
    'enabled'?: Enabled1EnabledEnum;
    /**
     * 
     * @type {Array<Cohorts>}
     * @memberof Enabled1
     */
    'cohorts'?: Array<Cohorts>;
    /**
     * 
     * @type {Enabled1CohortsRange}
     * @memberof Enabled1
     */
    'cohortsRange'?: Enabled1CohortsRange;
    /**
     * 
     * @type {CohortReportSettings}
     * @memberof Enabled1
     */
    'cohortReportSettings'?: CohortReportSettings;
}

export const Enabled1EnabledEnum = {
    TRUE: 'true'
} as const;

export type Enabled1EnabledEnum = typeof Enabled1EnabledEnum[keyof typeof Enabled1EnabledEnum];


