/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NativeNetworkEncryptionNNE } from './native-network-encryption-nne';
// May contain unused imports in some cases
// @ts-ignore
import type { TLSEncryptedVerifyCertificate } from './tlsencrypted-verify-certificate';
// May contain unused imports in some cases
// @ts-ignore
import type { Unencrypted } from './unencrypted';

/**
 * @type Encryption
 * The encryption method with is used when communicating with the database.
 * @export
 */
export type Encryption = NativeNetworkEncryptionNNE | TLSEncryptedVerifyCertificate | Unencrypted;


