/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Log first N entries per stream.
 * @export
 * @interface FirstNEntries
 */
export interface FirstNEntries {
    /**
     * 
     * @type {string}
     * @memberof FirstNEntries
     */
    'logging_type': FirstNEntriesLoggingTypeEnum;
    /**
     * Number of entries to log. This destination is for testing only. So it won\'t make sense to log infinitely. The maximum is 1,000 entries.
     * @type {number}
     * @memberof FirstNEntries
     */
    'max_entry_count': number;
}

export const FirstNEntriesLoggingTypeEnum = {
    FIRST_N: 'FirstN'
} as const;

export type FirstNEntriesLoggingTypeEnum = typeof FirstNEntriesLoggingTypeEnum[keyof typeof FirstNEntriesLoggingTypeEnum];


