/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Use a field in the record as the embedding. This is useful if you already have an embedding for your data and want to store it in the vector store.
 * @export
 * @interface FromField
 */
export interface FromField {
    /**
     * 
     * @type {string}
     * @memberof FromField
     */
    'mode': FromFieldModeEnum;
    /**
     * Name of the field in the record that contains the embedding
     * @type {string}
     * @memberof FromField
     */
    'field_name': string;
    /**
     * The number of dimensions the embedding model is generating
     * @type {number}
     * @memberof FromField
     */
    'dimensions': number;
}

export const FromFieldModeEnum = {
    FROM_FIELD: 'from_field'
} as const;

export type FromFieldModeEnum = typeof FromFieldModeEnum[keyof typeof FromFieldModeEnum];


