/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GitlabCredentials } from './gitlab-credentials';

/**
 * 
 * @export
 * @interface Gitlab
 */
export interface Gitlab {
    /**
     * 
     * @type {GitlabCredentials}
     * @memberof Gitlab
     */
    'credentials'?: GitlabCredentials;
}

