/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The GlueCatalog connects to a AWS Glue Catalog
 * @export
 * @interface GlueCatalog
 */
export interface GlueCatalog {
    /**
     * 
     * @type {string}
     * @memberof GlueCatalog
     */
    'catalog_type': GlueCatalogCatalogTypeEnum;
    /**
     * The default schema tables are written to if the source does not specify a namespace. The usual value for this field is \"public\".
     * @type {string}
     * @memberof GlueCatalog
     */
    'database'?: string;
}

export const GlueCatalogCatalogTypeEnum = {
    GLUE: 'Glue'
} as const;

export type GlueCatalogCatalogTypeEnum = typeof GlueCatalogCatalogTypeEnum[keyof typeof GlueCatalogCatalogTypeEnum];


