/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Header1
 */
export interface Header1 {
    /**
     * 
     * @type {string}
     * @memberof Header1
     */
    'header_key': string;
    /**
     * 
     * @type {string}
     * @memberof Header1
     */
    'value': string;
}

