/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthenticationMethod8 } from './authentication-method8';

/**
 * Indexing configuration
 * @export
 * @interface Indexing2
 */
export interface Indexing2 {
    /**
     * Public Endpoint of the Qdrant cluser
     * @type {string}
     * @memberof Indexing2
     */
    'url': string;
    /**
     * 
     * @type {AuthenticationMethod8}
     * @memberof Indexing2
     */
    'auth_method'?: AuthenticationMethod8;
    /**
     * Whether to prefer gRPC over HTTP. Set to true for Qdrant cloud clusters
     * @type {boolean}
     * @memberof Indexing2
     */
    'prefer_grpc'?: boolean;
    /**
     * The collection to load data into
     * @type {string}
     * @memberof Indexing2
     */
    'collection': string;
    /**
     * The Distance metric used to measure similarities among vectors. This field is only used if the collection defined in the does not exist yet and is created automatically by the connector.
     * @type {string}
     * @memberof Indexing2
     */
    'distance_metric'?: Indexing2DistanceMetricEnum;
    /**
     * The field in the payload that contains the embedded text
     * @type {string}
     * @memberof Indexing2
     */
    'text_field'?: string;
}

export const Indexing2DistanceMetricEnum = {
    DOT: 'dot',
    COS: 'cos',
    EUC: 'euc'
} as const;

export type Indexing2DistanceMetricEnum = typeof Indexing2DistanceMetricEnum[keyof typeof Indexing2DistanceMetricEnum];


