/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthenticationMethod9 } from './authentication-method9';

/**
 * Indexing configuration
 * @export
 * @interface Indexing3
 */
export interface Indexing3 {
    /**
     * Public Endpoint of the Qdrant cluser
     * @type {string}
     * @memberof Indexing3
     */
    'url': string;
    /**
     * 
     * @type {AuthenticationMethod9}
     * @memberof Indexing3
     */
    'auth_method'?: AuthenticationMethod9;
    /**
     * Whether to prefer gRPC over HTTP. Set to true for Qdrant cloud clusters
     * @type {boolean}
     * @memberof Indexing3
     */
    'prefer_grpc'?: boolean;
    /**
     * The collection to load data into
     * @type {string}
     * @memberof Indexing3
     */
    'collection': string;
    /**
     * The Distance metric used to measure similarities among vectors. This field is only used if the collection defined in the does not exist yet and is created automatically by the connector.
     * @type {string}
     * @memberof Indexing3
     */
    'distance_metric'?: Indexing3DistanceMetricEnum;
    /**
     * The field in the payload that contains the embedded text
     * @type {string}
     * @memberof Indexing3
     */
    'text_field'?: string;
}

export const Indexing3DistanceMetricEnum = {
    DOT: 'dot',
    COS: 'cos',
    EUC: 'euc'
} as const;

export type Indexing3DistanceMetricEnum = typeof Indexing3DistanceMetricEnum[keyof typeof Indexing3DistanceMetricEnum];


