/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OAuthActorNames } from './oauth-actor-names';

/**
 * POST body for initiating OAuth via the public API
 * @export
 * @interface InitiateOauthRequest
 */
export interface InitiateOauthRequest {
    /**
     * The URL to redirect the user to with the OAuth secret stored in the secret_id query string parameter after authentication is complete.
     * @type {string}
     * @memberof InitiateOauthRequest
     */
    'redirectUrl': string;
    /**
     * The workspace to create the secret and eventually the full source.
     * @type {string}
     * @memberof InitiateOauthRequest
     */
    'workspaceId': string;
    /**
     * 
     * @type {any}
     * @memberof InitiateOauthRequest
     */
    'oAuthInputConfiguration'?: any;
    /**
     * 
     * @type {OAuthActorNames}
     * @memberof InitiateOauthRequest
     */
    'sourceType': OAuthActorNames;
}



