/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InitiateOauthRequest
 */
export interface InitiateOauthRequest {
    /**
     * The name of the source to authenticate to. Deprecated - use sourceType instead.
     * @type {string}
     * @memberof InitiateOauthRequest
     */
    'name'?: string;
    /**
     * The name of the source to authenticate to
     * @type {string}
     * @memberof InitiateOauthRequest
     */
    'sourceType'?: string;
    /**
     * The URL to redirect the user to with the OAuth secret stored in the secret_id query string parameter after authentication is complete.
     * @type {string}
     * @memberof InitiateOauthRequest
     */
    'redirectUrl': string;
    /**
     * The workspace to create the secret and eventually the full source.
     * @type {string}
     * @memberof InitiateOauthRequest
     */
    'workspaceId': string;
    /**
     * 
     * @type {any}
     * @memberof InitiateOauthRequest
     */
    'oAuthInputConfiguration'?: any;
}

