/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Int64Value
 */
export interface Int64Value {
    /**
     * 
     * @type {string}
     * @memberof Int64Value
     */
    'value_type': Int64ValueValueTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Int64Value
     */
    'value': string;
}

export const Int64ValueValueTypeEnum = {
    INT64_VALUE: 'int64Value'
} as const;

export type Int64ValueValueTypeEnum = typeof Int64ValueValueTypeEnum[keyof typeof Int64ValueValueTypeEnum];


