/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Using a table in a relational database to manage Iceberg tables through JDBC. Read more <a href=\"https://iceberg.apache.org/docs/latest/jdbc/\">here</a>. Supporting: PostgreSQL
 * @export
 * @interface JdbcCatalogUseRelationalDatabase
 */
export interface JdbcCatalogUseRelationalDatabase {
    /**
     * 
     * @type {string}
     * @memberof JdbcCatalogUseRelationalDatabase
     */
    'catalog_type': JdbcCatalogUseRelationalDatabaseCatalogTypeEnum;
    /**
     * The default schema tables are written to if the source does not specify a namespace. The usual value for this field is \"public\".
     * @type {string}
     * @memberof JdbcCatalogUseRelationalDatabase
     */
    'database'?: string;
    /**
     * 
     * @type {string}
     * @memberof JdbcCatalogUseRelationalDatabase
     */
    'jdbc_url'?: string;
    /**
     * Username to use to access the database.
     * @type {string}
     * @memberof JdbcCatalogUseRelationalDatabase
     */
    'username'?: string;
    /**
     * Password associated with the username.
     * @type {string}
     * @memberof JdbcCatalogUseRelationalDatabase
     */
    'password'?: string;
    /**
     * Encrypt data using SSL. When activating SSL, please select one of the connection modes.
     * @type {boolean}
     * @memberof JdbcCatalogUseRelationalDatabase
     */
    'ssl'?: boolean;
    /**
     * Iceberg catalog metadata tables are written to catalog schema. The usual value for this field is \"public\".
     * @type {string}
     * @memberof JdbcCatalogUseRelationalDatabase
     */
    'catalog_schema'?: string;
}

export const JdbcCatalogUseRelationalDatabaseCatalogTypeEnum = {
    JDBC: 'Jdbc'
} as const;

export type JdbcCatalogUseRelationalDatabaseCatalogTypeEnum = typeof JdbcCatalogUseRelationalDatabaseCatalogTypeEnum[keyof typeof JdbcCatalogUseRelationalDatabaseCatalogTypeEnum];


