/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface KeyPairAuthentication
 */
export interface KeyPairAuthentication {
    /**
     * 
     * @type {string}
     * @memberof KeyPairAuthentication
     */
    'auth_type'?: KeyPairAuthenticationAuthTypeEnum;
    /**
     * The username you created to allow Airbyte to access the database.
     * @type {string}
     * @memberof KeyPairAuthentication
     */
    'username': string;
    /**
     * RSA Private key to use for Snowflake connection. See the <a href=\"https://docs.airbyte.com/integrations/sources/snowflake#key-pair-authentication\">docs</a> for more information on how to obtain this key.
     * @type {string}
     * @memberof KeyPairAuthentication
     */
    'private_key': string;
    /**
     * Passphrase for private key
     * @type {string}
     * @memberof KeyPairAuthentication
     */
    'private_key_password'?: string;
}

export const KeyPairAuthenticationAuthTypeEnum = {
    KEY_PAIR_AUTHENTICATION: 'Key Pair Authentication'
} as const;

export type KeyPairAuthenticationAuthTypeEnum = typeof KeyPairAuthenticationAuthTypeEnum[keyof typeof KeyPairAuthenticationAuthTypeEnum];


