/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Process files locally, supporting `fast` and `ocr` modes. This is the default option.
 * @export
 * @interface Local
 */
export interface Local {
    /**
     * 
     * @type {string}
     * @memberof Local
     */
    'mode': LocalModeEnum;
}

export const LocalModeEnum = {
    LOCAL: 'local'
} as const;

export type LocalModeEnum = typeof LocalModeEnum[keyof typeof LocalModeEnum];


