/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EveryNThEntry } from './every-nth-entry';
// May contain unused imports in some cases
// @ts-ignore
import type { FirstNEntries } from './first-nentries';
// May contain unused imports in some cases
// @ts-ignore
import type { RandomSampling } from './random-sampling';

/**
 * @type LoggingConfiguration
 * Configurate how the messages are logged.
 * @export
 */
export type LoggingConfiguration = EveryNThEntry | FirstNEntries | RandomSampling;


