/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LoggingConfiguration } from './logging-configuration';

/**
 * 
 * @export
 * @interface Logging
 */
export interface Logging {
    /**
     * 
     * @type {string}
     * @memberof Logging
     */
    'test_destination_type': LoggingTestDestinationTypeEnum;
    /**
     * 
     * @type {LoggingConfiguration}
     * @memberof Logging
     */
    'logging_config': LoggingConfiguration;
}

export const LoggingTestDestinationTypeEnum = {
    LOGGING: 'LOGGING'
} as const;

export type LoggingTestDestinationTypeEnum = typeof LoggingTestDestinationTypeEnum[keyof typeof LoggingTestDestinationTypeEnum];


