/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Login/Password.
 * @export
 * @interface LoginPassword1
 */
export interface LoginPassword1 {
    /**
     * 
     * @type {string}
     * @memberof LoginPassword1
     */
    'authorization': LoginPassword1AuthorizationEnum;
    /**
     * Username to use to access the database.
     * @type {string}
     * @memberof LoginPassword1
     */
    'username': string;
    /**
     * Password associated with the username.
     * @type {string}
     * @memberof LoginPassword1
     */
    'password': string;
}

export const LoginPassword1AuthorizationEnum = {
    LOGIN_PASSWORD: 'login/password'
} as const;

export type LoginPassword1AuthorizationEnum = typeof LoginPassword1AuthorizationEnum[keyof typeof LoginPassword1AuthorizationEnum];


