/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AndGroup } from './and-group';
// May contain unused imports in some cases
// @ts-ignore
import type { Expression } from './expression';
// May contain unused imports in some cases
// @ts-ignore
import type { Filter } from './filter';
// May contain unused imports in some cases
// @ts-ignore
import type { Filter2 } from './filter2';
// May contain unused imports in some cases
// @ts-ignore
import type { NotExpression } from './not-expression';
// May contain unused imports in some cases
// @ts-ignore
import type { OrGroup } from './or-group';

/**
 * @type MetricsFilter
 * Metrics filter
 * @export
 */
export type MetricsFilter = AndGroup | Filter2 | NotExpression | OrGroup;


