/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Define the location where the data will be stored in the destination
 * @export
 * @enum {string}
 */

export const NamespaceDefinitionEnumNoDefault = {
    SOURCE: 'source',
    DESTINATION: 'destination',
    CUSTOM_FORMAT: 'custom_format'
} as const;

export type NamespaceDefinitionEnumNoDefault = typeof NamespaceDefinitionEnumNoDefault[keyof typeof NamespaceDefinitionEnumNoDefault];



