/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The native network encryption gives you the ability to encrypt database connections, without the configuration overhead of TCP/IP and SSL/TLS and without the need to open and listen on different ports.
 * @export
 * @interface NativeNetworkEncryptionNNE
 */
export interface NativeNetworkEncryptionNNE {
    /**
     * 
     * @type {string}
     * @memberof NativeNetworkEncryptionNNE
     */
    'encryption_method': NativeNetworkEncryptionNNEEncryptionMethodEnum;
    /**
     * This parameter defines what encryption algorithm is used.
     * @type {string}
     * @memberof NativeNetworkEncryptionNNE
     */
    'encryption_algorithm'?: NativeNetworkEncryptionNNEEncryptionAlgorithmEnum;
}

export const NativeNetworkEncryptionNNEEncryptionMethodEnum = {
    CLIENT_NNE: 'client_nne'
} as const;

export type NativeNetworkEncryptionNNEEncryptionMethodEnum = typeof NativeNetworkEncryptionNNEEncryptionMethodEnum[keyof typeof NativeNetworkEncryptionNNEEncryptionMethodEnum];
export const NativeNetworkEncryptionNNEEncryptionAlgorithmEnum = {
    AES256: 'AES256',
    RC4_56: 'RC4_56',
    _3_DES168: '3DES168'
} as const;

export type NativeNetworkEncryptionNNEEncryptionAlgorithmEnum = typeof NativeNetworkEncryptionNNEEncryptionAlgorithmEnum[keyof typeof NativeNetworkEncryptionNNEEncryptionAlgorithmEnum];


