/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The native network encryption gives you the ability to encrypt database connections, without the configuration overhead of TCP/IP and SSL/TLS and without the need to open and listen on different ports.
 * @export
 * @interface NativeNetworkEncryptionNNE1
 */
export interface NativeNetworkEncryptionNNE1 {
    /**
     * 
     * @type {string}
     * @memberof NativeNetworkEncryptionNNE1
     */
    'encryption_method': NativeNetworkEncryptionNNE1EncryptionMethodEnum;
    /**
     * This parameter defines the database encryption algorithm.
     * @type {string}
     * @memberof NativeNetworkEncryptionNNE1
     */
    'encryption_algorithm'?: NativeNetworkEncryptionNNE1EncryptionAlgorithmEnum;
}

export const NativeNetworkEncryptionNNE1EncryptionMethodEnum = {
    CLIENT_NNE: 'client_nne'
} as const;

export type NativeNetworkEncryptionNNE1EncryptionMethodEnum = typeof NativeNetworkEncryptionNNE1EncryptionMethodEnum[keyof typeof NativeNetworkEncryptionNNE1EncryptionMethodEnum];
export const NativeNetworkEncryptionNNE1EncryptionAlgorithmEnum = {
    AES256: 'AES256',
    RC4_56: 'RC4_56',
    _3_DES168: '3DES168'
} as const;

export type NativeNetworkEncryptionNNE1EncryptionAlgorithmEnum = typeof NativeNetworkEncryptionNNE1EncryptionAlgorithmEnum[keyof typeof NativeNetworkEncryptionNNE1EncryptionAlgorithmEnum];


