/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Do not authenticate (suitable for locally running test clusters, do not use for clusters with public IP addresses)
 * @export
 * @interface NoAuthentication
 */
export interface NoAuthentication {
    /**
     * 
     * @type {string}
     * @memberof NoAuthentication
     */
    'mode': NoAuthenticationModeEnum;
}

export const NoAuthenticationModeEnum = {
    NO_AUTH: 'no_auth'
} as const;

export type NoAuthenticationModeEnum = typeof NoAuthenticationModeEnum[keyof typeof NoAuthenticationModeEnum];


