/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NoCompression2
 */
export interface NoCompression2 {
    /**
     * 
     * @type {string}
     * @memberof NoCompression2
     */
    'compression_type'?: NoCompression2CompressionTypeEnum;
}

export const NoCompression2CompressionTypeEnum = {
    NO_COMPRESSION: 'No Compression'
} as const;

export type NoCompression2CompressionTypeEnum = typeof NoCompression2CompressionTypeEnum[keyof typeof NoCompression2CompressionTypeEnum];


