/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Set how Airbyte handles syncs when it detects a non-breaking schema change in the source
 * @export
 * @enum {string}
 */

export const NonBreakingSchemaUpdatesBehaviorEnum = {
    IGNORE: 'ignore',
    DISABLE_CONNECTION: 'disable_connection',
    PROPAGATE_COLUMNS: 'propagate_columns',
    PROPAGATE_FULLY: 'propagate_fully'
} as const;

export type NonBreakingSchemaUpdatesBehaviorEnum = typeof NonBreakingSchemaUpdatesBehaviorEnum[keyof typeof NonBreakingSchemaUpdatesBehaviorEnum];



