/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * No authentication will be used
 * @export
 * @interface None1
 */
export interface None1 {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof None1
     */
    'method': None1MethodEnum;
}

export const None1MethodEnum = {
    NONE: 'none'
} as const;

export type None1MethodEnum = typeof None1MethodEnum[keyof typeof None1MethodEnum];


