/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Expression } from './expression';

/**
 * The FilterExpression is NOT of notExpression.
 * @export
 * @interface NotExpression
 */
export interface NotExpression {
    /**
     * 
     * @type {string}
     * @memberof NotExpression
     */
    'filter_type'?: NotExpressionFilterTypeEnum;
    /**
     * 
     * @type {Expression}
     * @memberof NotExpression
     */
    'expression'?: Expression;
}

export const NotExpressionFilterTypeEnum = {
    NOT_EXPRESSION: 'notExpression'
} as const;

export type NotExpressionFilterTypeEnum = typeof NotExpressionFilterTypeEnum[keyof typeof NotExpressionFilterTypeEnum];


