/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OAuth2019
 */
export interface OAuth2019 {
    /**
     * 
     * @type {string}
     * @memberof OAuth2019
     */
    'auth_method'?: OAuth2019AuthMethodEnum;
    /**
     * The client ID of your developer application. Refer to our <a href=\'https://docs.airbyte.com/integrations/sources/linkedin-ads#setup-guide\'>documentation</a> for more information.
     * @type {string}
     * @memberof OAuth2019
     */
    'client_id': string;
    /**
     * The client secret of your developer application. Refer to our <a href=\'https://docs.airbyte.com/integrations/sources/linkedin-ads#setup-guide\'>documentation</a> for more information.
     * @type {string}
     * @memberof OAuth2019
     */
    'client_secret': string;
    /**
     * The key to refresh the expired access token. Refer to our <a href=\'https://docs.airbyte.com/integrations/sources/linkedin-ads#setup-guide\'>documentation</a> for more information.
     * @type {string}
     * @memberof OAuth2019
     */
    'refresh_token': string;
}

export const OAuth2019AuthMethodEnum = {
    O_AUTH2_0: 'oAuth2.0'
} as const;

export type OAuth2019AuthMethodEnum = typeof OAuth2019AuthMethodEnum[keyof typeof OAuth2019AuthMethodEnum];


