/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OAuth208
 */
export interface OAuth208 {
    /**
     * 
     * @type {string}
     * @memberof OAuth208
     */
    'auth_type'?: OAuth208AuthTypeEnum;
    /**
     * The API ID of the Gitlab developer application.
     * @type {string}
     * @memberof OAuth208
     */
    'client_id': string;
    /**
     * The API Secret the Gitlab developer application.
     * @type {string}
     * @memberof OAuth208
     */
    'client_secret': string;
    /**
     * Access Token for making authenticated requests.
     * @type {string}
     * @memberof OAuth208
     */
    'access_token': string;
    /**
     * The date-time when the access token should be refreshed.
     * @type {string}
     * @memberof OAuth208
     */
    'token_expiry_date': string;
    /**
     * The key to refresh the expired access_token.
     * @type {string}
     * @memberof OAuth208
     */
    'refresh_token': string;
}

export const OAuth208AuthTypeEnum = {
    OAUTH2_0: 'oauth2.0'
} as const;

export type OAuth208AuthTypeEnum = typeof OAuth208AuthTypeEnum[keyof typeof OAuth208AuthTypeEnum];


