/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OAuth2033
 */
export interface OAuth2033 {
    /**
     * 
     * @type {string}
     * @memberof OAuth2033
     */
    'auth_type': OAuth2033AuthTypeEnum;
    /**
     * The Client ID of your OAuth application.
     * @type {string}
     * @memberof OAuth2033
     */
    'client_id'?: string;
    /**
     * The Client Secret of your OAuth application.
     * @type {string}
     * @memberof OAuth2033
     */
    'client_secret'?: string;
    /**
     * An access token generated using the above client ID and secret.
     * @type {string}
     * @memberof OAuth2033
     */
    'access_token': string;
}

export const OAuth2033AuthTypeEnum = {
    OAUTH2_0: 'oauth2.0'
} as const;

export type OAuth2033AuthTypeEnum = typeof OAuth2033AuthTypeEnum[keyof typeof OAuth2033AuthTypeEnum];


