/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OAuth2012
 */
export interface OAuth2012 {
    /**
     * 
     * @type {string}
     * @memberof OAuth2012
     */
    'auth_type'?: OAuth2012AuthTypeEnum;
    /**
     * The API ID of the SmartSheets developer application.
     * @type {string}
     * @memberof OAuth2012
     */
    'client_id': string;
    /**
     * The API Secret the SmartSheets developer application.
     * @type {string}
     * @memberof OAuth2012
     */
    'client_secret': string;
    /**
     * Access Token for making authenticated requests.
     * @type {string}
     * @memberof OAuth2012
     */
    'access_token': string;
    /**
     * The date-time when the access token should be refreshed.
     * @type {string}
     * @memberof OAuth2012
     */
    'token_expiry_date': string;
    /**
     * The key to refresh the expired access_token.
     * @type {string}
     * @memberof OAuth2012
     */
    'refresh_token': string;
}

export const OAuth2012AuthTypeEnum = {
    OAUTH2_0: 'oauth2.0'
} as const;

export type OAuth2012AuthTypeEnum = typeof OAuth2012AuthTypeEnum[keyof typeof OAuth2012AuthTypeEnum];


