/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OAuth206
 */
export interface OAuth206 {
    /**
     * The client ID of the LinkedIn developer application.
     * @type {string}
     * @memberof OAuth206
     */
    'client_id': string;
    /**
     * 
     * @type {string}
     * @memberof OAuth206
     */
    'auth_method'?: OAuth206AuthMethodEnum;
    /**
     * The client secret of the LinkedIn developer application.
     * @type {string}
     * @memberof OAuth206
     */
    'client_secret': string;
    /**
     * The token value generated using the LinkedIn Developers OAuth Token Tools. See the <a href=\"https://docs.airbyte.com/integrations/sources/linkedin-pages/\">docs</a> to obtain yours.
     * @type {string}
     * @memberof OAuth206
     */
    'refresh_token': string;
}

export const OAuth206AuthMethodEnum = {
    O_AUTH2_0: 'oAuth2.0'
} as const;

export type OAuth206AuthMethodEnum = typeof OAuth206AuthMethodEnum[keyof typeof OAuth206AuthMethodEnum];


