/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OAuth2021
 */
export interface OAuth2021 {
    /**
     * 
     * @type {string}
     * @memberof OAuth2021
     */
    'auth_method': OAuth2021AuthMethodEnum;
    /**
     * The Client ID of your OAuth application
     * @type {string}
     * @memberof OAuth2021
     */
    'client_id': string;
    /**
     * The Client Secret of your OAuth application.
     * @type {string}
     * @memberof OAuth2021
     */
    'client_secret': string;
    /**
     * Refresh Token to obtain new Access Token, when it\'s expired.
     * @type {string}
     * @memberof OAuth2021
     */
    'refresh_token': string;
}

export const OAuth2021AuthMethodEnum = {
    OAUTH2_0: 'oauth2.0'
} as const;

export type OAuth2021AuthMethodEnum = typeof OAuth2021AuthMethodEnum[keyof typeof OAuth2021AuthMethodEnum];


