/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OAuth2030
 */
export interface OAuth2030 {
    /**
     * Slug/subdomain of the account, or the first part of the URL that comes before .monday.com
     * @type {string}
     * @memberof OAuth2030
     */
    'subdomain'?: string;
    /**
     * 
     * @type {string}
     * @memberof OAuth2030
     */
    'auth_type': OAuth2030AuthTypeEnum;
    /**
     * The Client ID of your OAuth application.
     * @type {string}
     * @memberof OAuth2030
     */
    'client_id': string;
    /**
     * The Client Secret of your OAuth application.
     * @type {string}
     * @memberof OAuth2030
     */
    'client_secret': string;
    /**
     * Access Token for making authenticated requests.
     * @type {string}
     * @memberof OAuth2030
     */
    'access_token': string;
}

export const OAuth2030AuthTypeEnum = {
    OAUTH2_0: 'oauth2.0'
} as const;

export type OAuth2030AuthTypeEnum = typeof OAuth2030AuthTypeEnum[keyof typeof OAuth2030AuthTypeEnum];


