/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OAuth2024
 */
export interface OAuth2024 {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof OAuth2024
     */
    'credentials'?: OAuth2024CredentialsEnum;
    /**
     * The OAuth access token. See the <a href=\"https://developer.zendesk.com/documentation/ticketing/working-with-oauth/creating-and-using-oauth-tokens-with-the-api/\">Zendesk docs</a> for more information on generating this token.
     * @type {string}
     * @memberof OAuth2024
     */
    'access_token': string;
    /**
     * The OAuth client\'s ID. See <a href=\"https://docs.searchunify.com/Content/Content-Sources/Zendesk-Authentication-OAuth-Client-ID-Secret.htm#:~:text=Get%20Client%20ID%20and%20Client%20Secret&text=Go%20to%20OAuth%20Clients%20and,will%20be%20displayed%20only%20once.\">this guide</a> for more information.
     * @type {string}
     * @memberof OAuth2024
     */
    'client_id'?: string;
    /**
     * The OAuth client secret. See <a href=\"https://docs.searchunify.com/Content/Content-Sources/Zendesk-Authentication-OAuth-Client-ID-Secret.htm#:~:text=Get%20Client%20ID%20and%20Client%20Secret&text=Go%20to%20OAuth%20Clients%20and,will%20be%20displayed%20only%20once.\">this guide</a> for more information.
     * @type {string}
     * @memberof OAuth2024
     */
    'client_secret'?: string;
}

export const OAuth2024CredentialsEnum = {
    OAUTH2_0: 'oauth2.0'
} as const;

export type OAuth2024CredentialsEnum = typeof OAuth2024CredentialsEnum[keyof typeof OAuth2024CredentialsEnum];


