/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OAuth2037
 */
export interface OAuth2037 {
    /**
     * 
     * @type {string}
     * @memberof OAuth2037
     */
    'auth_type'?: OAuth2037AuthTypeEnum;
    /**
     * Enter your application\'s Client ID
     * @type {string}
     * @memberof OAuth2037
     */
    'client_id'?: string;
    /**
     * Enter your application\'s Client secret
     * @type {string}
     * @memberof OAuth2037
     */
    'client_secret'?: string;
    /**
     * Enter you application\'s Access Token
     * @type {string}
     * @memberof OAuth2037
     */
    'access_token': string;
    /**
     * Enter your application\'s Refresh Token
     * @type {string}
     * @memberof OAuth2037
     */
    'refresh_token': string;
}

export const OAuth2037AuthTypeEnum = {
    O_AUTH2_0: 'OAuth2.0'
} as const;

export type OAuth2037AuthTypeEnum = typeof OAuth2037AuthTypeEnum[keyof typeof OAuth2037AuthTypeEnum];


