/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Airtable } from './airtable';
// May contain unused imports in some cases
// @ts-ignore
import type { AmazonAds } from './amazon-ads';
// May contain unused imports in some cases
// @ts-ignore
import type { AmazonSellerPartner } from './amazon-seller-partner';
// May contain unused imports in some cases
// @ts-ignore
import type { Asana } from './asana';
// May contain unused imports in some cases
// @ts-ignore
import type { AzureBlobStorage } from './azure-blob-storage';
// May contain unused imports in some cases
// @ts-ignore
import type { BingAds } from './bing-ads';
// May contain unused imports in some cases
// @ts-ignore
import type { FacebookMarketing } from './facebook-marketing';
// May contain unused imports in some cases
// @ts-ignore
import type { Github } from './github';
// May contain unused imports in some cases
// @ts-ignore
import type { Gitlab } from './gitlab';
// May contain unused imports in some cases
// @ts-ignore
import type { GoogleAds } from './google-ads';
// May contain unused imports in some cases
// @ts-ignore
import type { GoogleAnalyticsDataApi } from './google-analytics-data-api';
// May contain unused imports in some cases
// @ts-ignore
import type { GoogleDrive } from './google-drive';
// May contain unused imports in some cases
// @ts-ignore
import type { GoogleSearchConsole } from './google-search-console';
// May contain unused imports in some cases
// @ts-ignore
import type { GoogleSearchConsoleAuthorization } from './google-search-console-authorization';
// May contain unused imports in some cases
// @ts-ignore
import type { GoogleSheets } from './google-sheets';
// May contain unused imports in some cases
// @ts-ignore
import type { Hubspot } from './hubspot';
// May contain unused imports in some cases
// @ts-ignore
import type { Instagram } from './instagram';
// May contain unused imports in some cases
// @ts-ignore
import type { Intercom } from './intercom';
// May contain unused imports in some cases
// @ts-ignore
import type { LeverHiring } from './lever-hiring';
// May contain unused imports in some cases
// @ts-ignore
import type { LinkedinAds } from './linkedin-ads';
// May contain unused imports in some cases
// @ts-ignore
import type { Mailchimp } from './mailchimp';
// May contain unused imports in some cases
// @ts-ignore
import type { MicrosoftOnedrive } from './microsoft-onedrive';
// May contain unused imports in some cases
// @ts-ignore
import type { MicrosoftSharepoint } from './microsoft-sharepoint';
// May contain unused imports in some cases
// @ts-ignore
import type { MicrosoftTeams } from './microsoft-teams';
// May contain unused imports in some cases
// @ts-ignore
import type { Monday } from './monday';
// May contain unused imports in some cases
// @ts-ignore
import type { Notion } from './notion';
// May contain unused imports in some cases
// @ts-ignore
import type { Pinterest } from './pinterest';
// May contain unused imports in some cases
// @ts-ignore
import type { Retently } from './retently';
// May contain unused imports in some cases
// @ts-ignore
import type { Salesforce } from './salesforce';
// May contain unused imports in some cases
// @ts-ignore
import type { Shopify } from './shopify';
// May contain unused imports in some cases
// @ts-ignore
import type { Slack } from './slack';
// May contain unused imports in some cases
// @ts-ignore
import type { Smartsheets } from './smartsheets';
// May contain unused imports in some cases
// @ts-ignore
import type { SnapchatMarketing } from './snapchat-marketing';
// May contain unused imports in some cases
// @ts-ignore
import type { Snowflake } from './snowflake';
// May contain unused imports in some cases
// @ts-ignore
import type { Square } from './square';
// May contain unused imports in some cases
// @ts-ignore
import type { Surveymonkey } from './surveymonkey';
// May contain unused imports in some cases
// @ts-ignore
import type { TiktokMarketing } from './tiktok-marketing';
// May contain unused imports in some cases
// @ts-ignore
import type { Typeform } from './typeform';
// May contain unused imports in some cases
// @ts-ignore
import type { YoutubeAnalytics } from './youtube-analytics';
// May contain unused imports in some cases
// @ts-ignore
import type { ZendeskChat } from './zendesk-chat';
// May contain unused imports in some cases
// @ts-ignore
import type { ZendeskSunshine } from './zendesk-sunshine';
// May contain unused imports in some cases
// @ts-ignore
import type { ZendeskSupport } from './zendesk-support';
// May contain unused imports in some cases
// @ts-ignore
import type { ZendeskTalk } from './zendesk-talk';
// May contain unused imports in some cases
// @ts-ignore
import type { ZendeskTalkCredentials } from './zendesk-talk-credentials';

/**
 * @type OAuthCredentialsConfiguration
 * The values required to configure the source.
 * @export
 */
export type OAuthCredentialsConfiguration = Airtable | AmazonAds | AmazonSellerPartner | Asana | AzureBlobStorage | BingAds | FacebookMarketing | Github | Gitlab | GoogleAds | GoogleAnalyticsDataApi | GoogleDrive | GoogleSearchConsole | GoogleSheets | Hubspot | Instagram | Intercom | LeverHiring | LinkedinAds | Mailchimp | MicrosoftOnedrive | MicrosoftSharepoint | MicrosoftTeams | Monday | Notion | Pinterest | Retently | Salesforce | Shopify | Slack | Smartsheets | SnapchatMarketing | Snowflake | Square | Surveymonkey | TiktokMarketing | Typeform | YoutubeAnalytics | ZendeskChat | ZendeskSunshine | ZendeskSupport | ZendeskTalk;


