/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OAuth205
 */
export interface OAuth205 {
    /**
     * 
     * @type {string}
     * @memberof OAuth205
     */
    'auth_method': OAuth205AuthMethodEnum;
    /**
     * The Client ID of your OAuth application.
     * @type {string}
     * @memberof OAuth205
     */
    'client_id': string;
    /**
     * The Client Secret of your OAuth application.
     * @type {string}
     * @memberof OAuth205
     */
    'client_secret': string;
    /**
     * Long-term access Token for making authenticated requests.
     * @type {string}
     * @memberof OAuth205
     */
    'access_token': string;
}

export const OAuth205AuthMethodEnum = {
    OAUTH2_0: 'oauth2.0'
} as const;

export type OAuth205AuthMethodEnum = typeof OAuth205AuthMethodEnum[keyof typeof OAuth205AuthMethodEnum];


