/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Provides details of a single organization for a user.
 * @export
 * @interface OrganizationResponse
 */
export interface OrganizationResponse {
    /**
     * 
     * @type {string}
     * @memberof OrganizationResponse
     */
    'organizationId': string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationResponse
     */
    'organizationName': string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationResponse
     */
    'email': string;
}

