/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JSONLinesNewlineDelimitedJSON1 } from './jsonlines-newline-delimited-json1';
// May contain unused imports in some cases
// @ts-ignore
import type { ParquetColumnarStorage1 } from './parquet-columnar-storage1';

/**
 * @type OutputFormat
 * Format of the data output.
 * @export
 */
export type OutputFormat = JSONLinesNewlineDelimitedJSON1 | ParquetColumnarStorage1;


