/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ParquetFormat
 */
export interface ParquetFormat {
    /**
     * 
     * @type {string}
     * @memberof ParquetFormat
     */
    'filetype': ParquetFormatFiletypeEnum;
    /**
     * Whether to convert decimal fields to floats. There is a loss of precision when converting decimals to floats, so this is not recommended.
     * @type {boolean}
     * @memberof ParquetFormat
     */
    'decimal_as_float'?: boolean;
}

export const ParquetFormatFiletypeEnum = {
    PARQUET: 'parquet'
} as const;

export type ParquetFormatFiletypeEnum = typeof ParquetFormatFiletypeEnum[keyof typeof ParquetFormatFiletypeEnum];


