/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PasswordAuthentication2
 */
export interface PasswordAuthentication2 {
    /**
     * Connect through password authentication
     * @type {string}
     * @memberof PasswordAuthentication2
     */
    'auth_method': PasswordAuthentication2AuthMethodEnum;
    /**
     * OS-level password for logging into the jump server host
     * @type {string}
     * @memberof PasswordAuthentication2
     */
    'auth_user_password': string;
}

export const PasswordAuthentication2AuthMethodEnum = {
    SSH_PASSWORD_AUTH: 'SSH_PASSWORD_AUTH'
} as const;

export type PasswordAuthentication2AuthMethodEnum = typeof PasswordAuthentication2AuthMethodEnum[keyof typeof PasswordAuthentication2AuthMethodEnum];


