/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PersonalAccessToken
 */
export interface PersonalAccessToken {
    /**
     * 
     * @type {string}
     * @memberof PersonalAccessToken
     */
    'option_title'?: PersonalAccessTokenOptionTitleEnum;
    /**
     * Log into GitHub and then generate a <a href=\"https://github.com/settings/tokens\">personal access token</a>. To load balance your API quota consumption across multiple API tokens, input multiple tokens separated with \",\"
     * @type {string}
     * @memberof PersonalAccessToken
     */
    'personal_access_token': string;
}

export const PersonalAccessTokenOptionTitleEnum = {
    PAT_CREDENTIALS: 'PAT Credentials'
} as const;

export type PersonalAccessTokenOptionTitleEnum = typeof PersonalAccessTokenOptionTitleEnum[keyof typeof PersonalAccessTokenOptionTitleEnum];


