/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PersonalAccessToken5
 */
export interface PersonalAccessToken5 {
    /**
     * 
     * @type {string}
     * @memberof PersonalAccessToken5
     */
    'auth_type': PersonalAccessToken5AuthTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PersonalAccessToken5
     */
    'personal_access_token': string;
}

export const PersonalAccessToken5AuthTypeEnum = {
    BASIC: 'BASIC'
} as const;

export type PersonalAccessToken5AuthTypeEnum = typeof PersonalAccessToken5AuthTypeEnum[keyof typeof PersonalAccessToken5AuthTypeEnum];


