/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Allows unencrypted connection only if the source database does not support encryption.
 * @export
 * @interface Prefer
 */
export interface Prefer {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof Prefer
     */
    'mode': PreferModeEnum;
}

export const PreferModeEnum = {
    PREFER: 'prefer'
} as const;

export type PreferModeEnum = typeof PreferModeEnum[keyof typeof PreferModeEnum];


