/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Automatically attempt SSL connection. If the MySQL server does not support SSL, continue with a regular connection.
 * @export
 * @interface Preferred
 */
export interface Preferred {
    /**
     * 
     * @type {string}
     * @memberof Preferred
     */
    'mode': PreferredModeEnum;
}

export const PreferredModeEnum = {
    PREFERRED: 'preferred'
} as const;

export type PreferredModeEnum = typeof PreferredModeEnum[keyof typeof PreferredModeEnum];


