/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Prefer SSL mode.
 * @export
 * @interface Prefer2
 */
export interface Prefer2 {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof Prefer2
     */
    'mode': Prefer2ModeEnum;
}

export const Prefer2ModeEnum = {
    PREFER: 'prefer'
} as const;

export type Prefer2ModeEnum = typeof Prefer2ModeEnum[keyof typeof Prefer2ModeEnum];


