/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Prefer SSL mode.
 * @export
 * @interface Prefer3
 */
export interface Prefer3 {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof Prefer3
     */
    'mode': Prefer3ModeEnum;
}

export const Prefer3ModeEnum = {
    PREFER: 'prefer'
} as const;

export type Prefer3ModeEnum = typeof Prefer3ModeEnum[keyof typeof Prefer3ModeEnum];


