/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * For each stream, randomly log a percentage of the entries with a maximum cap.
 * @export
 * @interface RandomSampling
 */
export interface RandomSampling {
    /**
     * 
     * @type {string}
     * @memberof RandomSampling
     */
    'logging_type': RandomSamplingLoggingTypeEnum;
    /**
     * A positive floating number smaller than 1.
     * @type {number}
     * @memberof RandomSampling
     */
    'sampling_ratio': number;
    /**
     * When the seed is unspecified, the current time millis will be used as the seed.
     * @type {number}
     * @memberof RandomSampling
     */
    'seed'?: number;
    /**
     * Max number of entries to log. This destination is for testing only. So it won\'t make sense to log infinitely. The maximum is 1,000 entries.
     * @type {number}
     * @memberof RandomSampling
     */
    'max_entry_count': number;
}

export const RandomSamplingLoggingTypeEnum = {
    RANDOM_SAMPLING: 'RandomSampling'
} as const;

export type RandomSamplingLoggingTypeEnum = typeof RandomSamplingLoggingTypeEnum[keyof typeof RandomSamplingLoggingTypeEnum];


