/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * <i>Recommended</i> - Incrementally reads new inserts, updates, and deletes using the SQL Server\'s <a href=\"https://docs.airbyte.com/integrations/sources/mssql/#change-data-capture-cdc\">change data capture feature</a>. This must be enabled on your database.
 * @export
 * @interface ReadChangesUsingChangeDataCaptureCDC
 */
export interface ReadChangesUsingChangeDataCaptureCDC {
    /**
     * 
     * @type {string}
     * @memberof ReadChangesUsingChangeDataCaptureCDC
     */
    'method': ReadChangesUsingChangeDataCaptureCDCMethodEnum;
    /**
     * The amount of time the connector will wait when it launches to determine if there is new data to sync or not. Defaults to 300 seconds. Valid range: 120 seconds to 3600 seconds. Read about <a href=\"https://docs.airbyte.com/integrations/sources/mysql/#change-data-capture-cdc\">initial waiting time</a>.
     * @type {number}
     * @memberof ReadChangesUsingChangeDataCaptureCDC
     */
    'initial_waiting_seconds'?: number;
    /**
     * Determines whether Airbyte should fail or re-sync data in case of an stale/invalid cursor value into the WAL. If \'Fail sync\' is chosen, a user will have to manually reset the connection before being able to continue syncing data. If \'Re-sync data\' is chosen, Airbyte will automatically trigger a refresh but could lead to higher cloud costs and data loss.
     * @type {string}
     * @memberof ReadChangesUsingChangeDataCaptureCDC
     */
    'invalid_cdc_cursor_position_behavior'?: ReadChangesUsingChangeDataCaptureCDCInvalidCdcCursorPositionBehaviorEnum;
    /**
     * The size of the internal queue. This may interfere with memory consumption and efficiency of the connector, please be careful.
     * @type {number}
     * @memberof ReadChangesUsingChangeDataCaptureCDC
     */
    'queue_size'?: number;
    /**
     * The amount of time an initial load is allowed to continue for before catching up on CDC logs.
     * @type {number}
     * @memberof ReadChangesUsingChangeDataCaptureCDC
     */
    'initial_load_timeout_hours'?: number;
}

export const ReadChangesUsingChangeDataCaptureCDCMethodEnum = {
    CDC: 'CDC'
} as const;

export type ReadChangesUsingChangeDataCaptureCDCMethodEnum = typeof ReadChangesUsingChangeDataCaptureCDCMethodEnum[keyof typeof ReadChangesUsingChangeDataCaptureCDCMethodEnum];
export const ReadChangesUsingChangeDataCaptureCDCInvalidCdcCursorPositionBehaviorEnum = {
    FAIL_SYNC: 'Fail sync',
    RE_SYNC_DATA: 'Re-sync data'
} as const;

export type ReadChangesUsingChangeDataCaptureCDCInvalidCdcCursorPositionBehaviorEnum = typeof ReadChangesUsingChangeDataCaptureCDCInvalidCdcCursorPositionBehaviorEnum[keyof typeof ReadChangesUsingChangeDataCaptureCDCInvalidCdcCursorPositionBehaviorEnum];


