/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Always connect with SSL. If the MySQL server doesn’t support SSL, the connection will not be established. Certificate Authority (CA) and Hostname are not verified.
 * @export
 * @interface Required
 */
export interface Required {
    /**
     * 
     * @type {string}
     * @memberof Required
     */
    'mode': RequiredModeEnum;
}

export const RequiredModeEnum = {
    REQUIRED: 'required'
} as const;

export type RequiredModeEnum = typeof RequiredModeEnum[keyof typeof RequiredModeEnum];


