/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Require SSL mode.
 * @export
 * @interface Require3
 */
export interface Require3 {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof Require3
     */
    'mode': Require3ModeEnum;
}

export const Require3ModeEnum = {
    REQUIRE: 'require'
} as const;

export type Require3ModeEnum = typeof Require3ModeEnum[keyof typeof Require3ModeEnum];


