/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RoleBasedAuthentication
 */
export interface RoleBasedAuthentication {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof RoleBasedAuthentication
     */
    'auth_type'?: RoleBasedAuthenticationAuthTypeEnum;
}

export const RoleBasedAuthenticationAuthTypeEnum = {
    ROLE: 'Role'
} as const;

export type RoleBasedAuthenticationAuthTypeEnum = typeof RoleBasedAuthenticationAuthTypeEnum[keyof typeof RoleBasedAuthenticationAuthTypeEnum];


