/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface S3AmazonWebServices
 */
export interface S3AmazonWebServices {
    /**
     * 
     * @type {string}
     * @memberof S3AmazonWebServices
     */
    'storage': S3AmazonWebServicesStorageEnum;
    /**
     * In order to access private Buckets stored on AWS S3, this connector would need credentials with the proper permissions. If accessing publicly available data, this field is not necessary.
     * @type {string}
     * @memberof S3AmazonWebServices
     */
    'aws_access_key_id'?: string;
    /**
     * In order to access private Buckets stored on AWS S3, this connector would need credentials with the proper permissions. If accessing publicly available data, this field is not necessary.
     * @type {string}
     * @memberof S3AmazonWebServices
     */
    'aws_secret_access_key'?: string;
}

export const S3AmazonWebServicesStorageEnum = {
    S3: 'S3'
} as const;

export type S3AmazonWebServicesStorageEnum = typeof S3AmazonWebServicesStorageEnum[keyof typeof S3AmazonWebServicesStorageEnum];


