/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SandboxAccessToken
 */
export interface SandboxAccessToken {
    /**
     * 
     * @type {string}
     * @memberof SandboxAccessToken
     */
    'auth_type'?: SandboxAccessTokenAuthTypeEnum;
    /**
     * The Advertiser ID which generated for the developer\'s Sandbox application.
     * @type {string}
     * @memberof SandboxAccessToken
     */
    'advertiser_id': string;
    /**
     * The long-term authorized access token.
     * @type {string}
     * @memberof SandboxAccessToken
     */
    'access_token': string;
}

export const SandboxAccessTokenAuthTypeEnum = {
    SANDBOX_ACCESS_TOKEN: 'sandbox_access_token'
} as const;

export type SandboxAccessTokenAuthTypeEnum = typeof SandboxAccessTokenAuthTypeEnum[keyof typeof SandboxAccessTokenAuthTypeEnum];


