/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Incrementally detects new inserts and updates using the <a href=\"https://docs.airbyte.com/understanding-airbyte/connections/incremental-append/#user-defined-cursor\">cursor column</a> chosen when configuring a connection (e.g. created_at, updated_at).
 * @export
 * @interface ScanChangesWithUserDefinedCursor
 */
export interface ScanChangesWithUserDefinedCursor {
    /**
     * 
     * @type {string}
     * @memberof ScanChangesWithUserDefinedCursor
     */
    'method': ScanChangesWithUserDefinedCursorMethodEnum;
}

export const ScanChangesWithUserDefinedCursorMethodEnum = {
    STANDARD: 'Standard'
} as const;

export type ScanChangesWithUserDefinedCursorMethodEnum = typeof ScanChangesWithUserDefinedCursorMethodEnum[keyof typeof ScanChangesWithUserDefinedCursorMethodEnum];


