/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Path to a field/column/property in a stream to be selected. For example, if the field to be selected is a database column called \"foo\", this will be [\"foo\"]. Use multiple path elements for nested schemas.
 * @export
 * @interface SelectedFieldInfo
 */
export interface SelectedFieldInfo {
    /**
     * 
     * @type {Array<string>}
     * @memberof SelectedFieldInfo
     */
    'fieldPath'?: Array<string>;
}

