/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * ServiceCredentials class for service key authentication. This class is structured similarly to OAuthCredentials but for a different authentication method.
 * @export
 * @interface ServiceKeyAuthentication3
 */
export interface ServiceKeyAuthentication3 {
    /**
     * 
     * @type {string}
     * @memberof ServiceKeyAuthentication3
     */
    'auth_type'?: ServiceKeyAuthentication3AuthTypeEnum;
    /**
     * Tenant ID of the Microsoft OneDrive user
     * @type {string}
     * @memberof ServiceKeyAuthentication3
     */
    'tenant_id': string;
    /**
     * Special characters such as a period, comma, space, and the at sign (@) are converted to underscores (_). More details: https://learn.microsoft.com/en-us/sharepoint/list-onedrive-urls
     * @type {string}
     * @memberof ServiceKeyAuthentication3
     */
    'user_principal_name': string;
    /**
     * Client ID of your Microsoft developer application
     * @type {string}
     * @memberof ServiceKeyAuthentication3
     */
    'client_id': string;
    /**
     * Client Secret of your Microsoft developer application
     * @type {string}
     * @memberof ServiceKeyAuthentication3
     */
    'client_secret': string;
}

export const ServiceKeyAuthentication3AuthTypeEnum = {
    SERVICE: 'Service'
} as const;

export type ServiceKeyAuthentication3AuthTypeEnum = typeof ServiceKeyAuthentication3AuthTypeEnum[keyof typeof ServiceKeyAuthentication3AuthTypeEnum];


