/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Use service name
 * @export
 * @interface ServiceName
 */
export interface ServiceName {
    /**
     * 
     * @type {string}
     * @memberof ServiceName
     */
    'connection_type'?: ServiceNameConnectionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ServiceName
     */
    'service_name': string;
}

export const ServiceNameConnectionTypeEnum = {
    SERVICE_NAME: 'service_name'
} as const;

export type ServiceNameConnectionTypeEnum = typeof ServiceNameConnectionTypeEnum[keyof typeof ServiceNameConnectionTypeEnum];


