/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Server-managed object storage
 * @export
 * @interface ServerManaged
 */
export interface ServerManaged {
    /**
     * 
     * @type {string}
     * @memberof ServerManaged
     */
    'storage_type': ServerManagedStorageTypeEnum;
    /**
     * The name of the managed warehouse
     * @type {string}
     * @memberof ServerManaged
     */
    'managed_warehouse_name': string;
}

export const ServerManagedStorageTypeEnum = {
    MANAGED: 'MANAGED'
} as const;

export type ServerManagedStorageTypeEnum = typeof ServerManagedStorageTypeEnum[keyof typeof ServerManagedStorageTypeEnum];


