/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * For these scenario user should obtain service account\'s credentials from the Google API Console and provide delegated email.
 * @export
 * @interface ServiceAccountKey1
 */
export interface ServiceAccountKey1 {
    /**
     * Authentication Scenario
     * @type {string}
     * @memberof ServiceAccountKey1
     */
    'credentials_title'?: ServiceAccountKey1CredentialsTitleEnum;
    /**
     * The contents of the JSON service account key. See the <a href=\"https://developers.google.com/admin-sdk/directory/v1/guides/delegation\">docs</a> for more information on how to generate this key.
     * @type {string}
     * @memberof ServiceAccountKey1
     */
    'credentials_json': string;
    /**
     * The email of the user, which has permissions to access the Google Workspace Admin APIs.
     * @type {string}
     * @memberof ServiceAccountKey1
     */
    'email': string;
}

export const ServiceAccountKey1CredentialsTitleEnum = {
    SERVICE_ACCOUNTS: 'Service accounts'
} as const;

export type ServiceAccountKey1CredentialsTitleEnum = typeof ServiceAccountKey1CredentialsTitleEnum[keyof typeof ServiceAccountKey1CredentialsTitleEnum];


