/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ServiceAccountKeyAuthentication
 */
export interface ServiceAccountKeyAuthentication {
    /**
     * 
     * @type {string}
     * @memberof ServiceAccountKeyAuthentication
     */
    'auth_type': ServiceAccountKeyAuthenticationAuthTypeEnum;
    /**
     * The JSON key of the service account to use for authorization. Read more <a href=\"https://cloud.google.com/iam/docs/creating-managing-service-account-keys\">here</a>.
     * @type {string}
     * @memberof ServiceAccountKeyAuthentication
     */
    'service_account_info': string;
    /**
     * The email of the user which has permissions to access the Google Workspace Admin APIs.
     * @type {string}
     * @memberof ServiceAccountKeyAuthentication
     */
    'email': string;
}

export const ServiceAccountKeyAuthenticationAuthTypeEnum = {
    SERVICE: 'Service'
} as const;

export type ServiceAccountKeyAuthenticationAuthTypeEnum = typeof ServiceAccountKeyAuthenticationAuthTypeEnum[keyof typeof ServiceAccountKeyAuthenticationAuthTypeEnum];


