/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ServiceAccountKeyAuthentication2
 */
export interface ServiceAccountKeyAuthentication2 {
    /**
     * 
     * @type {string}
     * @memberof ServiceAccountKeyAuthentication2
     */
    'auth_type': ServiceAccountKeyAuthentication2AuthTypeEnum;
    /**
     * The JSON key of the service account to use for authorization. Read more <a href=\"https://cloud.google.com/iam/docs/creating-managing-service-account-keys#creating_service_account_keys\">here</a>.
     * @type {string}
     * @memberof ServiceAccountKeyAuthentication2
     */
    'service_account_info': string;
}

export const ServiceAccountKeyAuthentication2AuthTypeEnum = {
    SERVICE: 'Service'
} as const;

export type ServiceAccountKeyAuthentication2AuthTypeEnum = typeof ServiceAccountKeyAuthentication2AuthTypeEnum[keyof typeof ServiceAccountKeyAuthentication2AuthTypeEnum];


