/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * For these scenario user only needs to give permission to read Google Directory data.
 * @export
 * @interface SignInViaGoogleOAuth
 */
export interface SignInViaGoogleOAuth {
    /**
     * Authentication Scenario
     * @type {string}
     * @memberof SignInViaGoogleOAuth
     */
    'credentials_title'?: SignInViaGoogleOAuthCredentialsTitleEnum;
    /**
     * The Client ID of the developer application.
     * @type {string}
     * @memberof SignInViaGoogleOAuth
     */
    'client_id': string;
    /**
     * The Client Secret of the developer application.
     * @type {string}
     * @memberof SignInViaGoogleOAuth
     */
    'client_secret': string;
    /**
     * The Token for obtaining a new access token.
     * @type {string}
     * @memberof SignInViaGoogleOAuth
     */
    'refresh_token': string;
}

export const SignInViaGoogleOAuthCredentialsTitleEnum = {
    WEB_SERVER_APP: 'Web server app'
} as const;

export type SignInViaGoogleOAuthCredentialsTitleEnum = typeof SignInViaGoogleOAuthCredentialsTitleEnum[keyof typeof SignInViaGoogleOAuthCredentialsTitleEnum];


