/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Silent
 */
export interface Silent {
    /**
     * 
     * @type {string}
     * @memberof Silent
     */
    'test_destination_type': SilentTestDestinationTypeEnum;
}

export const SilentTestDestinationTypeEnum = {
    SILENT: 'SILENT'
} as const;

export type SilentTestDestinationTypeEnum = typeof SilentTestDestinationTypeEnum[keyof typeof SilentTestDestinationTypeEnum];


