/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SmartsheetsCredentials
 */
export interface SmartsheetsCredentials {
    /**
     * The API ID of the SmartSheets developer application.
     * @type {string}
     * @memberof SmartsheetsCredentials
     */
    'client_id'?: string;
    /**
     * The API Secret the SmartSheets developer application.
     * @type {string}
     * @memberof SmartsheetsCredentials
     */
    'client_secret'?: string;
}

