/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Credentials6 } from './credentials6';

/**
 * Snowflake can be used to store vector data and retrieve embeddings.
 * @export
 * @interface SnowflakeConnection
 */
export interface SnowflakeConnection {
    /**
     * Enter the account name you want to use to access the database. This is usually the identifier before .snowflakecomputing.com
     * @type {string}
     * @memberof SnowflakeConnection
     */
    'host': string;
    /**
     * Enter the role that you want to use to access Snowflake
     * @type {string}
     * @memberof SnowflakeConnection
     */
    'role': string;
    /**
     * Enter the name of the warehouse that you want to use as a compute cluster
     * @type {string}
     * @memberof SnowflakeConnection
     */
    'warehouse': string;
    /**
     * Enter the name of the database that you want to sync data into
     * @type {string}
     * @memberof SnowflakeConnection
     */
    'database': string;
    /**
     * Enter the name of the default schema
     * @type {string}
     * @memberof SnowflakeConnection
     */
    'default_schema': string;
    /**
     * Enter the name of the user you want to use to access the database
     * @type {string}
     * @memberof SnowflakeConnection
     */
    'username': string;
    /**
     * 
     * @type {Credentials6}
     * @memberof SnowflakeConnection
     */
    'credentials': Credentials6;
}

