/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceFaker
 */
export interface SourceFaker {
    /**
     * How many users should be generated in total. The purchases table will be scaled to match, with 10 purchases created per 10 users. This setting does not apply to the products stream.
     * @type {number}
     * @memberof SourceFaker
     */
    'count'?: number;
    /**
     * Manually control the faker random seed to return the same values on subsequent runs (leave -1 for random)
     * @type {number}
     * @memberof SourceFaker
     */
    'seed'?: number;
    /**
     * How many fake records will be in each page (stream slice), before a state message is emitted?
     * @type {number}
     * @memberof SourceFaker
     */
    'records_per_slice'?: number;
    /**
     * Should the updated_at values for every record be new each sync?  Setting this to false will case the source to stop emitting records after COUNT records have been emitted.
     * @type {boolean}
     * @memberof SourceFaker
     */
    'always_updated'?: boolean;
    /**
     * How many parallel workers should we use to generate fake data?  Choose a value equal to the number of CPUs you will allocate to this source.
     * @type {number}
     * @memberof SourceFaker
     */
    'parallelism'?: number;
    /**
     * 
     * @type {string}
     * @memberof SourceFaker
     */
    'sourceType': SourceFakerSourceTypeEnum;
}

export const SourceFakerSourceTypeEnum = {
    FAKER: 'faker'
} as const;

export type SourceFakerSourceTypeEnum = typeof SourceFakerSourceTypeEnum[keyof typeof SourceFakerSourceTypeEnum];


