/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceShortcut
 */
export interface SourceShortcut {
    /**
     * 
     * @type {string}
     * @memberof SourceShortcut
     */
    'api_key_2': string;
    /**
     * 
     * @type {string}
     * @memberof SourceShortcut
     */
    'start_date': string;
    /**
     * Query for searching as defined in `https://help.shortcut.com/hc/en-us/articles/360000046646-Searching-in-Shortcut-Using-Search-Operators`
     * @type {string}
     * @memberof SourceShortcut
     */
    'query'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceShortcut
     */
    'sourceType': SourceShortcutSourceTypeEnum;
}

export const SourceShortcutSourceTypeEnum = {
    SHORTCUT: 'shortcut'
} as const;

export type SourceShortcutSourceTypeEnum = typeof SourceShortcutSourceTypeEnum[keyof typeof SourceShortcutSourceTypeEnum];


