/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceDatadogQueriesInner
 */
export interface SourceDatadogQueriesInner {
    /**
     * The variable name for use in queries.
     * @type {string}
     * @memberof SourceDatadogQueriesInner
     */
    'name': string;
    /**
     * A classic query string.
     * @type {string}
     * @memberof SourceDatadogQueriesInner
     */
    'query': string;
    /**
     * A data source that is powered by the platform.
     * @type {string}
     * @memberof SourceDatadogQueriesInner
     */
    'data_source': SourceDatadogQueriesInnerDataSourceEnum;
}

export const SourceDatadogQueriesInnerDataSourceEnum = {
    METRICS: 'metrics',
    CLOUD_COST: 'cloud_cost',
    LOGS: 'logs',
    RUM: 'rum'
} as const;

export type SourceDatadogQueriesInnerDataSourceEnum = typeof SourceDatadogQueriesInnerDataSourceEnum[keyof typeof SourceDatadogQueriesInnerDataSourceEnum];


