/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceMailgun
 */
export interface SourceMailgun {
    /**
     * Primary account API key to access your Mailgun data.
     * @type {string}
     * @memberof SourceMailgun
     */
    'private_key': string;
    /**
     * Domain region code. \'EU\' or \'US\' are possible values. The default is \'US\'.
     * @type {string}
     * @memberof SourceMailgun
     */
    'domain_region'?: SourceMailgunDomainRegionEnum;
    /**
     * UTC date and time in the format 2020-10-01 00:00:00. Any data before this date will not be replicated. If omitted, defaults to 3 days ago.
     * @type {string}
     * @memberof SourceMailgun
     */
    'start_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceMailgun
     */
    'sourceType': SourceMailgunSourceTypeEnum;
}

export const SourceMailgunDomainRegionEnum = {
    US: 'US',
    EU: 'EU'
} as const;

export type SourceMailgunDomainRegionEnum = typeof SourceMailgunDomainRegionEnum[keyof typeof SourceMailgunDomainRegionEnum];
export const SourceMailgunSourceTypeEnum = {
    MAILGUN: 'mailgun'
} as const;

export type SourceMailgunSourceTypeEnum = typeof SourceMailgunSourceTypeEnum[keyof typeof SourceMailgunSourceTypeEnum];


