/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceBigqueryUpdate
 */
export interface SourceBigqueryUpdate {
    /**
     * The GCP project ID for the project containing the target BigQuery dataset.
     * @type {string}
     * @memberof SourceBigqueryUpdate
     */
    'project_id': string;
    /**
     * The dataset ID to search for tables and views. If you are only loading data from one dataset, setting this option could result in much faster schema discovery.
     * @type {string}
     * @memberof SourceBigqueryUpdate
     */
    'dataset_id'?: string;
    /**
     * The contents of your Service Account Key JSON file. See the <a href=\"https://docs.airbyte.com/integrations/sources/bigquery#setup-the-bigquery-source-in-airbyte\">docs</a> for more information on how to obtain this key.
     * @type {string}
     * @memberof SourceBigqueryUpdate
     */
    'credentials_json': string;
}

