/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FileBasedStreamConfig3 } from './file-based-stream-config3';

/**
 * NOTE: When this Spec is changed, legacy_config_transformer.py must also be modified to uptake the changes because it is responsible for converting legacy GCS configs into file based configs using the File-Based CDK.
 * @export
 * @interface SourceGcs
 */
export interface SourceGcs {
    /**
     * UTC date and time in the format 2017-01-25T00:00:00.000000Z. Any file modified before this date will not be replicated.
     * @type {string}
     * @memberof SourceGcs
     */
    'start_date'?: string;
    /**
     * Each instance of this configuration defines a <a href=\"https://docs.airbyte.com/cloud/core-concepts#stream\">stream</a>. Use this to define which files belong in the stream, their format, and how they should be parsed and validated. When sending data to warehouse destination such as Snowflake or BigQuery, each stream is a separate table.
     * @type {Array<FileBasedStreamConfig3>}
     * @memberof SourceGcs
     */
    'streams': Array<FileBasedStreamConfig3>;
    /**
     * Enter your Google Cloud <a href=\"https://cloud.google.com/iam/docs/creating-managing-service-account-keys#creating_service_account_keys\">service account key</a> in JSON format
     * @type {string}
     * @memberof SourceGcs
     */
    'service_account': string;
    /**
     * Name of the GCS bucket where the file(s) exist.
     * @type {string}
     * @memberof SourceGcs
     */
    'bucket': string;
    /**
     * 
     * @type {string}
     * @memberof SourceGcs
     */
    'sourceType': SourceGcsSourceTypeEnum;
}

export const SourceGcsSourceTypeEnum = {
    GCS: 'gcs'
} as const;

export type SourceGcsSourceTypeEnum = typeof SourceGcsSourceTypeEnum[keyof typeof SourceGcsSourceTypeEnum];


