/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceSapFieldglass
 */
export interface SourceSapFieldglass {
    /**
     * API Key
     * @type {string}
     * @memberof SourceSapFieldglass
     */
    'api_key': string;
    /**
     * 
     * @type {string}
     * @memberof SourceSapFieldglass
     */
    'sourceType': SourceSapFieldglassSourceTypeEnum;
}

export const SourceSapFieldglassSourceTypeEnum = {
    SAP_FIELDGLASS: 'sap-fieldglass'
} as const;

export type SourceSapFieldglassSourceTypeEnum = typeof SourceSapFieldglassSourceTypeEnum[keyof typeof SourceSapFieldglassSourceTypeEnum];


