/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Credentials1 } from './credentials1';

/**
 * 
 * @export
 * @interface SourceSalesloftUpdate
 */
export interface SourceSalesloftUpdate {
    /**
     * 
     * @type {Credentials1}
     * @memberof SourceSalesloftUpdate
     */
    'credentials': Credentials1;
    /**
     * The date from which you\'d like to replicate data for Salesloft API, in the format YYYY-MM-DDT00:00:00Z. All data generated after this date will be replicated.
     * @type {string}
     * @memberof SourceSalesloftUpdate
     */
    'start_date': string;
}

