/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceSnapchatMarketing
 */
export interface SourceSnapchatMarketing {
    /**
     * The Client ID of your Snapchat developer application.
     * @type {string}
     * @memberof SourceSnapchatMarketing
     */
    'client_id': string;
    /**
     * The Client Secret of your Snapchat developer application.
     * @type {string}
     * @memberof SourceSnapchatMarketing
     */
    'client_secret': string;
    /**
     * Refresh Token to renew the expired Access Token.
     * @type {string}
     * @memberof SourceSnapchatMarketing
     */
    'refresh_token': string;
    /**
     * Date in the format 2022-01-01. Any data before this date will not be replicated.
     * @type {string}
     * @memberof SourceSnapchatMarketing
     */
    'start_date'?: string;
    /**
     * Date in the format 2017-01-25. Any data after this date will not be replicated.
     * @type {string}
     * @memberof SourceSnapchatMarketing
     */
    'end_date'?: string;
    /**
     * Specifies the principle for conversion reporting.
     * @type {string}
     * @memberof SourceSnapchatMarketing
     */
    'action_report_time'?: SourceSnapchatMarketingActionReportTimeEnum;
    /**
     * Attribution window for swipe ups.
     * @type {string}
     * @memberof SourceSnapchatMarketing
     */
    'swipe_up_attribution_window'?: SourceSnapchatMarketingSwipeUpAttributionWindowEnum;
    /**
     * Attribution window for views.
     * @type {string}
     * @memberof SourceSnapchatMarketing
     */
    'view_attribution_window'?: SourceSnapchatMarketingViewAttributionWindowEnum;
    /**
     * 
     * @type {string}
     * @memberof SourceSnapchatMarketing
     */
    'sourceType': SourceSnapchatMarketingSourceTypeEnum;
}

export const SourceSnapchatMarketingActionReportTimeEnum = {
    CONVERSION: 'conversion',
    IMPRESSION: 'impression'
} as const;

export type SourceSnapchatMarketingActionReportTimeEnum = typeof SourceSnapchatMarketingActionReportTimeEnum[keyof typeof SourceSnapchatMarketingActionReportTimeEnum];
export const SourceSnapchatMarketingSwipeUpAttributionWindowEnum = {
    _1_DAY: '1_DAY',
    _7_DAY: '7_DAY',
    _28_DAY: '28_DAY'
} as const;

export type SourceSnapchatMarketingSwipeUpAttributionWindowEnum = typeof SourceSnapchatMarketingSwipeUpAttributionWindowEnum[keyof typeof SourceSnapchatMarketingSwipeUpAttributionWindowEnum];
export const SourceSnapchatMarketingViewAttributionWindowEnum = {
    _1_HOUR: '1_HOUR',
    _3_HOUR: '3_HOUR',
    _6_HOUR: '6_HOUR',
    _1_DAY: '1_DAY',
    _7_DAY: '7_DAY'
} as const;

export type SourceSnapchatMarketingViewAttributionWindowEnum = typeof SourceSnapchatMarketingViewAttributionWindowEnum[keyof typeof SourceSnapchatMarketingViewAttributionWindowEnum];
export const SourceSnapchatMarketingSourceTypeEnum = {
    SNAPCHAT_MARKETING: 'snapchat-marketing'
} as const;

export type SourceSnapchatMarketingSourceTypeEnum = typeof SourceSnapchatMarketingSourceTypeEnum[keyof typeof SourceSnapchatMarketingSourceTypeEnum];


