/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceBeamer
 */
export interface SourceBeamer {
    /**
     * 
     * @type {string}
     * @memberof SourceBeamer
     */
    'api_key': string;
    /**
     * 
     * @type {string}
     * @memberof SourceBeamer
     */
    'start_date': string;
    /**
     * 
     * @type {string}
     * @memberof SourceBeamer
     */
    'sourceType': SourceBeamerSourceTypeEnum;
}

export const SourceBeamerSourceTypeEnum = {
    BEAMER: 'beamer'
} as const;

export type SourceBeamerSourceTypeEnum = typeof SourceBeamerSourceTypeEnum[keyof typeof SourceBeamerSourceTypeEnum];


