/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceFront
 */
export interface SourceFront {
    /**
     * 
     * @type {string}
     * @memberof SourceFront
     */
    'api_key': string;
    /**
     * 
     * @type {string}
     * @memberof SourceFront
     */
    'start_date': string;
    /**
     * Page limit for the responses
     * @type {string}
     * @memberof SourceFront
     */
    'page_limit'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceFront
     */
    'sourceType': SourceFrontSourceTypeEnum;
}

export const SourceFrontSourceTypeEnum = {
    FRONT: 'front'
} as const;

export type SourceFrontSourceTypeEnum = typeof SourceFrontSourceTypeEnum[keyof typeof SourceFrontSourceTypeEnum];


