/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourcePersistiq
 */
export interface SourcePersistiq {
    /**
     * PersistIq API Key. See the <a href=\"https://apidocs.persistiq.com/#authentication\">docs</a> for more information on where to find that key.
     * @type {string}
     * @memberof SourcePersistiq
     */
    'api_key': string;
    /**
     * 
     * @type {string}
     * @memberof SourcePersistiq
     */
    'sourceType': SourcePersistiqSourceTypeEnum;
}

export const SourcePersistiqSourceTypeEnum = {
    PERSISTIQ: 'persistiq'
} as const;

export type SourcePersistiqSourceTypeEnum = typeof SourcePersistiqSourceTypeEnum[keyof typeof SourcePersistiqSourceTypeEnum];


