/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourcePexelsApiUpdate
 */
export interface SourcePexelsApiUpdate {
    /**
     * API key is required to access pexels api, For getting your\'s goto https://www.pexels.com/api/documentation and create account for free.
     * @type {string}
     * @memberof SourcePexelsApiUpdate
     */
    'api_key': string;
    /**
     * Optional, Desired photo color. Supported colors red, orange, yellow, green, turquoise, blue, violet, pink, brown, black, gray, white or any hexidecimal color code.
     * @type {string}
     * @memberof SourcePexelsApiUpdate
     */
    'color'?: string;
    /**
     * Optional, The locale of the search you are performing. The current supported locales are \'en-US\' \'pt-BR\' \'es-ES\' \'ca-ES\' \'de-DE\' \'it-IT\' \'fr-FR\' \'sv-SE\' \'id-ID\' \'pl-PL\' \'ja-JP\' \'zh-TW\' \'zh-CN\' \'ko-KR\' \'th-TH\' \'nl-NL\' \'hu-HU\' \'vi-VN\' \'cs-CZ\' \'da-DK\' \'fi-FI\' \'uk-UA\' \'el-GR\' \'ro-RO\' \'nb-NO\' \'sk-SK\' \'tr-TR\' \'ru-RU\'.
     * @type {string}
     * @memberof SourcePexelsApiUpdate
     */
    'locale'?: string;
    /**
     * Optional, Desired photo orientation. The current supported orientations are landscape, portrait or square
     * @type {string}
     * @memberof SourcePexelsApiUpdate
     */
    'orientation'?: string;
    /**
     * Optional, the search query, Example Ocean, Tigers, Pears, etc.
     * @type {string}
     * @memberof SourcePexelsApiUpdate
     */
    'query': string;
    /**
     * Optional, Minimum photo size. The current supported sizes are large(24MP), medium(12MP) or small(4MP).
     * @type {string}
     * @memberof SourcePexelsApiUpdate
     */
    'size'?: string;
}

