/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceGoogleWebfontsUpdate
 */
export interface SourceGoogleWebfontsUpdate {
    /**
     * API key is required to access google apis, For getting your\'s goto google console and generate api key for Webfonts
     * @type {string}
     * @memberof SourceGoogleWebfontsUpdate
     */
    'api_key': string;
    /**
     * Optional, Available params- json, media, proto
     * @type {string}
     * @memberof SourceGoogleWebfontsUpdate
     */
    'alt'?: string;
    /**
     * Optional, boolean type
     * @type {string}
     * @memberof SourceGoogleWebfontsUpdate
     */
    'prettyPrint'?: string;
    /**
     * Optional, to find how to sort
     * @type {string}
     * @memberof SourceGoogleWebfontsUpdate
     */
    'sort'?: string;
}

