/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Collection } from './collection';

/**
 * 
 * @export
 * @interface SourceFauna
 */
export interface SourceFauna {
    /**
     * Domain of Fauna to query. Defaults db.fauna.com. See <a href=https://docs.fauna.com/fauna/current/learn/understanding/region_groups#how-to-use-region-groups>the docs</a>.
     * @type {string}
     * @memberof SourceFauna
     */
    'domain': string;
    /**
     * Endpoint port.
     * @type {number}
     * @memberof SourceFauna
     */
    'port': number;
    /**
     * URL scheme.
     * @type {string}
     * @memberof SourceFauna
     */
    'scheme': string;
    /**
     * Fauna secret, used when authenticating with the database.
     * @type {string}
     * @memberof SourceFauna
     */
    'secret': string;
    /**
     * 
     * @type {Collection}
     * @memberof SourceFauna
     */
    'collection'?: Collection;
    /**
     * 
     * @type {string}
     * @memberof SourceFauna
     */
    'sourceType': SourceFaunaSourceTypeEnum;
}

export const SourceFaunaSourceTypeEnum = {
    FAUNA: 'fauna'
} as const;

export type SourceFaunaSourceTypeEnum = typeof SourceFaunaSourceTypeEnum[keyof typeof SourceFaunaSourceTypeEnum];


