/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceAppfigures
 */
export interface SourceAppfigures {
    /**
     * 
     * @type {string}
     * @memberof SourceAppfigures
     */
    'api_key': string;
    /**
     * The store which needs to be searched in streams
     * @type {string}
     * @memberof SourceAppfigures
     */
    'search_store'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceAppfigures
     */
    'start_date': string;
    /**
     * Category term for grouping the search results
     * @type {string}
     * @memberof SourceAppfigures
     */
    'group_by'?: SourceAppfiguresGroupByEnum;
    /**
     * 
     * @type {string}
     * @memberof SourceAppfigures
     */
    'sourceType': SourceAppfiguresSourceTypeEnum;
}

export const SourceAppfiguresGroupByEnum = {
    NETWORK: 'network',
    PRODUCT: 'product',
    COUNTRY: 'country',
    DATE: 'date'
} as const;

export type SourceAppfiguresGroupByEnum = typeof SourceAppfiguresGroupByEnum[keyof typeof SourceAppfiguresGroupByEnum];
export const SourceAppfiguresSourceTypeEnum = {
    APPFIGURES: 'appfigures'
} as const;

export type SourceAppfiguresSourceTypeEnum = typeof SourceAppfiguresSourceTypeEnum[keyof typeof SourceAppfiguresSourceTypeEnum];


