/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceKissmetrics
 */
export interface SourceKissmetrics {
    /**
     * 
     * @type {string}
     * @memberof SourceKissmetrics
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof SourceKissmetrics
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceKissmetrics
     */
    'sourceType': SourceKissmetricsSourceTypeEnum;
}

export const SourceKissmetricsSourceTypeEnum = {
    KISSMETRICS: 'kissmetrics'
} as const;

export type SourceKissmetricsSourceTypeEnum = typeof SourceKissmetricsSourceTypeEnum[keyof typeof SourceKissmetricsSourceTypeEnum];


