/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceFirebolt
 */
export interface SourceFirebolt {
    /**
     * Firebolt service account ID.
     * @type {string}
     * @memberof SourceFirebolt
     */
    'client_id': string;
    /**
     * Firebolt secret, corresponding to the service account ID.
     * @type {string}
     * @memberof SourceFirebolt
     */
    'client_secret': string;
    /**
     * Firebolt account to login.
     * @type {string}
     * @memberof SourceFirebolt
     */
    'account': string;
    /**
     * The host name of your Firebolt database.
     * @type {string}
     * @memberof SourceFirebolt
     */
    'host'?: string;
    /**
     * The database to connect to.
     * @type {string}
     * @memberof SourceFirebolt
     */
    'database': string;
    /**
     * Engine name to connect to.
     * @type {string}
     * @memberof SourceFirebolt
     */
    'engine': string;
    /**
     * 
     * @type {string}
     * @memberof SourceFirebolt
     */
    'sourceType': SourceFireboltSourceTypeEnum;
}

export const SourceFireboltSourceTypeEnum = {
    FIREBOLT: 'firebolt'
} as const;

export type SourceFireboltSourceTypeEnum = typeof SourceFireboltSourceTypeEnum[keyof typeof SourceFireboltSourceTypeEnum];


