/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceRecruitee
 */
export interface SourceRecruitee {
    /**
     * Recruitee API Key. See <a href=\"https://docs.recruitee.com/reference/getting-started#generate-api-token\">here</a>.
     * @type {string}
     * @memberof SourceRecruitee
     */
    'api_key': string;
    /**
     * Recruitee Company ID. You can also find this ID on the <a href=\"https://app.recruitee.com/#/settings/api_tokens\">Recruitee API tokens page</a>.
     * @type {number}
     * @memberof SourceRecruitee
     */
    'company_id': number;
    /**
     * 
     * @type {string}
     * @memberof SourceRecruitee
     */
    'sourceType': SourceRecruiteeSourceTypeEnum;
}

export const SourceRecruiteeSourceTypeEnum = {
    RECRUITEE: 'recruitee'
} as const;

export type SourceRecruiteeSourceTypeEnum = typeof SourceRecruiteeSourceTypeEnum[keyof typeof SourceRecruiteeSourceTypeEnum];


