/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceClickupApiUpdate
 */
export interface SourceClickupApiUpdate {
    /**
     * Every ClickUp API call required authentication. This field is your personal API token. See <a href=\"https://clickup.com/api/developer-portal/authentication/#personal-token\">here</a>.
     * @type {string}
     * @memberof SourceClickupApiUpdate
     */
    'api_token': string;
    /**
     * Include or exclude closed tasks. By default, they are excluded. See <a https://clickup.com/api/clickupreference/operation/GetTasks/#!in=query&path=include_closed&t=request\">here</a>.
     * @type {boolean}
     * @memberof SourceClickupApiUpdate
     */
    'include_closed_tasks'?: boolean;
}

