/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceYotpo
 */
export interface SourceYotpo {
    /**
     * Access token recieved as a result of API call to https://api.yotpo.com/oauth/token (Ref- https://apidocs.yotpo.com/reference/yotpo-authentication)
     * @type {string}
     * @memberof SourceYotpo
     */
    'access_token': string;
    /**
     * App key found at settings (Ref- https://settings.yotpo.com/#/general_settings)
     * @type {string}
     * @memberof SourceYotpo
     */
    'app_key': string;
    /**
     * Date time filter for incremental filter, Specify which date to extract from.
     * @type {string}
     * @memberof SourceYotpo
     */
    'start_date': string;
    /**
     * Email address registered with yotpo.
     * @type {string}
     * @memberof SourceYotpo
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof SourceYotpo
     */
    'sourceType': SourceYotpoSourceTypeEnum;
}

export const SourceYotpoSourceTypeEnum = {
    YOTPO: 'yotpo'
} as const;

export type SourceYotpoSourceTypeEnum = typeof SourceYotpoSourceTypeEnum[keyof typeof SourceYotpoSourceTypeEnum];


