/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceCoda
 */
export interface SourceCoda {
    /**
     * Bearer token
     * @type {string}
     * @memberof SourceCoda
     */
    'auth_token': string;
    /**
     * 
     * @type {string}
     * @memberof SourceCoda
     */
    'sourceType': SourceCodaSourceTypeEnum;
}

export const SourceCodaSourceTypeEnum = {
    CODA: 'coda'
} as const;

export type SourceCodaSourceTypeEnum = typeof SourceCodaSourceTypeEnum[keyof typeof SourceCodaSourceTypeEnum];


