/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceBraze
 */
export interface SourceBraze {
    /**
     * Braze REST API endpoint
     * @type {string}
     * @memberof SourceBraze
     */
    'url': string;
    /**
     * Braze REST API key
     * @type {string}
     * @memberof SourceBraze
     */
    'api_key': string;
    /**
     * Rows after this date will be synced
     * @type {string}
     * @memberof SourceBraze
     */
    'start_date': string;
    /**
     * 
     * @type {string}
     * @memberof SourceBraze
     */
    'sourceType': SourceBrazeSourceTypeEnum;
}

export const SourceBrazeSourceTypeEnum = {
    BRAZE: 'braze'
} as const;

export type SourceBrazeSourceTypeEnum = typeof SourceBrazeSourceTypeEnum[keyof typeof SourceBrazeSourceTypeEnum];


