/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceMetabaseUpdate
 */
export interface SourceMetabaseUpdate {
    /**
     * URL to your metabase instance API
     * @type {string}
     * @memberof SourceMetabaseUpdate
     */
    'instance_api_url': string;
    /**
     * 
     * @type {string}
     * @memberof SourceMetabaseUpdate
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof SourceMetabaseUpdate
     */
    'password'?: string;
    /**
     * To generate your session token, you need to run the following command: ``` curl -X POST \\   -H \"Content-Type: application/json\" \\   -d \'{\"username\": \"person@metabase.com\", \"password\": \"fakepassword\"}\' \\   http://localhost:3000/api/session ``` Then copy the value of the `id` field returned by a successful call to that API. Note that by default, sessions are good for 14 days and needs to be regenerated.
     * @type {string}
     * @memberof SourceMetabaseUpdate
     */
    'session_token'?: string;
}

