/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceGlassfrog
 */
export interface SourceGlassfrog {
    /**
     * API key provided by Glassfrog
     * @type {string}
     * @memberof SourceGlassfrog
     */
    'api_key': string;
    /**
     * 
     * @type {string}
     * @memberof SourceGlassfrog
     */
    'sourceType': SourceGlassfrogSourceTypeEnum;
}

export const SourceGlassfrogSourceTypeEnum = {
    GLASSFROG: 'glassfrog'
} as const;

export type SourceGlassfrogSourceTypeEnum = typeof SourceGlassfrogSourceTypeEnum[keyof typeof SourceGlassfrogSourceTypeEnum];


