/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Authentication30 } from './authentication30';

/**
 * 
 * @export
 * @interface SourceSftp
 */
export interface SourceSftp {
    /**
     * The server user
     * @type {string}
     * @memberof SourceSftp
     */
    'user': string;
    /**
     * The server host address
     * @type {string}
     * @memberof SourceSftp
     */
    'host': string;
    /**
     * The server port
     * @type {number}
     * @memberof SourceSftp
     */
    'port': number;
    /**
     * 
     * @type {Authentication30}
     * @memberof SourceSftp
     */
    'credentials'?: Authentication30;
    /**
     * Coma separated file types. Currently only \'csv\' and \'json\' types are supported.
     * @type {string}
     * @memberof SourceSftp
     */
    'file_types'?: string;
    /**
     * The directory to search files for sync
     * @type {string}
     * @memberof SourceSftp
     */
    'folder_path'?: string;
    /**
     * The regular expression to specify files for sync in a chosen Folder Path
     * @type {string}
     * @memberof SourceSftp
     */
    'file_pattern'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceSftp
     */
    'sourceType': SourceSftpSourceTypeEnum;
}

export const SourceSftpSourceTypeEnum = {
    SFTP: 'sftp'
} as const;

export type SourceSftpSourceTypeEnum = typeof SourceSftpSourceTypeEnum[keyof typeof SourceSftpSourceTypeEnum];


