/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceFleetio
 */
export interface SourceFleetio {
    /**
     * 
     * @type {string}
     * @memberof SourceFleetio
     */
    'api_key': string;
    /**
     * 
     * @type {string}
     * @memberof SourceFleetio
     */
    'account_token': string;
    /**
     * 
     * @type {string}
     * @memberof SourceFleetio
     */
    'sourceType': SourceFleetioSourceTypeEnum;
}

export const SourceFleetioSourceTypeEnum = {
    FLEETIO: 'fleetio'
} as const;

export type SourceFleetioSourceTypeEnum = typeof SourceFleetioSourceTypeEnum[keyof typeof SourceFleetioSourceTypeEnum];


