/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceSalesforceStreamsCriteriaInner
 */
export interface SourceSalesforceStreamsCriteriaInner {
    /**
     * 
     * @type {string}
     * @memberof SourceSalesforceStreamsCriteriaInner
     */
    'criteria': SourceSalesforceStreamsCriteriaInnerCriteriaEnum;
    /**
     * 
     * @type {string}
     * @memberof SourceSalesforceStreamsCriteriaInner
     */
    'value': string;
}

export const SourceSalesforceStreamsCriteriaInnerCriteriaEnum = {
    STARTS_WITH: 'starts with',
    ENDS_WITH: 'ends with',
    CONTAINS: 'contains',
    EXACTS: 'exacts',
    STARTS_NOT_WITH: 'starts not with',
    ENDS_NOT_WITH: 'ends not with',
    NOT_CONTAINS: 'not contains',
    NOT_EXACTS: 'not exacts'
} as const;

export type SourceSalesforceStreamsCriteriaInnerCriteriaEnum = typeof SourceSalesforceStreamsCriteriaInnerCriteriaEnum[keyof typeof SourceSalesforceStreamsCriteriaInnerCriteriaEnum];


