/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthorizationMethod13 } from './authorization-method13';

/**
 * 
 * @export
 * @interface SourceOktaUpdate
 */
export interface SourceOktaUpdate {
    /**
     * 
     * @type {AuthorizationMethod13}
     * @memberof SourceOktaUpdate
     */
    'credentials'?: AuthorizationMethod13;
    /**
     * The Okta domain. See the <a href=\"https://docs.airbyte.com/integrations/sources/okta\">docs</a> for instructions on how to find it.
     * @type {string}
     * @memberof SourceOktaUpdate
     */
    'domain'?: string;
    /**
     * UTC date and time in the format YYYY-MM-DDTHH:MM:SSZ. Any data before this date will not be replicated.
     * @type {string}
     * @memberof SourceOktaUpdate
     */
    'start_date'?: string;
}

