/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceCoinApiUpdate
 */
export interface SourceCoinApiUpdate {
    /**
     * API Key
     * @type {string}
     * @memberof SourceCoinApiUpdate
     */
    'api_key': string;
    /**
     * The environment to use. Either sandbox or production. 
     * @type {string}
     * @memberof SourceCoinApiUpdate
     */
    'environment': SourceCoinApiUpdateEnvironmentEnum;
    /**
     * The symbol ID to use. See the documentation for a list. https://docs.coinapi.io/#list-all-symbols-get 
     * @type {string}
     * @memberof SourceCoinApiUpdate
     */
    'symbol_id': string;
    /**
     * The period to use. See the documentation for a list. https://docs.coinapi.io/#list-all-periods-get
     * @type {string}
     * @memberof SourceCoinApiUpdate
     */
    'period': string;
    /**
     * The start date in ISO 8601 format.
     * @type {string}
     * @memberof SourceCoinApiUpdate
     */
    'start_date': string;
    /**
     * The end date in ISO 8601 format. If not supplied, data will be returned from the start date to the current time, or when the count of result elements reaches its limit. 
     * @type {string}
     * @memberof SourceCoinApiUpdate
     */
    'end_date'?: string;
    /**
     * The maximum number of elements to return. If not supplied, the default is 100. For numbers larger than 100, each 100 items is counted as one request for pricing purposes. Maximum value is 100000. 
     * @type {number}
     * @memberof SourceCoinApiUpdate
     */
    'limit'?: number;
}

export const SourceCoinApiUpdateEnvironmentEnum = {
    SANDBOX: 'sandbox',
    PRODUCTION: 'production'
} as const;

export type SourceCoinApiUpdateEnvironmentEnum = typeof SourceCoinApiUpdateEnvironmentEnum[keyof typeof SourceCoinApiUpdateEnvironmentEnum];


