/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceWoocommerce
 */
export interface SourceWoocommerce {
    /**
     * Customer Key for API in WooCommerce shop
     * @type {string}
     * @memberof SourceWoocommerce
     */
    'api_key': string;
    /**
     * Customer Secret for API in WooCommerce shop
     * @type {string}
     * @memberof SourceWoocommerce
     */
    'api_secret': string;
    /**
     * The name of the store. For https://EXAMPLE.com, the shop name is \'EXAMPLE.com\'.
     * @type {string}
     * @memberof SourceWoocommerce
     */
    'shop': string;
    /**
     * The date you would like to replicate data from. Format: YYYY-MM-DD
     * @type {string}
     * @memberof SourceWoocommerce
     */
    'start_date': string;
    /**
     * 
     * @type {string}
     * @memberof SourceWoocommerce
     */
    'sourceType': SourceWoocommerceSourceTypeEnum;
}

export const SourceWoocommerceSourceTypeEnum = {
    WOOCOMMERCE: 'woocommerce'
} as const;

export type SourceWoocommerceSourceTypeEnum = typeof SourceWoocommerceSourceTypeEnum[keyof typeof SourceWoocommerceSourceTypeEnum];


