/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceLuma
 */
export interface SourceLuma {
    /**
     * Get your API key on lu.ma Calendars dashboard → Settings.
     * @type {string}
     * @memberof SourceLuma
     */
    'api_key': string;
    /**
     * 
     * @type {string}
     * @memberof SourceLuma
     */
    'sourceType': SourceLumaSourceTypeEnum;
}

export const SourceLumaSourceTypeEnum = {
    LUMA: 'luma'
} as const;

export type SourceLumaSourceTypeEnum = typeof SourceLumaSourceTypeEnum[keyof typeof SourceLumaSourceTypeEnum];


