/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthorizationMethod12 } from './authorization-method12';

/**
 * 
 * @export
 * @interface SourceOkta
 */
export interface SourceOkta {
    /**
     * 
     * @type {AuthorizationMethod12}
     * @memberof SourceOkta
     */
    'credentials'?: AuthorizationMethod12;
    /**
     * The Okta domain. See the <a href=\"https://docs.airbyte.com/integrations/sources/okta\">docs</a> for instructions on how to find it.
     * @type {string}
     * @memberof SourceOkta
     */
    'domain'?: string;
    /**
     * UTC date and time in the format YYYY-MM-DDTHH:MM:SSZ. Any data before this date will not be replicated.
     * @type {string}
     * @memberof SourceOkta
     */
    'start_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceOkta
     */
    'sourceType': SourceOktaSourceTypeEnum;
}

export const SourceOktaSourceTypeEnum = {
    OKTA: 'okta'
} as const;

export type SourceOktaSourceTypeEnum = typeof SourceOktaSourceTypeEnum[keyof typeof SourceOktaSourceTypeEnum];


