/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Authentication32 } from './authentication32';
// May contain unused imports in some cases
// @ts-ignore
import type { FileBasedStreamConfig1 } from './file-based-stream-config1';

/**
 * Used during spec; allows the developer to configure the cloud provider specific options that are needed when users configure a file-based source.
 * @export
 * @interface SourceGoogleDrive
 */
export interface SourceGoogleDrive {
    /**
     * UTC date and time in the format 2017-01-25T00:00:00.000000Z. Any file modified before this date will not be replicated.
     * @type {string}
     * @memberof SourceGoogleDrive
     */
    'start_date'?: string;
    /**
     * Each instance of this configuration defines a <a href=\"https://docs.airbyte.com/cloud/core-concepts#stream\">stream</a>. Use this to define which files belong in the stream, their format, and how they should be parsed and validated. When sending data to warehouse destination such as Snowflake or BigQuery, each stream is a separate table.
     * @type {Array<FileBasedStreamConfig1>}
     * @memberof SourceGoogleDrive
     */
    'streams': Array<FileBasedStreamConfig1>;
    /**
     * URL for the folder you want to sync. Using individual streams and glob patterns, it\'s possible to only sync a subset of all files located in the folder.
     * @type {string}
     * @memberof SourceGoogleDrive
     */
    'folder_url': string;
    /**
     * 
     * @type {Authentication32}
     * @memberof SourceGoogleDrive
     */
    'credentials': Authentication32;
    /**
     * 
     * @type {string}
     * @memberof SourceGoogleDrive
     */
    'sourceType': SourceGoogleDriveSourceTypeEnum;
}

export const SourceGoogleDriveSourceTypeEnum = {
    GOOGLE_DRIVE: 'google-drive'
} as const;

export type SourceGoogleDriveSourceTypeEnum = typeof SourceGoogleDriveSourceTypeEnum[keyof typeof SourceGoogleDriveSourceTypeEnum];


