/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceShortioUpdate
 */
export interface SourceShortioUpdate {
    /**
     * 
     * @type {string}
     * @memberof SourceShortioUpdate
     */
    'domain_id': string;
    /**
     * Short.io Secret Key
     * @type {string}
     * @memberof SourceShortioUpdate
     */
    'secret_key': string;
    /**
     * UTC date and time in the format 2017-01-25T00:00:00Z. Any data before this date will not be replicated.
     * @type {string}
     * @memberof SourceShortioUpdate
     */
    'start_date': string;
}

