/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceLaunchdarkly
 */
export interface SourceLaunchdarkly {
    /**
     * Your Access token. See <a href=\"https://apidocs.launchdarkly.com/#section/Overview/Authentication\">here</a>.
     * @type {string}
     * @memberof SourceLaunchdarkly
     */
    'access_token': string;
    /**
     * 
     * @type {string}
     * @memberof SourceLaunchdarkly
     */
    'sourceType': SourceLaunchdarklySourceTypeEnum;
}

export const SourceLaunchdarklySourceTypeEnum = {
    LAUNCHDARKLY: 'launchdarkly'
} as const;

export type SourceLaunchdarklySourceTypeEnum = typeof SourceLaunchdarklySourceTypeEnum[keyof typeof SourceLaunchdarklySourceTypeEnum];


