/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthorizationMethod17 } from './authorization-method17';

/**
 * 
 * @export
 * @interface SourceCartUpdate
 */
export interface SourceCartUpdate {
    /**
     * 
     * @type {AuthorizationMethod17}
     * @memberof SourceCartUpdate
     */
    'credentials'?: AuthorizationMethod17;
    /**
     * The date from which you\'d like to replicate the data
     * @type {string}
     * @memberof SourceCartUpdate
     */
    'start_date': string;
}

