/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SSHTunnelMethod1 } from './sshtunnel-method1';
// May contain unused imports in some cases
// @ts-ignore
import type { SSLModes1 } from './sslmodes1';
// May contain unused imports in some cases
// @ts-ignore
import type { UpdateMethod1 } from './update-method1';

/**
 * 
 * @export
 * @interface SourcePostgresUpdate
 */
export interface SourcePostgresUpdate {
    /**
     * Hostname of the database.
     * @type {string}
     * @memberof SourcePostgresUpdate
     */
    'host': string;
    /**
     * Port of the database.
     * @type {number}
     * @memberof SourcePostgresUpdate
     */
    'port': number;
    /**
     * Name of the database.
     * @type {string}
     * @memberof SourcePostgresUpdate
     */
    'database': string;
    /**
     * The list of schemas (case sensitive) to sync from. Defaults to public.
     * @type {Set<string>}
     * @memberof SourcePostgresUpdate
     */
    'schemas'?: Set<string>;
    /**
     * Username to access the database.
     * @type {string}
     * @memberof SourcePostgresUpdate
     */
    'username': string;
    /**
     * Password associated with the username.
     * @type {string}
     * @memberof SourcePostgresUpdate
     */
    'password'?: string;
    /**
     * Additional properties to pass to the JDBC URL string when connecting to the database formatted as \'key=value\' pairs separated by the symbol \'&\'. (Eg. key1=value1&key2=value2&key3=value3). For more information read about <a href=\"https://jdbc.postgresql.org/documentation/head/connect.html\">JDBC URL parameters</a>.
     * @type {string}
     * @memberof SourcePostgresUpdate
     */
    'jdbc_url_params'?: string;
    /**
     * 
     * @type {SSLModes1}
     * @memberof SourcePostgresUpdate
     */
    'ssl_mode'?: SSLModes1;
    /**
     * 
     * @type {UpdateMethod1}
     * @memberof SourcePostgresUpdate
     */
    'replication_method'?: UpdateMethod1;
    /**
     * 
     * @type {SSHTunnelMethod1}
     * @memberof SourcePostgresUpdate
     */
    'tunnel_method'?: SSHTunnelMethod1;
}

