/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceHeight
 */
export interface SourceHeight {
    /**
     * 
     * @type {string}
     * @memberof SourceHeight
     */
    'api_key': string;
    /**
     * 
     * @type {string}
     * @memberof SourceHeight
     */
    'start_date': string;
    /**
     * Search query to be used with search stream
     * @type {string}
     * @memberof SourceHeight
     */
    'search_query'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceHeight
     */
    'sourceType': SourceHeightSourceTypeEnum;
}

export const SourceHeightSourceTypeEnum = {
    HEIGHT: 'height'
} as const;

export type SourceHeightSourceTypeEnum = typeof SourceHeightSourceTypeEnum[keyof typeof SourceHeightSourceTypeEnum];


