/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceRollbar
 */
export interface SourceRollbar {
    /**
     * 
     * @type {string}
     * @memberof SourceRollbar
     */
    'project_access_token': string;
    /**
     * 
     * @type {string}
     * @memberof SourceRollbar
     */
    'start_date': string;
    /**
     * 
     * @type {string}
     * @memberof SourceRollbar
     */
    'account_access_token': string;
    /**
     * 
     * @type {string}
     * @memberof SourceRollbar
     */
    'sourceType': SourceRollbarSourceTypeEnum;
}

export const SourceRollbarSourceTypeEnum = {
    ROLLBAR: 'rollbar'
} as const;

export type SourceRollbarSourceTypeEnum = typeof SourceRollbarSourceTypeEnum[keyof typeof SourceRollbarSourceTypeEnum];


