/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceWikipediaPageviewsUpdate
 */
export interface SourceWikipediaPageviewsUpdate {
    /**
     * If you want to filter by access method, use one of desktop, mobile-app or mobile-web. If you are interested in pageviews regardless of access method, use all-access.
     * @type {string}
     * @memberof SourceWikipediaPageviewsUpdate
     */
    'access': string;
    /**
     * If you want to filter by agent type, use one of user, automated or spider. If you are interested in pageviews regardless of agent type, use all-agents.
     * @type {string}
     * @memberof SourceWikipediaPageviewsUpdate
     */
    'agent': string;
    /**
     * The title of any article in the specified project. Any spaces should be replaced with underscores. It also should be URI-encoded, so that non-URI-safe characters like %, / or ? are accepted.
     * @type {string}
     * @memberof SourceWikipediaPageviewsUpdate
     */
    'article': string;
    /**
     * The ISO 3166-1 alpha-2 code of a country for which to retrieve top articles.
     * @type {string}
     * @memberof SourceWikipediaPageviewsUpdate
     */
    'country': string;
    /**
     * The date of the last day to include, in YYYYMMDD or YYYYMMDDHH format.
     * @type {string}
     * @memberof SourceWikipediaPageviewsUpdate
     */
    'end': string;
    /**
     * If you want to filter by project, use the domain of any Wikimedia project.
     * @type {string}
     * @memberof SourceWikipediaPageviewsUpdate
     */
    'project': string;
    /**
     * The date of the first day to include, in YYYYMMDD or YYYYMMDDHH format. Also serves as the date to retrieve data for the top articles.
     * @type {string}
     * @memberof SourceWikipediaPageviewsUpdate
     */
    'start': string;
}

