/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceCimisUpdate
 */
export interface SourceCimisUpdate {
    /**
     * 
     * @type {string}
     * @memberof SourceCimisUpdate
     */
    'api_key': string;
    /**
     * 
     * @type {string}
     * @memberof SourceCimisUpdate
     */
    'targets_type': SourceCimisUpdateTargetsTypeEnum;
    /**
     * 
     * @type {Array<any>}
     * @memberof SourceCimisUpdate
     */
    'targets': Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SourceCimisUpdate
     */
    'daily_data_items'?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SourceCimisUpdate
     */
    'hourly_data_items'?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof SourceCimisUpdate
     */
    'start_date': string;
    /**
     * 
     * @type {string}
     * @memberof SourceCimisUpdate
     */
    'end_date': string;
    /**
     * 
     * @type {string}
     * @memberof SourceCimisUpdate
     */
    'unit_of_measure'?: SourceCimisUpdateUnitOfMeasureEnum;
}

export const SourceCimisUpdateTargetsTypeEnum = {
    WSN_STATION_NUMBERS: 'WSN station numbers',
    CALIFORNIA_ZIP_CODES: 'California zip codes',
    DECIMAL_DEGREE_COORDINATES: 'decimal-degree coordinates',
    STREET_ADDRESSES: 'street addresses'
} as const;

export type SourceCimisUpdateTargetsTypeEnum = typeof SourceCimisUpdateTargetsTypeEnum[keyof typeof SourceCimisUpdateTargetsTypeEnum];
export const SourceCimisUpdateUnitOfMeasureEnum = {
    E: 'E',
    M: 'M'
} as const;

export type SourceCimisUpdateUnitOfMeasureEnum = typeof SourceCimisUpdateUnitOfMeasureEnum[keyof typeof SourceCimisUpdateUnitOfMeasureEnum];


