/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthorizationMethod14 } from './authorization-method14';

/**
 * 
 * @export
 * @interface SourceTypeform
 */
export interface SourceTypeform {
    /**
     * 
     * @type {AuthorizationMethod14}
     * @memberof SourceTypeform
     */
    'credentials': AuthorizationMethod14;
    /**
     * The date from which you\'d like to replicate data for Typeform API, in the format YYYY-MM-DDT00:00:00Z. All data generated after this date will be replicated.
     * @type {string}
     * @memberof SourceTypeform
     */
    'start_date'?: string;
    /**
     * When this parameter is set, the connector will replicate data only from the input forms. Otherwise, all forms in your Typeform account will be replicated. You can find form IDs in your form URLs. For example, in the URL \"https://mysite.typeform.com/to/u6nXL7\" the form_id is u6nXL7. You can find form URLs on Share panel
     * @type {Set<string>}
     * @memberof SourceTypeform
     */
    'form_ids'?: Set<string>;
    /**
     * 
     * @type {string}
     * @memberof SourceTypeform
     */
    'sourceType': SourceTypeformSourceTypeEnum;
}

export const SourceTypeformSourceTypeEnum = {
    TYPEFORM: 'typeform'
} as const;

export type SourceTypeformSourceTypeEnum = typeof SourceTypeformSourceTypeEnum[keyof typeof SourceTypeformSourceTypeEnum];


