/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthorizationMethod1 } from './authorization-method1';

/**
 * 
 * @export
 * @interface SourceZendeskChatUpdate
 */
export interface SourceZendeskChatUpdate {
    /**
     * The date from which you\'d like to replicate data for Zendesk Chat API, in the format YYYY-MM-DDT00:00:00Z.
     * @type {string}
     * @memberof SourceZendeskChatUpdate
     */
    'start_date': string;
    /**
     * Required if you access Zendesk Chat from a Zendesk Support subdomain.
     * @type {string}
     * @memberof SourceZendeskChatUpdate
     */
    'subdomain'?: string;
    /**
     * 
     * @type {AuthorizationMethod1}
     * @memberof SourceZendeskChatUpdate
     */
    'credentials'?: AuthorizationMethod1;
}

