/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourcePiwikUpdate
 */
export interface SourcePiwikUpdate {
    /**
     * 
     * @type {string}
     * @memberof SourcePiwikUpdate
     */
    'client_id': string;
    /**
     * 
     * @type {string}
     * @memberof SourcePiwikUpdate
     */
    'client_secret': string;
    /**
     * The organization id appearing at URL of your piwik website
     * @type {string}
     * @memberof SourcePiwikUpdate
     */
    'organization_id': string;
}

