/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceKyve
 */
export interface SourceKyve {
    /**
     * The IDs of the KYVE storage pool you want to archive. (Comma separated)
     * @type {string}
     * @memberof SourceKyve
     */
    'pool_ids': string;
    /**
     * The start-id defines, from which bundle id the pipeline should start to extract the data. (Comma separated)
     * @type {string}
     * @memberof SourceKyve
     */
    'start_ids': string;
    /**
     * URL to the KYVE Chain API.
     * @type {string}
     * @memberof SourceKyve
     */
    'url_base': string;
    /**
     * 
     * @type {string}
     * @memberof SourceKyve
     */
    'sourceType': SourceKyveSourceTypeEnum;
}

export const SourceKyveSourceTypeEnum = {
    KYVE: 'kyve'
} as const;

export type SourceKyveSourceTypeEnum = typeof SourceKyveSourceTypeEnum[keyof typeof SourceKyveSourceTypeEnum];


