/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceChameleon
 */
export interface SourceChameleon {
    /**
     * 
     * @type {string}
     * @memberof SourceChameleon
     */
    'api_key': string;
    /**
     * 
     * @type {string}
     * @memberof SourceChameleon
     */
    'start_date': string;
    /**
     * Max records per page limit
     * @type {string}
     * @memberof SourceChameleon
     */
    'limit'?: string;
    /**
     * Filter for using in the `segments_experiences` stream
     * @type {string}
     * @memberof SourceChameleon
     */
    'filter'?: SourceChameleonFilterEnum;
    /**
     * 
     * @type {string}
     * @memberof SourceChameleon
     */
    'end_date': string;
    /**
     * 
     * @type {string}
     * @memberof SourceChameleon
     */
    'sourceType': SourceChameleonSourceTypeEnum;
}

export const SourceChameleonFilterEnum = {
    TOUR: 'tour',
    SURVEY: 'survey',
    LAUNCHER: 'launcher'
} as const;

export type SourceChameleonFilterEnum = typeof SourceChameleonFilterEnum[keyof typeof SourceChameleonFilterEnum];
export const SourceChameleonSourceTypeEnum = {
    CHAMELEON: 'chameleon'
} as const;

export type SourceChameleonSourceTypeEnum = typeof SourceChameleonSourceTypeEnum[keyof typeof SourceChameleonSourceTypeEnum];


