/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Authentication14 } from './authentication14';

/**
 * 
 * @export
 * @interface SourceZendeskSupport
 */
export interface SourceZendeskSupport {
    /**
     * The UTC date and time from which you\'d like to replicate data, in the format YYYY-MM-DDT00:00:00Z. All data generated after this date will be replicated.
     * @type {string}
     * @memberof SourceZendeskSupport
     */
    'start_date'?: string;
    /**
     * This is your unique Zendesk subdomain that can be found in your account URL. For example, in https://MY_SUBDOMAIN.zendesk.com/, MY_SUBDOMAIN is the value of your subdomain.
     * @type {string}
     * @memberof SourceZendeskSupport
     */
    'subdomain': string;
    /**
     * 
     * @type {Authentication14}
     * @memberof SourceZendeskSupport
     */
    'credentials'?: Authentication14;
    /**
     * 
     * @type {string}
     * @memberof SourceZendeskSupport
     */
    'sourceType': SourceZendeskSupportSourceTypeEnum;
}

export const SourceZendeskSupportSourceTypeEnum = {
    ZENDESK_SUPPORT: 'zendesk-support'
} as const;

export type SourceZendeskSupportSourceTypeEnum = typeof SourceZendeskSupportSourceTypeEnum[keyof typeof SourceZendeskSupportSourceTypeEnum];


