/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceGooglePagespeedInsights
 */
export interface SourceGooglePagespeedInsights {
    /**
     * Google PageSpeed API Key. See <a href=\"https://developers.google.com/speed/docs/insights/v5/get-started#APIKey\">here</a>. The key is optional - however the API is heavily rate limited when using without API Key. Creating and using the API key therefore is recommended. The key is case sensitive.
     * @type {string}
     * @memberof SourceGooglePagespeedInsights
     */
    'api_key'?: string;
    /**
     * Defines which Lighthouse category to run. One or many of: \"accessibility\", \"best-practices\", \"performance\", \"pwa\", \"seo\".
     * @type {Array<string>}
     * @memberof SourceGooglePagespeedInsights
     */
    'categories': Array<SourceGooglePagespeedInsightsCategoriesEnum>;
    /**
     * The analyses strategy to use. Either \"desktop\" or \"mobile\".
     * @type {Array<string>}
     * @memberof SourceGooglePagespeedInsights
     */
    'strategies': Array<SourceGooglePagespeedInsightsStrategiesEnum>;
    /**
     * The URLs to retrieve pagespeed information from. The connector will attempt to sync PageSpeed reports for all the defined URLs. Format: https://(www.)url.domain
     * @type {Array<string>}
     * @memberof SourceGooglePagespeedInsights
     */
    'urls': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SourceGooglePagespeedInsights
     */
    'sourceType': SourceGooglePagespeedInsightsSourceTypeEnum;
}

export const SourceGooglePagespeedInsightsCategoriesEnum = {
    ACCESSIBILITY: 'accessibility',
    BEST_PRACTICES: 'best-practices',
    PERFORMANCE: 'performance',
    PWA: 'pwa',
    SEO: 'seo'
} as const;

export type SourceGooglePagespeedInsightsCategoriesEnum = typeof SourceGooglePagespeedInsightsCategoriesEnum[keyof typeof SourceGooglePagespeedInsightsCategoriesEnum];
export const SourceGooglePagespeedInsightsStrategiesEnum = {
    DESKTOP: 'desktop',
    MOBILE: 'mobile'
} as const;

export type SourceGooglePagespeedInsightsStrategiesEnum = typeof SourceGooglePagespeedInsightsStrategiesEnum[keyof typeof SourceGooglePagespeedInsightsStrategiesEnum];
export const SourceGooglePagespeedInsightsSourceTypeEnum = {
    GOOGLE_PAGESPEED_INSIGHTS: 'google-pagespeed-insights'
} as const;

export type SourceGooglePagespeedInsightsSourceTypeEnum = typeof SourceGooglePagespeedInsightsSourceTypeEnum[keyof typeof SourceGooglePagespeedInsightsSourceTypeEnum];


