/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceCustomerIo
 */
export interface SourceCustomerIo {
    /**
     * 
     * @type {string}
     * @memberof SourceCustomerIo
     */
    'app_api_key': string;
    /**
     * 
     * @type {string}
     * @memberof SourceCustomerIo
     */
    'sourceType': SourceCustomerIoSourceTypeEnum;
}

export const SourceCustomerIoSourceTypeEnum = {
    CUSTOMER_IO: 'customer-io'
} as const;

export type SourceCustomerIoSourceTypeEnum = typeof SourceCustomerIoSourceTypeEnum[keyof typeof SourceCustomerIoSourceTypeEnum];


