/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceClazarUpdate
 */
export interface SourceClazarUpdate {
    /**
     * 
     * @type {string}
     * @memberof SourceClazarUpdate
     */
    'client_id': string;
    /**
     * 
     * @type {string}
     * @memberof SourceClazarUpdate
     */
    'client_secret': string;
}

