/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceMailjetSms
 */
export interface SourceMailjetSms {
    /**
     * Retrieve SMS messages created before the specified timestamp. Required format - Unix timestamp.
     * @type {number}
     * @memberof SourceMailjetSms
     */
    'end_date'?: number;
    /**
     * Retrieve SMS messages created after the specified timestamp. Required format - Unix timestamp.
     * @type {number}
     * @memberof SourceMailjetSms
     */
    'start_date'?: number;
    /**
     * Your access token. See <a href=\"https://dev.mailjet.com/sms/reference/overview/authentication\">here</a>.
     * @type {string}
     * @memberof SourceMailjetSms
     */
    'token': string;
    /**
     * 
     * @type {string}
     * @memberof SourceMailjetSms
     */
    'sourceType': SourceMailjetSmsSourceTypeEnum;
}

export const SourceMailjetSmsSourceTypeEnum = {
    MAILJET_SMS: 'mailjet-sms'
} as const;

export type SourceMailjetSmsSourceTypeEnum = typeof SourceMailjetSmsSourceTypeEnum[keyof typeof SourceMailjetSmsSourceTypeEnum];


