/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceOnesignalUpdateApplicationsInner
 */
export interface SourceOnesignalUpdateApplicationsInner {
    /**
     * 
     * @type {string}
     * @memberof SourceOnesignalUpdateApplicationsInner
     */
    'app_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceOnesignalUpdateApplicationsInner
     */
    'app_id': string;
    /**
     * 
     * @type {string}
     * @memberof SourceOnesignalUpdateApplicationsInner
     */
    'app_api_key': string;
}

