/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceWhenIWork
 */
export interface SourceWhenIWork {
    /**
     * Email of your when-i-work account
     * @type {string}
     * @memberof SourceWhenIWork
     */
    'email': string;
    /**
     * Password for your when-i-work account
     * @type {string}
     * @memberof SourceWhenIWork
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof SourceWhenIWork
     */
    'sourceType': SourceWhenIWorkSourceTypeEnum;
}

export const SourceWhenIWorkSourceTypeEnum = {
    WHEN_I_WORK: 'when-i-work'
} as const;

export type SourceWhenIWorkSourceTypeEnum = typeof SourceWhenIWorkSourceTypeEnum[keyof typeof SourceWhenIWorkSourceTypeEnum];


