/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceClazar
 */
export interface SourceClazar {
    /**
     * 
     * @type {string}
     * @memberof SourceClazar
     */
    'client_id': string;
    /**
     * 
     * @type {string}
     * @memberof SourceClazar
     */
    'client_secret': string;
    /**
     * 
     * @type {string}
     * @memberof SourceClazar
     */
    'sourceType': SourceClazarSourceTypeEnum;
}

export const SourceClazarSourceTypeEnum = {
    CLAZAR: 'clazar'
} as const;

export type SourceClazarSourceTypeEnum = typeof SourceClazarSourceTypeEnum[keyof typeof SourceClazarSourceTypeEnum];


