/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceCloseCom
 */
export interface SourceCloseCom {
    /**
     * Close.com API key (usually starts with \'api_\'; find yours <a href=\"https://app.close.com/settings/api/\">here</a>).
     * @type {string}
     * @memberof SourceCloseCom
     */
    'api_key': string;
    /**
     * The start date to sync data; all data after this date will be replicated. Leave blank to retrieve all the data available in the account. Format: YYYY-MM-DD.
     * @type {string}
     * @memberof SourceCloseCom
     */
    'start_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceCloseCom
     */
    'sourceType': SourceCloseComSourceTypeEnum;
}

export const SourceCloseComSourceTypeEnum = {
    CLOSE_COM: 'close-com'
} as const;

export type SourceCloseComSourceTypeEnum = typeof SourceCloseComSourceTypeEnum[keyof typeof SourceCloseComSourceTypeEnum];


