/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceLooker
 */
export interface SourceLooker {
    /**
     * The Client ID is first part of an API3 key that is specific to each Looker user. See the <a href=\"https://docs.airbyte.com/integrations/sources/looker\">docs</a> for more information on how to generate this key.
     * @type {string}
     * @memberof SourceLooker
     */
    'client_id': string;
    /**
     * The Client Secret is second part of an API3 key.
     * @type {string}
     * @memberof SourceLooker
     */
    'client_secret': string;
    /**
     * Domain for your Looker account, e.g. airbyte.cloud.looker.com,looker.[clientname].com,IP address
     * @type {string}
     * @memberof SourceLooker
     */
    'domain': string;
    /**
     * The IDs of any Looks to run
     * @type {Array<string>}
     * @memberof SourceLooker
     */
    'run_look_ids'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SourceLooker
     */
    'sourceType': SourceLookerSourceTypeEnum;
}

export const SourceLookerSourceTypeEnum = {
    LOOKER: 'looker'
} as const;

export type SourceLookerSourceTypeEnum = typeof SourceLookerSourceTypeEnum[keyof typeof SourceLookerSourceTypeEnum];


