/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceClockify
 */
export interface SourceClockify {
    /**
     * You can get your api access_key <a href=\"https://app.clockify.me/user/settings\">here</a> This API is Case Sensitive.
     * @type {string}
     * @memberof SourceClockify
     */
    'api_key': string;
    /**
     * The URL for the Clockify API. This should only need to be modified if connecting to an enterprise version of Clockify.
     * @type {string}
     * @memberof SourceClockify
     */
    'api_url'?: string;
    /**
     * WorkSpace Id
     * @type {string}
     * @memberof SourceClockify
     */
    'workspace_id': string;
    /**
     * 
     * @type {string}
     * @memberof SourceClockify
     */
    'sourceType': SourceClockifySourceTypeEnum;
}

export const SourceClockifySourceTypeEnum = {
    CLOCKIFY: 'clockify'
} as const;

export type SourceClockifySourceTypeEnum = typeof SourceClockifySourceTypeEnum[keyof typeof SourceClockifySourceTypeEnum];


