/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceLokaliseUpdate
 */
export interface SourceLokaliseUpdate {
    /**
     * Lokalise API Key with read-access. Available at Profile settings > API tokens. See <a href=\"https://docs.lokalise.com/en/articles/1929556-api-tokens\">here</a>.
     * @type {string}
     * @memberof SourceLokaliseUpdate
     */
    'api_key': string;
    /**
     * Lokalise project ID. Available at Project Settings > General.
     * @type {string}
     * @memberof SourceLokaliseUpdate
     */
    'project_id': string;
}

