/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceFreshsales
 */
export interface SourceFreshsales {
    /**
     * Freshsales API Key. See <a href=\"https://crmsupport.freshworks.com/support/solutions/articles/50000002503-how-to-find-my-api-key-\">here</a>. The key is case sensitive.
     * @type {string}
     * @memberof SourceFreshsales
     */
    'api_key': string;
    /**
     * The Name of your Freshsales domain
     * @type {string}
     * @memberof SourceFreshsales
     */
    'domain_name': string;
    /**
     * 
     * @type {string}
     * @memberof SourceFreshsales
     */
    'sourceType': SourceFreshsalesSourceTypeEnum;
}

export const SourceFreshsalesSourceTypeEnum = {
    FRESHSALES: 'freshsales'
} as const;

export type SourceFreshsalesSourceTypeEnum = typeof SourceFreshsalesSourceTypeEnum[keyof typeof SourceFreshsalesSourceTypeEnum];


