/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceRailz
 */
export interface SourceRailz {
    /**
     * Client ID (client_id)
     * @type {string}
     * @memberof SourceRailz
     */
    'client_id': string;
    /**
     * Secret key (secret_key)
     * @type {string}
     * @memberof SourceRailz
     */
    'secret_key': string;
    /**
     * Start date
     * @type {string}
     * @memberof SourceRailz
     */
    'start_date': string;
    /**
     * 
     * @type {string}
     * @memberof SourceRailz
     */
    'sourceType': SourceRailzSourceTypeEnum;
}

export const SourceRailzSourceTypeEnum = {
    RAILZ: 'railz'
} as const;

export type SourceRailzSourceTypeEnum = typeof SourceRailzSourceTypeEnum[keyof typeof SourceRailzSourceTypeEnum];


