/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceGoogleAdsCustomQueriesArrayInner
 */
export interface SourceGoogleAdsCustomQueriesArrayInner {
    /**
     * A custom defined GAQL query for building the report. Avoid including the segments.date field; wherever possible, Airbyte will automatically include it for incremental syncs. For more information, refer to <a href=\"https://developers.google.com/google-ads/api/fields/v11/overview_query_builder\">Google\'s documentation</a>.
     * @type {string}
     * @memberof SourceGoogleAdsCustomQueriesArrayInner
     */
    'query': string;
    /**
     * The table name in your destination database for the chosen query.
     * @type {string}
     * @memberof SourceGoogleAdsCustomQueriesArrayInner
     */
    'table_name': string;
}

