/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Authentication21 } from './authentication21';
// May contain unused imports in some cases
// @ts-ignore
import type { InsightConfig } from './insight-config';

/**
 * 
 * @export
 * @interface SourceFacebookMarketingUpdate
 */
export interface SourceFacebookMarketingUpdate {
    /**
     * The Facebook Ad account ID(s) to pull data from. The Ad account ID number is in the account dropdown menu or in your browser\'s address bar of your <a href=\"https://adsmanager.facebook.com/adsmanager/\">Meta Ads Manager</a>. See the <a href=\"https://www.facebook.com/business/help/1492627900875762\">docs</a> for more information.
     * @type {Set<string>}
     * @memberof SourceFacebookMarketingUpdate
     */
    'account_ids': Set<string>;
    /**
     * The value of the generated access token. From your App’s Dashboard, click on \"Marketing API\" then \"Tools\". Select permissions <b>ads_management, ads_read, read_insights, business_management</b>. Then click on \"Get token\". See the <a href=\"https://docs.airbyte.com/integrations/sources/facebook-marketing\">docs</a> for more information.
     * @type {string}
     * @memberof SourceFacebookMarketingUpdate
     */
    'access_token'?: string;
    /**
     * 
     * @type {Authentication21}
     * @memberof SourceFacebookMarketingUpdate
     */
    'credentials': Authentication21;
    /**
     * The date from which you\'d like to replicate data for all incremental streams, in the format YYYY-MM-DDT00:00:00Z. If not set then all data will be replicated for usual streams and only last 2 years for insight streams.
     * @type {string}
     * @memberof SourceFacebookMarketingUpdate
     */
    'start_date'?: string;
    /**
     * The date until which you\'d like to replicate data for all incremental streams, in the format YYYY-MM-DDT00:00:00Z. All data generated between the start date and this end date will be replicated. Not setting this option will result in always syncing the latest data.
     * @type {string}
     * @memberof SourceFacebookMarketingUpdate
     */
    'end_date'?: string;
    /**
     * Select the statuses you want to be loaded in the stream. If no specific statuses are selected, the API\'s default behavior applies, and some statuses may be filtered out.
     * @type {Array<string>}
     * @memberof SourceFacebookMarketingUpdate
     */
    'campaign_statuses'?: Array<SourceFacebookMarketingUpdateCampaignStatusesEnum>;
    /**
     * Select the statuses you want to be loaded in the stream. If no specific statuses are selected, the API\'s default behavior applies, and some statuses may be filtered out.
     * @type {Array<string>}
     * @memberof SourceFacebookMarketingUpdate
     */
    'adset_statuses'?: Array<SourceFacebookMarketingUpdateAdsetStatusesEnum>;
    /**
     * Select the statuses you want to be loaded in the stream. If no specific statuses are selected, the API\'s default behavior applies, and some statuses may be filtered out.
     * @type {Array<string>}
     * @memberof SourceFacebookMarketingUpdate
     */
    'ad_statuses'?: Array<SourceFacebookMarketingUpdateAdStatusesEnum>;
    /**
     * Set to active if you want to fetch the thumbnail_url and store the result in thumbnail_data_url for each Ad Creative.
     * @type {boolean}
     * @memberof SourceFacebookMarketingUpdate
     */
    'fetch_thumbnail_images'?: boolean;
    /**
     * A list which contains ad statistics entries, each entry must have a name and can contains fields, breakdowns or action_breakdowns. Click on \"add\" to fill this field.
     * @type {Array<InsightConfig>}
     * @memberof SourceFacebookMarketingUpdate
     */
    'custom_insights'?: Array<InsightConfig>;
    /**
     * Page size used when sending requests to Facebook API to specify number of records per page when response has pagination. Most users do not need to set this field unless they specifically need to tune the connector to address specific issues or use cases.
     * @type {number}
     * @memberof SourceFacebookMarketingUpdate
     */
    'page_size'?: number;
    /**
     * The attribution window. Facebook freezes insight data 28 days after it was generated, which means that all data from the past 28 days may have changed since we last emitted it, so you can retrieve refreshed insights from the past by setting this parameter. If you set a custom lookback window value in Facebook account, please provide the same value here.
     * @type {number}
     * @memberof SourceFacebookMarketingUpdate
     */
    'insights_lookback_window'?: number;
    /**
     * Insights Job Timeout establishes the maximum amount of time (in minutes) of waiting for the report job to complete. When timeout is reached the job is considered failed and we are trying to request smaller amount of data by breaking the job to few smaller ones. If you definitely know that 60 minutes is not enough for your report to be processed then you can decrease the timeout value, so we start breaking job to smaller parts faster.
     * @type {number}
     * @memberof SourceFacebookMarketingUpdate
     */
    'insights_job_timeout'?: number;
}

export const SourceFacebookMarketingUpdateCampaignStatusesEnum = {
    ACTIVE: 'ACTIVE',
    ARCHIVED: 'ARCHIVED',
    DELETED: 'DELETED',
    IN_PROCESS: 'IN_PROCESS',
    PAUSED: 'PAUSED',
    WITH_ISSUES: 'WITH_ISSUES'
} as const;

export type SourceFacebookMarketingUpdateCampaignStatusesEnum = typeof SourceFacebookMarketingUpdateCampaignStatusesEnum[keyof typeof SourceFacebookMarketingUpdateCampaignStatusesEnum];
export const SourceFacebookMarketingUpdateAdsetStatusesEnum = {
    ACTIVE: 'ACTIVE',
    ARCHIVED: 'ARCHIVED',
    CAMPAIGN_PAUSED: 'CAMPAIGN_PAUSED',
    DELETED: 'DELETED',
    IN_PROCESS: 'IN_PROCESS',
    PAUSED: 'PAUSED',
    WITH_ISSUES: 'WITH_ISSUES'
} as const;

export type SourceFacebookMarketingUpdateAdsetStatusesEnum = typeof SourceFacebookMarketingUpdateAdsetStatusesEnum[keyof typeof SourceFacebookMarketingUpdateAdsetStatusesEnum];
export const SourceFacebookMarketingUpdateAdStatusesEnum = {
    ACTIVE: 'ACTIVE',
    ADSET_PAUSED: 'ADSET_PAUSED',
    ARCHIVED: 'ARCHIVED',
    CAMPAIGN_PAUSED: 'CAMPAIGN_PAUSED',
    DELETED: 'DELETED',
    DISAPPROVED: 'DISAPPROVED',
    IN_PROCESS: 'IN_PROCESS',
    PAUSED: 'PAUSED',
    PENDING_BILLING_INFO: 'PENDING_BILLING_INFO',
    PENDING_REVIEW: 'PENDING_REVIEW',
    PREAPPROVED: 'PREAPPROVED',
    WITH_ISSUES: 'WITH_ISSUES'
} as const;

export type SourceFacebookMarketingUpdateAdStatusesEnum = typeof SourceFacebookMarketingUpdateAdStatusesEnum[keyof typeof SourceFacebookMarketingUpdateAdStatusesEnum];


