/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourcePlanhatUpdate
 */
export interface SourcePlanhatUpdate {
    /**
     * Your Planhat <a href=\"https://docs.planhat.com/#authentication\">API Access Token</a>
     * @type {string}
     * @memberof SourcePlanhatUpdate
     */
    'api_token': string;
}

