/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceKlarnaUpdate
 */
export interface SourceKlarnaUpdate {
    /**
     * Base url region (For playground eu https://docs.klarna.com/klarna-payments/api/payments-api/#tag/API-URLs). Supported \'eu\', \'na\', \'oc\'
     * @type {string}
     * @memberof SourceKlarnaUpdate
     */
    'region': SourceKlarnaUpdateRegionEnum;
    /**
     * Propertie defining if connector is used against playground or production environment
     * @type {boolean}
     * @memberof SourceKlarnaUpdate
     */
    'playground': boolean;
    /**
     * Consists of your Merchant ID (eid) - a unique number that identifies your e-store, combined with a random string (https://developers.klarna.com/api/#authentication)
     * @type {string}
     * @memberof SourceKlarnaUpdate
     */
    'username': string;
    /**
     * A string which is associated with your Merchant ID and is used to authorize use of Klarna\'s APIs (https://developers.klarna.com/api/#authentication)
     * @type {string}
     * @memberof SourceKlarnaUpdate
     */
    'password': string;
}

export const SourceKlarnaUpdateRegionEnum = {
    EU: 'eu',
    NA: 'na',
    OC: 'oc'
} as const;

export type SourceKlarnaUpdateRegionEnum = typeof SourceKlarnaUpdateRegionEnum[keyof typeof SourceKlarnaUpdateRegionEnum];


