/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Authentication } from './authentication';

/**
 * 
 * @export
 * @interface SourceMixpanel
 */
export interface SourceMixpanel {
    /**
     * 
     * @type {Authentication}
     * @memberof SourceMixpanel
     */
    'credentials': Authentication;
    /**
     * A period of time for attributing results to ads and the lookback period after those actions occur during which ad results are counted. Default attribution window is 5 days. (This value should be non-negative integer)
     * @type {number}
     * @memberof SourceMixpanel
     */
    'attribution_window'?: number;
    /**
     * Time zone in which integer date times are stored. The project timezone may be found in the project settings in the <a href=\"https://help.mixpanel.com/hc/en-us/articles/115004547203-Manage-Timezones-for-Projects-in-Mixpanel\">Mixpanel console</a>.
     * @type {string}
     * @memberof SourceMixpanel
     */
    'project_timezone'?: string;
    /**
     * Setting this config parameter to TRUE ensures that new properties on events and engage records are captured. Otherwise new properties will be ignored.
     * @type {boolean}
     * @memberof SourceMixpanel
     */
    'select_properties_by_default'?: boolean;
    /**
     * The date in the format YYYY-MM-DD. Any data before this date will not be replicated. If this option is not set, the connector will replicate data from up to one year ago by default.
     * @type {string}
     * @memberof SourceMixpanel
     */
    'start_date'?: string;
    /**
     * The date in the format YYYY-MM-DD. Any data after this date will not be replicated. Left empty to always sync to most recent date
     * @type {string}
     * @memberof SourceMixpanel
     */
    'end_date'?: string;
    /**
     * The region of mixpanel domain instance either US or EU.
     * @type {string}
     * @memberof SourceMixpanel
     */
    'region'?: SourceMixpanelRegionEnum;
    /**
     * Defines window size in days, that used to slice through data. You can reduce it, if amount of data in each window is too big for your environment. (This value should be positive integer)
     * @type {number}
     * @memberof SourceMixpanel
     */
    'date_window_size'?: number;
    /**
     * The number of records to fetch per request for the engage stream. Default is 1000. If you are experiencing long sync times with this stream, try increasing this value.
     * @type {number}
     * @memberof SourceMixpanel
     */
    'page_size'?: number;
    /**
     * 
     * @type {string}
     * @memberof SourceMixpanel
     */
    'sourceType': SourceMixpanelSourceTypeEnum;
}

export const SourceMixpanelRegionEnum = {
    US: 'US',
    EU: 'EU'
} as const;

export type SourceMixpanelRegionEnum = typeof SourceMixpanelRegionEnum[keyof typeof SourceMixpanelRegionEnum];
export const SourceMixpanelSourceTypeEnum = {
    MIXPANEL: 'mixpanel'
} as const;

export type SourceMixpanelSourceTypeEnum = typeof SourceMixpanelSourceTypeEnum[keyof typeof SourceMixpanelSourceTypeEnum];


