/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceZoom
 */
export interface SourceZoom {
    /**
     * The account ID for your Zoom account. You can find this in the Zoom Marketplace under the \"Manage\" tab for your app.
     * @type {string}
     * @memberof SourceZoom
     */
    'account_id': string;
    /**
     * The client ID for your Zoom app. You can find this in the Zoom Marketplace under the \"Manage\" tab for your app.
     * @type {string}
     * @memberof SourceZoom
     */
    'client_id': string;
    /**
     * The client secret for your Zoom app. You can find this in the Zoom Marketplace under the \"Manage\" tab for your app.
     * @type {string}
     * @memberof SourceZoom
     */
    'client_secret': string;
    /**
     * 
     * @type {string}
     * @memberof SourceZoom
     */
    'authorization_endpoint': string;
    /**
     * 
     * @type {string}
     * @memberof SourceZoom
     */
    'sourceType': SourceZoomSourceTypeEnum;
}

export const SourceZoomSourceTypeEnum = {
    ZOOM: 'zoom'
} as const;

export type SourceZoomSourceTypeEnum = typeof SourceZoomSourceTypeEnum[keyof typeof SourceZoomSourceTypeEnum];


