/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceDremioUpdate
 */
export interface SourceDremioUpdate {
    /**
     * API Key that is generated when you authenticate to Dremio API
     * @type {string}
     * @memberof SourceDremioUpdate
     */
    'api_key': string;
    /**
     * URL of your Dremio instance
     * @type {string}
     * @memberof SourceDremioUpdate
     */
    'base_url': string;
}

