/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceHighLevel
 */
export interface SourceHighLevel {
    /**
     * 
     * @type {string}
     * @memberof SourceHighLevel
     */
    'location_id': string;
    /**
     * 
     * @type {string}
     * @memberof SourceHighLevel
     */
    'api_key': string;
    /**
     * 
     * @type {string}
     * @memberof SourceHighLevel
     */
    'start_date': string;
    /**
     * 
     * @type {string}
     * @memberof SourceHighLevel
     */
    'sourceType': SourceHighLevelSourceTypeEnum;
}

export const SourceHighLevelSourceTypeEnum = {
    HIGH_LEVEL: 'high-level'
} as const;

export type SourceHighLevelSourceTypeEnum = typeof SourceHighLevelSourceTypeEnum[keyof typeof SourceHighLevelSourceTypeEnum];


