/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceConfigcat
 */
export interface SourceConfigcat {
    /**
     * Basic auth user name. See <a href=\"https://api.configcat.com/docs/#section/Authentication\">here</a>.
     * @type {string}
     * @memberof SourceConfigcat
     */
    'username': string;
    /**
     * Basic auth password. See <a href=\"https://api.configcat.com/docs/#section/Authentication\">here</a>.
     * @type {string}
     * @memberof SourceConfigcat
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof SourceConfigcat
     */
    'sourceType': SourceConfigcatSourceTypeEnum;
}

export const SourceConfigcatSourceTypeEnum = {
    CONFIGCAT: 'configcat'
} as const;

export type SourceConfigcatSourceTypeEnum = typeof SourceConfigcatSourceTypeEnum[keyof typeof SourceConfigcatSourceTypeEnum];


