/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthorizationMethod7 } from './authorization-method7';

/**
 * 
 * @export
 * @interface SourceSnowflakeUpdate
 */
export interface SourceSnowflakeUpdate {
    /**
     * 
     * @type {AuthorizationMethod7}
     * @memberof SourceSnowflakeUpdate
     */
    'credentials'?: AuthorizationMethod7;
    /**
     * The host domain of the snowflake instance (must include the account, region, cloud environment, and end with snowflakecomputing.com).
     * @type {string}
     * @memberof SourceSnowflakeUpdate
     */
    'host': string;
    /**
     * The role you created for Airbyte to access Snowflake.
     * @type {string}
     * @memberof SourceSnowflakeUpdate
     */
    'role': string;
    /**
     * The warehouse you created for Airbyte to access data.
     * @type {string}
     * @memberof SourceSnowflakeUpdate
     */
    'warehouse': string;
    /**
     * The database you created for Airbyte to access data.
     * @type {string}
     * @memberof SourceSnowflakeUpdate
     */
    'database': string;
    /**
     * The source Snowflake schema tables. Leave empty to access tables from multiple schemas.
     * @type {string}
     * @memberof SourceSnowflakeUpdate
     */
    'schema'?: string;
    /**
     * Additional properties to pass to the JDBC URL string when connecting to the database formatted as \'key=value\' pairs separated by the symbol \'&\'. (example: key1=value1&key2=value2&key3=value3).
     * @type {string}
     * @memberof SourceSnowflakeUpdate
     */
    'jdbc_url_params'?: string;
}

