/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceBambooHr
 */
export interface SourceBambooHr {
    /**
     * Api key of bamboo hr
     * @type {string}
     * @memberof SourceBambooHr
     */
    'api_key': string;
    /**
     * Sub Domain of bamboo hr
     * @type {string}
     * @memberof SourceBambooHr
     */
    'subdomain': string;
    /**
     * Comma-separated list of fields to include in custom reports.
     * @type {string}
     * @memberof SourceBambooHr
     */
    'custom_reports_fields'?: string;
    /**
     * If true, the custom reports endpoint will include the default fields defined here: https://documentation.bamboohr.com/docs/list-of-field-names.
     * @type {boolean}
     * @memberof SourceBambooHr
     */
    'custom_reports_include_default_fields'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SourceBambooHr
     */
    'start_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceBambooHr
     */
    'sourceType': SourceBambooHrSourceTypeEnum;
}

export const SourceBambooHrSourceTypeEnum = {
    BAMBOO_HR: 'bamboo-hr'
} as const;

export type SourceBambooHrSourceTypeEnum = typeof SourceBambooHrSourceTypeEnum[keyof typeof SourceBambooHrSourceTypeEnum];


