/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceTwilioTaskrouter
 */
export interface SourceTwilioTaskrouter {
    /**
     * Twilio Account ID
     * @type {string}
     * @memberof SourceTwilioTaskrouter
     */
    'account_sid': string;
    /**
     * Twilio Auth Token
     * @type {string}
     * @memberof SourceTwilioTaskrouter
     */
    'auth_token': string;
    /**
     * 
     * @type {string}
     * @memberof SourceTwilioTaskrouter
     */
    'sourceType': SourceTwilioTaskrouterSourceTypeEnum;
}

export const SourceTwilioTaskrouterSourceTypeEnum = {
    TWILIO_TASKROUTER: 'twilio-taskrouter'
} as const;

export type SourceTwilioTaskrouterSourceTypeEnum = typeof SourceTwilioTaskrouterSourceTypeEnum[keyof typeof SourceTwilioTaskrouterSourceTypeEnum];


