/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceSonarCloud
 */
export interface SourceSonarCloud {
    /**
     * Comma-separated list of component keys.
     * @type {Array<any>}
     * @memberof SourceSonarCloud
     */
    'component_keys': Array<any>;
    /**
     * To retrieve issues created before the given date (inclusive).
     * @type {string}
     * @memberof SourceSonarCloud
     */
    'end_date'?: string;
    /**
     * Organization key. See <a href=\"https://docs.sonarcloud.io/appendices/project-information/#project-and-organization-keys\">here</a>.
     * @type {string}
     * @memberof SourceSonarCloud
     */
    'organization': string;
    /**
     * To retrieve issues created after the given date (inclusive).
     * @type {string}
     * @memberof SourceSonarCloud
     */
    'start_date'?: string;
    /**
     * Your User Token. See <a href=\"https://docs.sonarcloud.io/advanced-setup/user-accounts/\">here</a>. The token is case sensitive.
     * @type {string}
     * @memberof SourceSonarCloud
     */
    'user_token': string;
    /**
     * 
     * @type {string}
     * @memberof SourceSonarCloud
     */
    'sourceType': SourceSonarCloudSourceTypeEnum;
}

export const SourceSonarCloudSourceTypeEnum = {
    SONAR_CLOUD: 'sonar-cloud'
} as const;

export type SourceSonarCloudSourceTypeEnum = typeof SourceSonarCloudSourceTypeEnum[keyof typeof SourceSonarCloudSourceTypeEnum];


