/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceProductive
 */
export interface SourceProductive {
    /**
     * 
     * @type {string}
     * @memberof SourceProductive
     */
    'api_key': string;
    /**
     * The organization ID which could be seen from `https://app.productive.io/xxxx-xxxx/settings/api-integrations` page
     * @type {string}
     * @memberof SourceProductive
     */
    'organization_id': string;
    /**
     * 
     * @type {string}
     * @memberof SourceProductive
     */
    'sourceType': SourceProductiveSourceTypeEnum;
}

export const SourceProductiveSourceTypeEnum = {
    PRODUCTIVE: 'productive'
} as const;

export type SourceProductiveSourceTypeEnum = typeof SourceProductiveSourceTypeEnum[keyof typeof SourceProductiveSourceTypeEnum];


