/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceDatascopeUpdate
 */
export interface SourceDatascopeUpdate {
    /**
     * API Key
     * @type {string}
     * @memberof SourceDatascopeUpdate
     */
    'api_key': string;
    /**
     * Start date for the data to be replicated
     * @type {string}
     * @memberof SourceDatascopeUpdate
     */
    'start_date': string;
}

