/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Authentication27 } from './authentication27';

/**
 * 
 * @export
 * @interface SourceMailchimpUpdate
 */
export interface SourceMailchimpUpdate {
    /**
     * 
     * @type {Authentication27}
     * @memberof SourceMailchimpUpdate
     */
    'credentials'?: Authentication27;
    /**
     * The date from which you want to start syncing data for Incremental streams. Only records that have been created or modified since this date will be synced. If left blank, all data will by synced.
     * @type {string}
     * @memberof SourceMailchimpUpdate
     */
    'start_date'?: string;
}

