/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceGetlagoUpdate
 */
export interface SourceGetlagoUpdate {
    /**
     * Your Lago API URL
     * @type {string}
     * @memberof SourceGetlagoUpdate
     */
    'api_url'?: string;
    /**
     * Your API Key. See <a href=\"https://doc.getlago.com/docs/api/intro\">here</a>.
     * @type {string}
     * @memberof SourceGetlagoUpdate
     */
    'api_key': string;
}

