/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceAircallUpdate
 */
export interface SourceAircallUpdate {
    /**
     * App ID found at settings https://dashboard.aircall.io/integrations/api-keys
     * @type {string}
     * @memberof SourceAircallUpdate
     */
    'api_id': string;
    /**
     * App token found at settings (Ref- https://dashboard.aircall.io/integrations/api-keys)
     * @type {string}
     * @memberof SourceAircallUpdate
     */
    'api_token': string;
    /**
     * Date time filter for incremental filter, Specify which date to extract from.
     * @type {string}
     * @memberof SourceAircallUpdate
     */
    'start_date': string;
}

