/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthorizationMethod11 } from './authorization-method11';

/**
 * 
 * @export
 * @interface SourceTrustpilotUpdate
 */
export interface SourceTrustpilotUpdate {
    /**
     * 
     * @type {AuthorizationMethod11}
     * @memberof SourceTrustpilotUpdate
     */
    'credentials': AuthorizationMethod11;
    /**
     * The names of business units which shall be synchronized. Some streams e.g. configured_business_units or private_reviews use this configuration.
     * @type {Array<string>}
     * @memberof SourceTrustpilotUpdate
     */
    'business_units': Array<string>;
    /**
     * For streams with sync. method incremental the start date time to be used
     * @type {string}
     * @memberof SourceTrustpilotUpdate
     */
    'start_date': string;
}

