/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceNorthpassLms
 */
export interface SourceNorthpassLms {
    /**
     * 
     * @type {string}
     * @memberof SourceNorthpassLms
     */
    'api_key': string;
    /**
     * 
     * @type {string}
     * @memberof SourceNorthpassLms
     */
    'sourceType': SourceNorthpassLmsSourceTypeEnum;
}

export const SourceNorthpassLmsSourceTypeEnum = {
    NORTHPASS_LMS: 'northpass-lms'
} as const;

export type SourceNorthpassLmsSourceTypeEnum = typeof SourceNorthpassLmsSourceTypeEnum[keyof typeof SourceNorthpassLmsSourceTypeEnum];


