/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceVantageUpdate
 */
export interface SourceVantageUpdate {
    /**
     * Your API Access token. See <a href=\"https://vantage.readme.io/reference/authentication\">here</a>.
     * @type {string}
     * @memberof SourceVantageUpdate
     */
    'access_token': string;
}

