/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Provides details of a single source.
 * @export
 * @interface SourceResponse
 */
export interface SourceResponse {
    /**
     * 
     * @type {string}
     * @memberof SourceResponse
     */
    'sourceId': string;
    /**
     * 
     * @type {string}
     * @memberof SourceResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof SourceResponse
     */
    'sourceType': string;
    /**
     * 
     * @type {string}
     * @memberof SourceResponse
     */
    'workspaceId': string;
    /**
     * 
     * @type {any}
     * @memberof SourceResponse
     */
    'configuration': any;
}

