/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SourceIterable
 */
export interface SourceIterable {
    /**
     * Iterable API Key. See the <a href=\\\"https://docs.airbyte.com/integrations/sources/iterable\\\">docs</a>  for more information on how to obtain this key.
     * @type {string}
     * @memberof SourceIterable
     */
    'api_key': string;
    /**
     * The date from which you\'d like to replicate data for Iterable, in the format YYYY-MM-DDT00:00:00Z.  All data generated after this date will be replicated.
     * @type {string}
     * @memberof SourceIterable
     */
    'start_date': string;
    /**
     * 
     * @type {string}
     * @memberof SourceIterable
     */
    'sourceType': SourceIterableSourceTypeEnum;
}

export const SourceIterableSourceTypeEnum = {
    ITERABLE: 'iterable'
} as const;

export type SourceIterableSourceTypeEnum = typeof SourceIterableSourceTypeEnum[keyof typeof SourceIterableSourceTypeEnum];


