/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SSHKeyAuthentication1
 */
export interface SSHKeyAuthentication1 {
    /**
     * Connect through a jump server tunnel host using username and ssh key
     * @type {string}
     * @memberof SSHKeyAuthentication1
     */
    'tunnel_method': SSHKeyAuthentication1TunnelMethodEnum;
    /**
     * Hostname of the jump server host that allows inbound ssh tunnel.
     * @type {string}
     * @memberof SSHKeyAuthentication1
     */
    'tunnel_host': string;
    /**
     * Port on the proxy/jump server that accepts inbound ssh connections.
     * @type {number}
     * @memberof SSHKeyAuthentication1
     */
    'tunnel_port': number;
    /**
     * OS-level username for logging into the jump server host.
     * @type {string}
     * @memberof SSHKeyAuthentication1
     */
    'tunnel_user': string;
    /**
     * OS-level user account ssh key credentials in RSA PEM format ( created with ssh-keygen -t rsa -m PEM -f myuser_rsa )
     * @type {string}
     * @memberof SSHKeyAuthentication1
     */
    'ssh_key': string;
}

export const SSHKeyAuthentication1TunnelMethodEnum = {
    SSH_KEY_AUTH: 'SSH_KEY_AUTH'
} as const;

export type SSHKeyAuthentication1TunnelMethodEnum = typeof SSHKeyAuthentication1TunnelMethodEnum[keyof typeof SSHKeyAuthentication1TunnelMethodEnum];


