/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SSHKeyAuthentication3
 */
export interface SSHKeyAuthentication3 {
    /**
     * Connect through ssh key
     * @type {string}
     * @memberof SSHKeyAuthentication3
     */
    'auth_method': SSHKeyAuthentication3AuthMethodEnum;
    /**
     * OS-level user account ssh key credentials in RSA PEM format ( created with ssh-keygen -t rsa -m PEM -f myuser_rsa )
     * @type {string}
     * @memberof SSHKeyAuthentication3
     */
    'auth_ssh_key': string;
}

export const SSHKeyAuthentication3AuthMethodEnum = {
    SSH_KEY_AUTH: 'SSH_KEY_AUTH'
} as const;

export type SSHKeyAuthentication3AuthMethodEnum = typeof SSHKeyAuthentication3AuthMethodEnum[keyof typeof SSHKeyAuthentication3AuthMethodEnum];


