/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Preferred } from './preferred';
// May contain unused imports in some cases
// @ts-ignore
import type { Required } from './required';
// May contain unused imports in some cases
// @ts-ignore
import type { VerifyCA } from './verify-ca';
// May contain unused imports in some cases
// @ts-ignore
import type { VerifyIdentity } from './verify-identity';

/**
 * @type SSLModes
 * SSL connection modes. Read more <a href=\"https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-using-ssl.html\"> in the docs</a>.
 * @export
 */
export type SSLModes = Preferred | Required | VerifyCA | VerifyIdentity;


