/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StringFilter
 */
export interface StringFilter {
    /**
     * 
     * @type {string}
     * @memberof StringFilter
     */
    'filter_name': StringFilterFilterNameEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof StringFilter
     */
    'matchType'?: Array<StringFilterMatchTypeEnum>;
    /**
     * 
     * @type {string}
     * @memberof StringFilter
     */
    'value': string;
    /**
     * 
     * @type {boolean}
     * @memberof StringFilter
     */
    'caseSensitive'?: boolean;
}

export const StringFilterFilterNameEnum = {
    STRING_FILTER: 'stringFilter'
} as const;

export type StringFilterFilterNameEnum = typeof StringFilterFilterNameEnum[keyof typeof StringFilterFilterNameEnum];
export const StringFilterMatchTypeEnum = {
    MATCH_TYPE_UNSPECIFIED: 'MATCH_TYPE_UNSPECIFIED',
    EXACT: 'EXACT',
    BEGINS_WITH: 'BEGINS_WITH',
    ENDS_WITH: 'ENDS_WITH',
    CONTAINS: 'CONTAINS',
    FULL_REGEXP: 'FULL_REGEXP',
    PARTIAL_REGEXP: 'PARTIAL_REGEXP'
} as const;

export type StringFilterMatchTypeEnum = typeof StringFilterMatchTypeEnum[keyof typeof StringFilterMatchTypeEnum];


