/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The authorization method to use to retrieve data from SurveyMonkey
 * @export
 * @interface SurveyMonkeyAuthorizationMethod1
 */
export interface SurveyMonkeyAuthorizationMethod1 {
    /**
     * 
     * @type {string}
     * @memberof SurveyMonkeyAuthorizationMethod1
     */
    'auth_method': SurveyMonkeyAuthorizationMethod1AuthMethodEnum;
    /**
     * The Client ID of the SurveyMonkey developer application.
     * @type {string}
     * @memberof SurveyMonkeyAuthorizationMethod1
     */
    'client_id'?: string;
    /**
     * The Client Secret of the SurveyMonkey developer application.
     * @type {string}
     * @memberof SurveyMonkeyAuthorizationMethod1
     */
    'client_secret'?: string;
    /**
     * Access Token for making authenticated requests. See the <a href=\"https://docs.airbyte.io/integrations/sources/surveymonkey\">docs</a> for information on how to generate this key.
     * @type {string}
     * @memberof SurveyMonkeyAuthorizationMethod1
     */
    'access_token': string;
}

export const SurveyMonkeyAuthorizationMethod1AuthMethodEnum = {
    OAUTH2_0: 'oauth2.0'
} as const;

export type SurveyMonkeyAuthorizationMethod1AuthMethodEnum = typeof SurveyMonkeyAuthorizationMethod1AuthMethodEnum[keyof typeof SurveyMonkeyAuthorizationMethod1AuthMethodEnum];


