/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ByMarkdownHeader } from './by-markdown-header';
// May contain unused imports in some cases
// @ts-ignore
import type { ByProgrammingLanguage } from './by-programming-language';
// May contain unused imports in some cases
// @ts-ignore
import type { BySeparator } from './by-separator';

/**
 * @type TextSplitter
 * Split text fields into chunks based on the specified method.
 * @export
 */
export type TextSplitter = ByMarkdownHeader | ByProgrammingLanguage | BySeparator;


