/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Data transfer will not be encrypted.
 * @export
 * @interface Unencrypted3
 */
export interface Unencrypted3 {
    /**
     * 
     * @type {string}
     * @memberof Unencrypted3
     */
    'encryption_method': Unencrypted3EncryptionMethodEnum;
}

export const Unencrypted3EncryptionMethodEnum = {
    UNENCRYPTED: 'unencrypted'
} as const;

export type Unencrypted3EncryptionMethodEnum = typeof Unencrypted3EncryptionMethodEnum[keyof typeof Unencrypted3EncryptionMethodEnum];


