/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The data transfer will not be encrypted.
 * @export
 * @interface Unencrypted2
 */
export interface Unencrypted2 {
    /**
     * 
     * @type {string}
     * @memberof Unencrypted2
     */
    'ssl_method': Unencrypted2SslMethodEnum;
}

export const Unencrypted2SslMethodEnum = {
    UNENCRYPTED: 'unencrypted'
} as const;

export type Unencrypted2SslMethodEnum = typeof Unencrypted2SslMethodEnum[keyof typeof Unencrypted2SslMethodEnum];


