/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ReadChangesUsingBinaryLogCDC } from './read-changes-using-binary-log-cdc';
// May contain unused imports in some cases
// @ts-ignore
import type { ScanChangesWithUserDefinedCursor1 } from './scan-changes-with-user-defined-cursor1';

/**
 * @type UpdateMethod2
 * Configures how data is extracted from the database.
 * @export
 */
export type UpdateMethod2 = ReadChangesUsingBinaryLogCDC | ScanChangesWithUserDefinedCursor1;


