/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UsernamePassword
 */
export interface UsernamePassword {
    /**
     * 
     * @type {string}
     * @memberof UsernamePassword
     */
    'type': UsernamePasswordTypeEnum;
    /**
     * Add Username for authentication.
     * @type {string}
     * @memberof UsernamePassword
     */
    'username': string;
    /**
     * Add Password for authentication.
     * @type {string}
     * @memberof UsernamePassword
     */
    'password': string;
}

export const UsernamePasswordTypeEnum = {
    USERNAME_PASSWORD: 'username_password'
} as const;

export type UsernamePasswordTypeEnum = typeof UsernamePasswordTypeEnum[keyof typeof UsernamePasswordTypeEnum];


