/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UsernameAndPassword2
 */
export interface UsernameAndPassword2 {
    /**
     * 
     * @type {string}
     * @memberof UsernameAndPassword2
     */
    'auth_type'?: UsernameAndPassword2AuthTypeEnum;
    /**
     * Enter the password associated with the username.
     * @type {string}
     * @memberof UsernameAndPassword2
     */
    'password': string;
}

export const UsernameAndPassword2AuthTypeEnum = {
    USERNAME_AND_PASSWORD: 'Username and Password'
} as const;

export type UsernameAndPassword2AuthTypeEnum = typeof UsernameAndPassword2AuthTypeEnum[keyof typeof UsernameAndPassword2AuthTypeEnum];


