/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserProvided
 */
export interface UserProvided {
    /**
     * 
     * @type {string}
     * @memberof UserProvided
     */
    'header_definition_type': UserProvidedHeaderDefinitionTypeEnum;
    /**
     * The column names that will be used while emitting the CSV records
     * @type {Array<string>}
     * @memberof UserProvided
     */
    'column_names': Array<string>;
}

export const UserProvidedHeaderDefinitionTypeEnum = {
    USER_PROVIDED: 'User Provided'
} as const;

export type UserProvidedHeaderDefinitionTypeEnum = typeof UserProvidedHeaderDefinitionTypeEnum[keyof typeof UserProvidedHeaderDefinitionTypeEnum];


