/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Authenticate using username and password (suitable for self-managed Weaviate clusters)
 * @export
 * @interface UsernamePassword2
 */
export interface UsernamePassword2 {
    /**
     * 
     * @type {string}
     * @memberof UsernamePassword2
     */
    'mode': UsernamePassword2ModeEnum;
    /**
     * Username for the Weaviate cluster
     * @type {string}
     * @memberof UsernamePassword2
     */
    'username': string;
    /**
     * Password for the Weaviate cluster
     * @type {string}
     * @memberof UsernamePassword2
     */
    'password': string;
}

export const UsernamePassword2ModeEnum = {
    USERNAME_PASSWORD: 'username_password'
} as const;

export type UsernamePassword2ModeEnum = typeof UsernamePassword2ModeEnum[keyof typeof UsernamePassword2ModeEnum];


