/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * This is the most secure mode. Always require encryption and verifies the identity of the source database server.
 * @export
 * @interface VerifyFull
 */
export interface VerifyFull {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof VerifyFull
     */
    'mode': VerifyFullModeEnum;
    /**
     * CA certificate
     * @type {string}
     * @memberof VerifyFull
     */
    'ca_certificate': string;
    /**
     * Client certificate
     * @type {string}
     * @memberof VerifyFull
     */
    'client_certificate'?: string;
    /**
     * Client key
     * @type {string}
     * @memberof VerifyFull
     */
    'client_key'?: string;
    /**
     * Password for keystorage. If you do not add it - the password will be generated automatically.
     * @type {string}
     * @memberof VerifyFull
     */
    'client_key_password'?: string;
}

export const VerifyFullModeEnum = {
    VERIFY_FULL: 'verify-full'
} as const;

export type VerifyFullModeEnum = typeof VerifyFullModeEnum[keyof typeof VerifyFullModeEnum];


