/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GeographyEnum } from './geography-enum';

/**
 * Provides details of a single workspace.
 * @export
 * @interface WorkspaceResponse
 */
export interface WorkspaceResponse {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceResponse
     */
    'workspaceId': string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceResponse
     */
    'name': string;
    /**
     * 
     * @type {GeographyEnum}
     * @memberof WorkspaceResponse
     */
    'dataResidency': GeographyEnum;
}



