/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WorkspaceCreateRequest
 */
export interface WorkspaceCreateRequest {
    /**
     * Name of the workspace
     * @type {string}
     * @memberof WorkspaceCreateRequest
     */
    'name': string;
    /**
     * ID of organization to add workspace to.
     * @type {string}
     * @memberof WorkspaceCreateRequest
     */
    'organizationId'?: string;
}

