/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ZendeskChatCredentials
 */
export interface ZendeskChatCredentials {
    /**
     * The Client ID of your OAuth application
     * @type {string}
     * @memberof ZendeskChatCredentials
     */
    'client_id'?: string;
    /**
     * The Client Secret of your OAuth application.
     * @type {string}
     * @memberof ZendeskChatCredentials
     */
    'client_secret'?: string;
}

