/* tslint:disable */
/* eslint-disable */
/**
 * airbyte-api
 * Programatically control Airbyte Cloud, OSS & Enterprise.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Zstandard1
 */
export interface Zstandard1 {
    /**
     * 
     * @type {string}
     * @memberof Zstandard1
     */
    'codec': Zstandard1CodecEnum;
    /**
     * Negative levels are \'fast\' modes akin to lz4 or snappy, levels above 9 are generally for archival purposes, and levels above 18 use a lot of memory.
     * @type {number}
     * @memberof Zstandard1
     */
    'compression_level': number;
    /**
     * If true, include a checksum with each data block.
     * @type {boolean}
     * @memberof Zstandard1
     */
    'include_checksum'?: boolean;
}

export const Zstandard1CodecEnum = {
    ZSTANDARD: 'zstandard'
} as const;

export type Zstandard1CodecEnum = typeof Zstandard1CodecEnum[keyof typeof Zstandard1CodecEnum];


